[["HMMWV","JeepWreck1","CUP_Terrains_-_Core","CIVILIAN"],
["HMMWV II","JeepWreck2","CUP_Terrains_-_Core","CIVILIAN"],
["HMMWV III","JeepWreck3","CUP_Terrains_-_Core","CIVILIAN"],
["Tatra T810 (MG/Covered)","CUP_B_T810_Armed_CZ_WDL","CUP_Vehicles","WEST"],
["Tatra T810 (Covered)","CUP_B_T810_Unarmed_CZ_WDL","CUP_Vehicles","WEST"],
["Tatra T810 (Fuel)","CUP_B_T810_Refuel_CZ_WDL","CUP_Vehicles","WEST"],
["Tatra T810 (Ammo)","CUP_B_T810_Reammo_CZ_WDL","CUP_Vehicles","WEST"],
["Tatra T810 (Repair)","CUP_B_T810_Repair_CZ_WDL","CUP_Vehicles","WEST"],
["Tatra T810 (MG/Covered)","CUP_B_T810_Armed_CZ_DES","CUP_Vehicles","WEST"],
["Tatra T810 (Covered)","CUP_B_T810_Unarmed_CZ_DES","CUP_Vehicles","WEST"],
["Tatra T810 (Fuel)","CUP_B_T810_Refuel_CZ_DES","CUP_Vehicles","WEST"],
["Tatra T810 (Ammo)","CUP_B_T810_Reammo_CZ_DES","CUP_Vehicles","WEST"],
["Tatra T810 (Repair)","CUP_B_T810_Repair_CZ_DES","CUP_Vehicles","WEST"],
["Tatra T810 (Covered)","CUP_I_T810_Unarmed_LDF","CUP_Vehicles","RESISTANCE"],
["Tatra T810 (Fuel)","CUP_I_T810_Refuel_LDF","CUP_Vehicles","RESISTANCE"],
["Tatra T810 (Ammo)","CUP_I_T810_Reammo_LDF","CUP_Vehicles","RESISTANCE"],
["Tatra T810 (Repair)","CUP_I_T810_Repair_LDF","CUP_Vehicles","RESISTANCE"],
["HEMTT Transporter","B_Truck_01_transport_F","expansion","WEST"],
["HEMTT Transporter (abgedeckt)","B_Truck_01_covered_F","expansion","WEST"],
["HEMTT","B_Truck_01_mover_F","expansion","WEST"],
["HEMTT Transport","B_Truck_01_box_F","expansion","WEST"],
["HEMTT Instandsetzung","B_Truck_01_Repair_F","expansion","WEST"],
["HEMTT Munition","B_Truck_01_ammo_F","expansion","WEST"],
["HEMTT Treibstoff","B_Truck_01_fuel_F","expansion","WEST"],
["HEMTT SanitÃ¤tsfahrzeug","B_Truck_01_medical_F","expansion","WEST"],
["HMMWV","HMMWVWreck","CUP_Terrains_-_Core","CIVILIAN"],
["Ural","UralWreck","CUP_Terrains_-_Core","CIVILIAN"],
["Pickup","datsun01Wreck","CUP_Terrains_-_Core","CIVILIAN"],
["Pickup II","datsun02Wreck","CUP_Terrains_-_Core","CIVILIAN"],
["GelÃ¤ndewagen","hiluxWreck","CUP_Terrains_-_Core","CIVILIAN"],
["UAZ","UAZWreck","CUP_Terrains_-_Core","CIVILIAN"],
["Limousine","SKODAWreck","CUP_Terrains_-_Core","CIVILIAN"],
["Auto","LADAWreck","CUP_Terrains_-_Core","CIVILIAN"],
["Ikarus 553","CUP_C_Bus_City_CIV","CUP_Vehicles","CIVILIAN"],
["Ikarus 553","CUP_C_Bus_City_TKCIV","CUP_Vehicles","CIVILIAN"],
["Ikarus 553","CUP_C_Bus_City_CRCIV","CUP_Vehicles","CIVILIAN"],
["VAZ-2103","CUP_C_Lada_CIV","CUP_Vehicles","CIVILIAN"],
["VAZ-2103 (Red)","CUP_C_Lada_White_CIV","CUP_Vehicles","CIVILIAN"],
["VAZ-2103 (Red)","CUP_C_Lada_Red_CIV","CUP_Vehicles","CIVILIAN"],
["VAZ-2103","CUP_C_Lada_TK_CIV","CUP_Vehicles","CIVILIAN"],
["VAZ-2103 (Green)","CUP_C_Lada_GreenTK_CIV","CUP_Vehicles","CIVILIAN"],
["VAZ-2103 (Jingle)","CUP_C_Lada_TK2_CIV","CUP_Vehicles","CIVILIAN"],
["VAZ-2103 (Militia)","CUP_LADA_LM_CIV","CUP_Vehicles","CIVILIAN"],
["Å koda S1203","CUP_C_S1203_CIV","CUP_Vehicles","CIVILIAN"],
["Å koda S1203 (Ambulance)","CUP_C_S1203_Ambulance_CIV","CUP_Vehicles","CIVILIAN"],
["Å koda S1203 (Ambulance)","CUP_B_S1203_Ambulance_CDF","CUP_Vehicles","WEST"],
["Å koda S1203 (Militia)","CUP_C_S1203_Militia_CIV","CUP_Vehicles","CIVILIAN"],
["Å koda S1203","CUP_C_S1203_CIV_CR","CUP_Vehicles","CIVILIAN"],
["Å koda S1203 (Ambulance)","CUP_B_S1203_Ambulance_CR","CUP_Vehicles","CIVILIAN"],
["GAZ-24 ""Volga""","CUP_C_Volha_Gray_TKCIV","CUP_Vehicles","CIVILIAN"],
["GAZ-24 ""Volga"" (Blue)","CUP_C_Volha_Blue_TKCIV","CUP_Vehicles","CIVILIAN"],
["GAZ-24 ""Volga"" (Limo)","CUP_C_Volha_Limo_TKCIV","CUP_Vehicles","CIVILIAN"],
["GAZ-24 ""Volga"" (Militia)","CUP_O_Volha_SLA","CUP_Vehicles","EAST"],
["GAZ-24 ""Volga""","CUP_C_Volha_CR_CIV","CUP_Vehicles","CIVILIAN"],
["M151A2","CUP_B_M151_HIL","CUP_Vehicles","WEST"],
["M151A2 (M2)","CUP_B_M151_M2_HIL","CUP_Vehicles","WEST"],
["M151A2","CUP_I_M151_SYND","CUP_Vehicles","RESISTANCE"],
["M151A2 (M2)","CUP_I_M151_M2_SYND","CUP_Vehicles","RESISTANCE"],
["Prowler (schw. MG)","B_T_LSV_01_armed_F","expansion","WEST"],
["Prowler (PA)","B_T_LSV_01_AT_F","expansion","WEST"],
["Prowler (Unbewaffnet)","B_T_LSV_01_unarmed_F","expansion","WEST"],
["Prowler (schw. MG)","B_LSV_01_armed_F","expansion","WEST"],
["Prowler (PA)","B_LSV_01_AT_F","expansion","WEST"],
["Prowler (Unbewaffnet)","B_LSV_01_unarmed_F","expansion","WEST"],
["Prowler (Leicht)","B_CTRG_LSV_01_light_F","expansion","WEST"],
["Qilin (Minigun)","O_T_LSV_02_armed_F","expansion","EAST"],
["Qilin (Unbewaffnet)","O_T_LSV_02_unarmed_F","expansion","EAST"],
["Qilin (PA)","O_T_LSV_02_AT_F","expansion","EAST"],
["Qilin (Minigun)","O_LSV_02_armed_F","expansion","EAST"],
["Qilin (Unbewaffnet)","O_LSV_02_unarmed_F","expansion","EAST"],
["Qilin (PA)","O_LSV_02_AT_F","expansion","EAST"],
["Hunter","B_T_MRAP_01_F","expansion","WEST"],
["Hunter-GMG","B_T_MRAP_01_gmg_F","expansion","WEST"],
["Hunter-HMG","B_T_MRAP_01_hmg_F","expansion","WEST"],
["Ifrit","O_T_MRAP_02_ghex_F","expansion","EAST"],
["Ifrit-HMG","O_T_MRAP_02_hmg_ghex_F","expansion","EAST"],
["Ifrit-GMG","O_T_MRAP_02_gmg_ghex_F","expansion","EAST"],
["GelÃ¤ndewagen","B_GEN_Offroad_01_gen_F","expansion","WEST"],
["MB 4WD","C_Offroad_02_unarmed_F","expansion","CIVILIAN"],
["MB 4WD","I_C_Offroad_02_unarmed_F","expansion","RESISTANCE"],
["MB 4WD (LMG)","I_C_Offroad_02_LMG_F","expansion","RESISTANCE"],
["MB 4WD (PA)","I_C_Offroad_02_AT_F","expansion","RESISTANCE"],
["Quadbike","O_T_Quadbike_01_ghex_F","expansion","EAST"],
["Quadbike","B_T_Quadbike_01_F","expansion","WEST"],
["HEMTT Transporter","B_T_Truck_01_transport_F","expansion","WEST"],
["HEMTT Transporter (abgedeckt)","B_T_Truck_01_covered_F","expansion","WEST"],
["HEMTT","B_T_Truck_01_mover_F","expansion","WEST"],
["HEMTT Transport","B_T_Truck_01_box_F","expansion","WEST"],
["HEMTT Instandsetzung","B_T_Truck_01_Repair_F","expansion","WEST"],
["HEMTT Munition","B_T_Truck_01_ammo_F","expansion","WEST"],
["HEMTT Treibstoff","B_T_Truck_01_fuel_F","expansion","WEST"],
["HEMTT SanitÃ¤tsfahrzeug","B_T_Truck_01_medical_F","expansion","WEST"],
["Zamak Transporter (abgedeckt)","O_T_Truck_02_F","expansion","EAST"],
["Zamak Transporter","O_T_Truck_02_transport_F","expansion","EAST"],
["Zamak Tanken","O_T_Truck_02_fuel_F","expansion","EAST"],
["Zamak Munition","O_T_Truck_02_Ammo_F","expansion","EAST"],
["Zamak Reparatur","O_T_Truck_02_Box_F","expansion","EAST"],
["Zamak SanitÃ¤tsfahrzeug","O_T_Truck_02_Medical_F","expansion","EAST"],
["Tempest-Transporter","O_T_Truck_03_transport_ghex_F","expansion","EAST"],
["Tempest-Transporter (abgedeckt)","O_T_Truck_03_covered_ghex_F","expansion","EAST"],
["Tempest Reparatur","O_T_Truck_03_repair_ghex_F","expansion","EAST"],
["Tempest Munition","O_T_Truck_03_ammo_ghex_F","expansion","EAST"],
["Tempest Tanken","O_T_Truck_03_fuel_ghex_F","expansion","EAST"],
["Tempest SanitÃ¤tsfahrzeug","O_T_Truck_03_medical_ghex_F","expansion","EAST"],
["Tempest (GerÃ¤t)","O_T_Truck_03_device_ghex_F","expansion","EAST"],
["Truck","I_C_Van_01_transport_F","expansion","RESISTANCE"],
["Krad K125 gl","gm_ge_army_k125","GM","WEST"],
["Krad K125 gl","gm_ge_bgs_k125","GM","WEST"],
["Lkw 10t mil gl Pritsche","gm_ge_army_kat1_454_cargo","GM","WEST"],
["Lkw 5t mil gl Transporter","gm_ge_army_kat1_451_cargo","GM","WEST"],
["Lkw 5t mil gl Pritsche","gm_ge_army_kat1_451_container","GM","WEST"],
["Lkw 5t mil gl Munition","gm_ge_army_kat1_451_reammo","GM","WEST"],
["Lkw 5t mil gl Treibstoff","gm_ge_army_kat1_451_refuel","GM","WEST"],
["P601","gm_gc_army_p601","GM","EAST"],
["P601","gm_gc_bgs_p601","GM","EAST"],
["Typ 1200","gm_dk_army_typ1200_cargo","GM","WEST"],
["Typ 1200","gm_ge_army_typ1200_cargo","GM","WEST"],
["Typ 1200","gm_ge_civ_typ1200","GM","CIVILIAN"],
["Typ 1200 (Post)","gm_ge_dbp_typ1200","GM","CIVILIAN"],
["Typ 1200 (Polizei)","gm_ge_pol_typ1200","GM","CIVILIAN"],
["Typ 1200 (Feuerwehr)","gm_ge_ff_typ1200","GM","CIVILIAN"],
["Lkw 2t mil gl Pritsche","gm_dk_army_u1300l_container","GM","WEST"],
["Lkw 2t mil gl Transporter","gm_ge_army_u1300l_cargo","GM","WEST"],
["Lkw 2t mil gl Pritsche","gm_ge_army_u1300l_container","GM","WEST"],
["Lkw 2t mil gl Instandsetzung","gm_ge_army_u1300l_repair","GM","WEST"],
["Lkw 2t mil gl SanitÃ¤tsfahrzeug","gm_ge_army_u1300l_medic","GM","WEST"],
["Lkw 2t mil gl Pritsche","gm_ge_civ_u1300l","GM","CIVILIAN"],
["Lkw gel. 5 Mp Fuel","gm_gc_army_ural375d_refuel","GM","EAST"],
["Lkw gel. 5 Mp SanitÃ¤tsfahrzeug","gm_gc_army_ural375d_medic","GM","EAST"],
["Lkw gel. 5 Mp Fuel","gm_gc_bgs_ural375d_refuel","GM","EAST"],
["Lkw gel. 5 Mp SanitÃ¤tsfahrzeug","gm_gc_bgs_ural375d_medic","GM","EAST"],
["Lkw gel. 5 Mp Fuel","gm_pl_army_ural375d_refuel","GM","EAST"],
["Lkw gel. 5 Mp SanitÃ¤tsfahrzeug","gm_pl_army_ural375d_medic","GM","EAST"],
["Lkw gel. 5 Instandsetzung","gm_gc_army_ural4320_repair","GM","EAST"],
["Lkw gel. 5 Transporter","gm_gc_army_ural4320_cargo","GM","EAST"],
["Lkw gel. 5 Munition","gm_gc_army_ural4320_reammo","GM","EAST"],
["Lkw gel. 5 Sattel","gm_gc_army_ural44202","GM","EAST"],
["Lkw gel. 5 Instandsetzung","gm_gc_bgs_ural4320_repair","GM","EAST"],
["Lkw gel. 5 Transporter","gm_gc_bgs_ural4320_cargo","GM","EAST"],
["Lkw gel. 5 Munition","gm_gc_bgs_ural4320_reammo","GM","EAST"],
["Lkw gel. 5 Instandsetzung","gm_pl_army_ural4320_repair","GM","EAST"],
["Lkw gel. 5 Transporter","gm_pl_army_ural4320_cargo","GM","EAST"],
["Lkw gel. 5 Munition","gm_pl_army_ural4320_reammo","GM","EAST"],
["Lkw 0.5t tmil gl","gm_ge_army_iltis_cargo","GM","WEST"],
["Lkw 0.5t tmil gl LPALR","gm_ge_army_iltis_milan","GM","WEST"],
["Lkw 0.5t tmil gl MG3","gm_ge_army_iltis_mg3","GM","WEST"],
["P601","gm_gc_civ_p601","GM","CIVILIAN"],
["P601 (Post)","gm_gc_dp_p601","GM","CIVILIAN"],
["P601 (Polizei)","gm_gc_pol_p601","GM","CIVILIAN"],
["P601 (Feuerwehr)","gm_gc_ff_p601","GM","CIVILIAN"],
["Coyote L2A1 (Desert)","CUP_B_BAF_Coyote_L2A1_D","CUP_Vehicles","WEST"],
["Coyote GMG (Desert)","CUP_B_BAF_Coyote_GMG_D","CUP_Vehicles","WEST"],
["Coyote GMG (Woodland)","CUP_B_BAF_Coyote_GMG_W","CUP_Vehicles","WEST"],
["Coyote L2A1 (Woodland)","CUP_B_BAF_Coyote_L2A1_W","CUP_Vehicles","WEST"],
["Dingo 2 (MG) (Woodland)","CUP_B_Dingo_CZ_Wdl","CUP_Vehicles","WEST"],
["Dingo 2 (MG) (Desert)","CUP_B_Dingo_CZ_Des","CUP_Vehicles","WEST"],
["Dingo 2 (GL) (Woodland)","CUP_B_Dingo_GL_CZ_Wdl","CUP_Vehicles","WEST"],
["Dingo 2 (GL) (Desert)","CUP_B_Dingo_GL_CZ_Des","CUP_Vehicles","WEST"],
["Dingo 2 (MG) (Woodland)","CUP_B_Dingo_GER_Wdl","CUP_Vehicles","WEST"],
["Dingo 2 (MG) (Desert)","CUP_B_Dingo_GER_Des","CUP_Vehicles","WEST"],
["Dingo 2 (GL) (Woodland)","CUP_B_Dingo_GL_GER_Wdl","CUP_Vehicles","WEST"],
["Dingo 2 (GL) (Desert)","CUP_B_Dingo_GL_GER_Des","CUP_Vehicles","WEST"],
["Hilux","CUP_I_Hilux_unarmed_TK","CUP_Vehicles","RESISTANCE"],
["Hilux Full Armor Mode","CUP_I_Hilux_armored_unarmed_TK","CUP_Vehicles","RESISTANCE"],
["Hilux (DShKM)","CUP_I_Hilux_DSHKM_TK","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (DShKM)","CUP_I_Hilux_armored_DSHKM_TK","CUP_Vehicles","RESISTANCE"],
["Hilux (SPG-9)","CUP_I_Hilux_SPG9_TK","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (SPG-9)","CUP_I_Hilux_armored_SPG9_TK","CUP_Vehicles","RESISTANCE"],
["Hilux (Igla)","CUP_I_Hilux_igla_TK","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (Igla)","CUP_I_Hilux_armored_igla_TK","CUP_Vehicles","RESISTANCE"],
["Hilux (Metis)","CUP_I_Hilux_metis_TK","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (Metis)","CUP_I_Hilux_armored_metis_TK","CUP_Vehicles","RESISTANCE"],
["Hilux (Podnos)","CUP_I_Hilux_podnos_TK","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (Podnos)","CUP_I_Hilux_armored_podnos_TK","CUP_Vehicles","RESISTANCE"],
["Hilux (MLRS)","CUP_I_Hilux_MLRS_TK","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (MLRS)","CUP_I_Hilux_armored_MLRS_TK","CUP_Vehicles","RESISTANCE"],
["Hilux (ZU-23-2)","CUP_I_Hilux_zu23_TK","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (ZU-23-2)","CUP_I_Hilux_armored_zu23_TK","CUP_Vehicles","RESISTANCE"],
["Hilux (BTR-60)","CUP_I_Hilux_btr60_TK","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (BTR-60)","CUP_I_Hilux_armored_BTR60_TK","CUP_Vehicles","RESISTANCE"],
["Hilux (AGS-30)","CUP_I_Hilux_AGS30_TK","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (AGS-30)","CUP_I_Hilux_armored_AGS30_TK","CUP_Vehicles","RESISTANCE"],
["Hilux (M2)","CUP_I_Hilux_M2_TK","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (M2)","CUP_I_Hilux_armored_M2_TK","CUP_Vehicles","RESISTANCE"],
["Hilux (UB-32)","CUP_I_Hilux_UB32_TK","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (UB-32)","CUP_I_Hilux_armored_UB32_TK","CUP_Vehicles","RESISTANCE"],
["Hilux (BMP-1)","CUP_I_Hilux_BMP1_TK","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (BMP-1)","CUP_I_Hilux_armored_BMP1_TK","CUP_Vehicles","RESISTANCE"],
["Hilux","CUP_O_Hilux_unarmed_TK_INS","CUP_Vehicles","EAST"],
["Hilux Full Armor Mode","CUP_O_Hilux_armored_unarmed_TK_INS","CUP_Vehicles","EAST"],
["Hilux (DShKM)","CUP_O_Hilux_DSHKM_TK_INS","CUP_Vehicles","EAST"],
["Hilux Armored (DShKM)","CUP_O_Hilux_armored_DSHKM_TK_INS","CUP_Vehicles","EAST"],
["Hilux (SPG-9)","CUP_O_Hilux_SPG9_TK_INS","CUP_Vehicles","EAST"],
["Hilux Armored (SPG-9)","CUP_O_Hilux_armored_SPG9_TK_INS","CUP_Vehicles","EAST"],
["Hilux (Igla)","CUP_O_Hilux_igla_TK_INS","CUP_Vehicles","EAST"],
["Hilux Armored (Igla)","CUP_O_Hilux_armored_igla_TK_INS","CUP_Vehicles","EAST"],
["Hilux (Metis)","CUP_O_Hilux_metis_TK_INS","CUP_Vehicles","EAST"],
["Hilux Armored (Metis)","CUP_O_Hilux_armored_metis_TK_INS","CUP_Vehicles","EAST"],
["Hilux (Podnos)","CUP_O_Hilux_podnos_TK_INS","CUP_Vehicles","EAST"],
["Hilux Armored (Podnos)","CUP_O_Hilux_armored_podnos_TK_INS","CUP_Vehicles","EAST"],
["Hilux (MLRS)","CUP_O_Hilux_MLRS_TK_INS","CUP_Vehicles","EAST"],
["Hilux Armored (MLRS)","CUP_O_Hilux_armored_MLRS_TK_INS","CUP_Vehicles","EAST"],
["Hilux (ZU-23-2)","CUP_O_Hilux_zu23_TK_INS","CUP_Vehicles","EAST"],
["Hilux Armored (ZU-23-2)","CUP_O_Hilux_armored_zu23_TK_INS","CUP_Vehicles","EAST"],
["Hilux (BTR-60)","CUP_O_Hilux_btr60_TK_INS","CUP_Vehicles","EAST"],
["Hilux Armored (BTR-60)","CUP_O_Hilux_armored_BTR60_TK_INS","CUP_Vehicles","EAST"],
["Hilux (AGS-30)","CUP_O_Hilux_AGS30_TK_INS","CUP_Vehicles","EAST"],
["Hilux Armored (AGS-30)","CUP_O_Hilux_armored_AGS30_TK_INS","CUP_Vehicles","EAST"],
["Hilux (M2)","CUP_O_Hilux_M2_TK_INS","CUP_Vehicles","EAST"],
["Hilux Armored (M2)","CUP_O_Hilux_armored_M2_TK_INS","CUP_Vehicles","EAST"],
["Hilux (UB-32)","CUP_O_Hilux_UB32_TK_INS","CUP_Vehicles","EAST"],
["Hilux Armored (UB-32)","CUP_O_Hilux_armored_UB32_TK_INS","CUP_Vehicles","EAST"],
["Hilux (BMP-1)","CUP_O_Hilux_BMP1_TK_INS","CUP_Vehicles","EAST"],
["Hilux Armored (BMP-1)","CUP_O_Hilux_armored_BMP1_TK_INS","CUP_Vehicles","EAST"],
["Hilux","CUP_O_Hilux_unarmed_CHDKZ","CUP_Vehicles","EAST"],
["Hilux (DShKM)","CUP_O_Hilux_DSHKM_CHDKZ","CUP_Vehicles","EAST"],
["Hilux (SPG-9)","CUP_O_Hilux_SPG9_CHDKZ","CUP_Vehicles","EAST"],
["Hilux (Igla)","CUP_O_Hilux_igla_CHDKZ","CUP_Vehicles","EAST"],
["Hilux (Metis)","CUP_O_Hilux_metis_CHDKZ","CUP_Vehicles","EAST"],
["Hilux (Podnos)","CUP_O_Hilux_podnos_CHDKZ","CUP_Vehicles","EAST"],
["Hilux (MLRS)","CUP_O_Hilux_MLRS_CHDKZ","CUP_Vehicles","EAST"],
["Hilux (ZU-23-2)","CUP_O_Hilux_zu23_CHDKZ","CUP_Vehicles","EAST"],
["Hilux (AGS-30)","CUP_O_Hilux_AGS30_CHDKZ","CUP_Vehicles","EAST"],
["Hilux (UB-32)","CUP_O_Hilux_UB32_CHDKZ","CUP_Vehicles","EAST"],
["Hilux","CUP_O_Hilux_unarmed_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux Full Armor Mode","CUP_O_Hilux_armored_unarmed_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux (DShKM)","CUP_O_Hilux_DSHKM_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux Armored (DShKM)","CUP_O_Hilux_armored_DSHKM_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux (SPG-9)","CUP_O_Hilux_SPG9_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux Armored (SPG-9)","CUP_O_Hilux_armored_SPG9_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux (Igla)","CUP_O_Hilux_igla_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux Armored (Igla)","CUP_O_Hilux_armored_igla_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux (Metis)","CUP_O_Hilux_metis_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux Armored (Metis)","CUP_O_Hilux_armored_metis_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux (Podnos)","CUP_O_Hilux_podnos_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux Armored (Podnos)","CUP_O_Hilux_armored_podnos_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux (MLRS)","CUP_O_Hilux_MLRS_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux Armored (MLRS)","CUP_O_Hilux_armored_MLRS_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux (ZU-23-2)","CUP_O_Hilux_zu23_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux Armored (ZU-23-2)","CUP_O_Hilux_armored_zu23_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux (BTR-60)","CUP_O_Hilux_btr60_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux Armored (BTR-60)","CUP_O_Hilux_armored_BTR60_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux (AGS-30)","CUP_O_Hilux_AGS30_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux Armored (AGS-30)","CUP_O_Hilux_armored_AGS30_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux (M2)","CUP_O_Hilux_M2_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux Armored (M2)","CUP_O_Hilux_armored_M2_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux (UB-32)","CUP_O_Hilux_UB32_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux Armored (UB-32)","CUP_O_Hilux_armored_UB32_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux (BMP-1)","CUP_O_Hilux_BMP1_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux Armored (BMP-1)","CUP_O_Hilux_armored_BMP1_OPF_G_F","CUP_Vehicles","EAST"],
["Hilux","CUP_I_Hilux_unarmed_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux Full Armor Mode","CUP_I_Hilux_armored_unarmed_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux (DShKM)","CUP_I_Hilux_DSHKM_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (DShKM)","CUP_I_Hilux_armored_DSHKM_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux (SPG-9)","CUP_I_Hilux_SPG9_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (SPG-9)","CUP_I_Hilux_armored_SPG9_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux (Igla)","CUP_I_Hilux_igla_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (Igla)","CUP_I_Hilux_armored_igla_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux (Metis)","CUP_I_Hilux_metis_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (Metis)","CUP_I_Hilux_armored_metis_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux (Podnos)","CUP_I_Hilux_podnos_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (Podnos)","CUP_I_Hilux_armored_podnos_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux (MLRS)","CUP_I_Hilux_MLRS_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (MLRS)","CUP_I_Hilux_armored_MLRS_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux (ZU-23-2)","CUP_I_Hilux_zu23_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (ZU-23-2)","CUP_I_Hilux_armored_zu23_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux (BTR-60)","CUP_I_Hilux_btr60_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (BTR-60)","CUP_I_Hilux_armored_BTR60_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux (AGS-30)","CUP_I_Hilux_AGS30_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (AGS-30)","CUP_I_Hilux_armored_AGS30_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux (M2)","CUP_I_Hilux_M2_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (M2)","CUP_I_Hilux_armored_M2_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux (UB-32)","CUP_I_Hilux_UB32_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (UB-32)","CUP_I_Hilux_armored_UB32_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux (BMP-1)","CUP_I_Hilux_BMP1_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (BMP-1)","CUP_I_Hilux_armored_BMP1_IND_G_F","CUP_Vehicles","RESISTANCE"],
["Hilux","CUP_B_Hilux_unarmed_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux Full Armor Mode","CUP_B_Hilux_armored_unarmed_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux (DShKM)","CUP_B_Hilux_DSHKM_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux Armored (DShKM)","CUP_B_Hilux_armored_DSHKM_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux (SPG-9)","CUP_B_Hilux_SPG9_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux Armored (SPG-9)","CUP_B_Hilux_armored_SPG9_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux (Igla)","CUP_B_Hilux_igla_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux Armored (Igla)","CUP_B_Hilux_armored_igla_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux (Metis)","CUP_B_Hilux_metis_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux Armored (Metis)","CUP_B_Hilux_armored_metis_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux (Podnos)","CUP_B_Hilux_podnos_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux Armored (Podnos)","CUP_B_Hilux_armored_podnos_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux (MLRS)","CUP_B_Hilux_MLRS_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux Armored (MLRS)","CUP_B_Hilux_armored_MLRS_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux (ZU-23-2)","CUP_B_Hilux_zu23_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux Armored (ZU-23-2)","CUP_B_Hilux_armored_zu23_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux (BTR-60)","CUP_B_Hilux_btr60_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux Armored (BTR-60)","CUP_B_Hilux_armored_BTR60_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux (AGS-30)","CUP_B_Hilux_AGS30_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux Armored (AGS-30)","CUP_B_Hilux_armored_AGS30_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux (M2)","CUP_B_Hilux_M2_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux Armored (M2)","CUP_B_Hilux_armored_M2_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux (UB-32)","CUP_B_Hilux_UB32_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux Armored (UB-32)","CUP_B_Hilux_armored_UB32_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux (BMP-1)","CUP_B_Hilux_BMP1_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux Armored (BMP-1)","CUP_B_Hilux_armored_BMP1_BLU_G_F","CUP_Vehicles","WEST"],
["Hilux","CUP_I_Hilux_unarmed_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux Full Armor Mode","CUP_I_Hilux_armored_unarmed_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux (DShKM)","CUP_I_Hilux_DSHKM_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (DShKM)","CUP_I_Hilux_armored_DSHKM_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux (SPG-9)","CUP_I_Hilux_SPG9_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (SPG-9)","CUP_I_Hilux_armored_SPG9_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux (Igla)","CUP_I_Hilux_igla_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (Igla)","CUP_I_Hilux_armored_igla_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux (Metis)","CUP_I_Hilux_metis_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (Metis)","CUP_I_Hilux_armored_metis_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux (Podnos)","CUP_I_Hilux_podnos_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (Podnos)","CUP_I_Hilux_armored_podnos_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux (MLRS)","CUP_I_Hilux_MLRS_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (MLRS)","CUP_I_Hilux_armored_MLRS_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux (ZU-23-2)","CUP_I_Hilux_zu23_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (ZU-23-2)","CUP_I_Hilux_armored_zu23_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux (BTR-60)","CUP_I_Hilux_btr60_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (BTR-60)","CUP_I_Hilux_armored_BTR60_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux (AGS-30)","CUP_I_Hilux_AGS30_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (AGS-30)","CUP_I_Hilux_armored_AGS30_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux (UB-32)","CUP_I_Hilux_UB32_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (UB-32)","CUP_I_Hilux_armored_UB32_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux (BMP-1)","CUP_I_Hilux_BMP1_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux Armored (BMP-1)","CUP_I_Hilux_armored_BMP1_NAPA","CUP_Vehicles","RESISTANCE"],
["Hilux","CUP_O_Hilux_unarmed_CR_CIV","CUP_Vehicles","CIVILIAN"],
["Hilux (Red)","CUP_O_Hilux_unarmed_CR_CIV_Red","CUP_Vehicles","CIVILIAN"],
["Hilux (Tan)","CUP_O_Hilux_unarmed_CR_CIV_Tan","CUP_Vehicles","CIVILIAN"],
["Hilux (White)","CUP_O_Hilux_unarmed_CR_CIV_White","CUP_Vehicles","CIVILIAN"],
["Hilux","CUP_O_Hilux_unarmed_TK_CIV","CUP_Vehicles","CIVILIAN"],
["Hilux (Red)","CUP_O_Hilux_unarmed_TK_CIV_Red","CUP_Vehicles","CIVILIAN"],
["Hilux (Tan)","CUP_O_Hilux_unarmed_TK_CIV_Tan","CUP_Vehicles","CIVILIAN"],
["Hilux (White)","CUP_O_Hilux_unarmed_TK_CIV_White","CUP_Vehicles","CIVILIAN"],
["Jackal2 L2A1 Desert","CUP_B_Jackal2_GMG_GB_D","CUP_Vehicles","WEST"],
["Jackal2 GMG Woodland","CUP_B_Jackal2_GMG_GB_W","CUP_Vehicles","WEST"],
["Jackal2 L2A1 Desert","CUP_B_Jackal2_L2A1_GB_D","CUP_Vehicles","WEST"],
["Jackal2 L2A1 Woodland","CUP_B_Jackal2_L2A1_GB_W","CUP_Vehicles","WEST"],
["Jackal2 GMG","CUP_B_Jackal2_GMG_FIA","CUP_Vehicles","WEST"],
["Jackal2 L2A1","CUP_B_Jackal2_L2A1_FIA","CUP_Vehicles","WEST"],
["Kamaz 5350","CUP_O_Kamaz_RU","CUP_Vehicles","EAST"],
["Kamaz 5350 (Open)","CUP_O_Kamaz_Open_RU","CUP_Vehicles","EAST"],
["Kamaz 5350 (Repair)","CUP_O_Kamaz_Repair_RU","CUP_Vehicles","EAST"],
["Kamaz 5350 (Ammo)","CUP_O_Kamaz_Reammo_RU","CUP_Vehicles","EAST"],
["Kamaz 5350 (Fuel)","CUP_O_Kamaz_Refuel_RU","CUP_Vehicles","EAST"],
["Kamaz 5350","CUP_B_Kamaz_CDF","CUP_Vehicles","WEST"],
["Kamaz 5350 (Open)","CUP_B_Kamaz_Open_CDF","CUP_Vehicles","WEST"],
["Kamaz 5350 (Fuel)","CUP_B_Kamaz_Refuel_CDF","CUP_Vehicles","WEST"],
["Kamaz 5350 (Repair)","CUP_B_Kamaz_Repair_CDF","CUP_Vehicles","WEST"],
["Kamaz 5350 (Ammo)","CUP_B_Kamaz_Reammo_CDF","CUP_Vehicles","WEST"],
["Qilin (Unbewaffnet)","CUP_I_LSV_02_unarmed_ION","CUP_Vehicles","RESISTANCE"],
["Qilin (Bewaffnet)","CUP_I_LSV_02_AT_ION","CUP_Vehicles","RESISTANCE"],
["Qilin (Minigun)","CUP_I_LSV_02_Minigun_ION","CUP_Vehicles","RESISTANCE"],
["Mastiff PPV HMG Desert","CUP_B_Mastiff_HMG_GB_D","CUP_Vehicles","WEST"],
["Mastiff PPV HMG Woodland","CUP_B_Mastiff_HMG_GB_W","CUP_Vehicles","WEST"],
["Mastiff PPV GMG Desert","CUP_B_Mastiff_GMG_GB_D","CUP_Vehicles","WEST"],
["Mastiff PPV GMG Woodland","CUP_B_Mastiff_GMG_GB_W","CUP_Vehicles","WEST"],
["Mastiff PPV LMG Desert","CUP_B_Mastiff_LMG_GB_D","CUP_Vehicles","WEST"],
["Mastiff PPV LMG Woodland","CUP_B_Mastiff_LMG_GB_W","CUP_Vehicles","WEST"],
["M-ATV","CUP_I_MATV_ION","CUP_Vehicles","RESISTANCE"],
["M-ATV (HMG)","CUP_I_MATV_HMG_ION","CUP_Vehicles","RESISTANCE"],
["M-ATV (GMG)","CUP_I_MATV_GMG_ION","CUP_Vehicles","RESISTANCE"],
["Skoda Octavia","CUP_C_Octavia_CIV","CUP_Vehicles","CIVILIAN"],
["MB 4WD","CUP_I_4WD_unarmed_ION","CUP_Vehicles","RESISTANCE"],
["MB 4WD (AT)","CUP_I_4WD_AT_ION","CUP_Vehicles","RESISTANCE"],
["MB 4WD (LMG)","CUP_I_4WD_LMG_ION","CUP_Vehicles","RESISTANCE"],
["RG-31 Nyala M2","CUP_B_RG31_M2_OD_USMC","CUP_Vehicles","WEST"],
["RG-31 Nyala M2 GC","CUP_B_RG31_M2_OD_GC_USMC","CUP_Vehicles","WEST"],
["RG-31 Mk.19","CUP_B_RG31_Mk19_OD_USMC","CUP_Vehicles","WEST"],
["RG-31 Mk5E M2","CUP_B_RG31E_M2_OD_USMC","CUP_Vehicles","WEST"],
["RG-31 Nyala M2","CUP_B_RG31_M2_USA","CUP_Vehicles","WEST"],
["RG-31 Nyala M2 GC","CUP_B_RG31_M2_GC_USA","CUP_Vehicles","WEST"],
["RG-31 Mk.19","CUP_B_RG31_Mk19_USA","CUP_Vehicles","WEST"],
["RG-31 Mk5E M2","CUP_B_RG31E_M2_USA","CUP_Vehicles","WEST"],
["RG-31 Nyala M2","CUP_I_RG31_M2_ION","CUP_Vehicles","RESISTANCE"],
["RG-31 Nyala M2 GC","CUP_I_RG31_M2_GC_ION","CUP_Vehicles","RESISTANCE"],
["RG-31 Mk.19","CUP_I_RG31_Mk19_ION","CUP_Vehicles","RESISTANCE"],
["RG-31 Mk5E M2","CUP_I_RG31E_M2_ION","CUP_Vehicles","RESISTANCE"],
["Ridgeback PPV HMG Desert","CUP_B_Ridgback_HMG_GB_D","CUP_Vehicles","WEST"],
["Ridgeback PPV HMG Woodland","CUP_B_Ridgback_HMG_GB_W","CUP_Vehicles","WEST"],
["Ridgeback PPV GMG Desert","CUP_B_Ridgback_GMG_GB_D","CUP_Vehicles","WEST"],
["Ridgeback PPV GMG Woodland","CUP_B_Ridgback_GMG_GB_W","CUP_Vehicles","WEST"],
["Ridgeback PPV LMG Desert","CUP_B_Ridgback_LMG_GB_D","CUP_Vehicles","WEST"],
["Ridgeback PPV LMG Woodland","CUP_B_Ridgback_LMG_GB_W","CUP_Vehicles","WEST"],
["Å koda 105 L","CUP_C_Skoda_CR_CIV","CUP_Vehicles","CIVILIAN"],
["Å koda 105 L (White)","CUP_C_Skoda_White_CIV","CUP_Vehicles","CIVILIAN"],
["Å koda 105 L (Red)","CUP_C_Skoda_Red_CIV","CUP_Vehicles","CIVILIAN"],
["Å koda 105 L (Blue)","CUP_C_Skoda_Blue_CIV","CUP_Vehicles","CIVILIAN"],
["Å koda 105 L (Green)","CUP_C_Skoda_Green_CIV","CUP_Vehicles","CIVILIAN"],
["Fennek","CUP_I_FENNEK_ION","CUP_Vehicles","RESISTANCE"],
["Fennek HMG","CUP_I_FENNEK_HMG_ION","CUP_Vehicles","RESISTANCE"],
["Fennek GMG","CUP_I_FENNEK_GMG_ION","CUP_Vehicles","RESISTANCE"],
["Fennek (Woodland)","CUP_B_FENNEK_GER_Wdl","CUP_Vehicles","WEST"],
["Fennek (Desert)","CUP_B_FENNEK_GER_Des","CUP_Vehicles","WEST"],
["Towing Tractor","CUP_B_TowingTractor_USMC","CUP_Vehicles","WEST"],
["Towing Tractor","CUP_B_TowingTractor_CZ","CUP_Vehicles","WEST"],
["Towing Tractor","CUP_B_TowingTractor_GB","CUP_Vehicles","WEST"],
["Towing Tractor","CUP_B_TowingTractor_NATO","CUP_Vehicles","WEST"],
["Towing Tractor","CUP_B_TowingTractor_USA","CUP_Vehicles","WEST"],
["Towing Tractor","CUP_O_TowingTractor_RU","CUP_Vehicles","EAST"],
["Towing Tractor","CUP_O_TowingTractor_CSAT","CUP_Vehicles","EAST"],
["Towing Tractor","CUP_I_TowingTractor_AAF","CUP_Vehicles","RESISTANCE"],
["Towing Tractor","CUP_I_TowingTractor_ION","CUP_Vehicles","RESISTANCE"],
["Towing Tractor","CUP_I_TowingTractor_RACS","CUP_Vehicles","RESISTANCE"],
["Towing Tractor","CUP_C_TowingTractor_CIV","CUP_Vehicles","CIVILIAN"],
["Transporter","CUP_I_Van_Transport_ION","CUP_Vehicles","RESISTANCE"],
["Transporter (ViV)","CUP_I_Van_Cargo_ION","CUP_Vehicles","RESISTANCE"],
["Van (Repair)","CUP_I_Van_Repair_ION","CUP_Vehicles","RESISTANCE"],
["Van (Ammo)","CUP_I_Van_ammo_ION","CUP_Vehicles","RESISTANCE"],
["Golf IV 1.9 TDI","CUP_C_Golf4_CR_Civ","CUP_Vehicles","CIVILIAN"],
["Golf IV 1.9 TDI (Sport)","CUP_C_Golf4_Sport_CR_Civ","CUP_Vehicles","CIVILIAN"],
["Golf (Red)","CUP_C_Golf4_red_Civ","CUP_Vehicles","CIVILIAN"],
["Golf (Black)","CUP_C_Golf4_black_Civ","CUP_Vehicles","CIVILIAN"],
["Golf (Yellow)","CUP_C_Golf4_yellow_Civ","CUP_Vehicles","CIVILIAN"],
["Golf (Blue)","CUP_C_Golf4_blue_Civ","CUP_Vehicles","CIVILIAN"],
["Golf (White)","CUP_C_Golf4_white_Civ","CUP_Vehicles","CIVILIAN"],
["Golf (Green)","CUP_C_Golf4_green_Civ","CUP_Vehicles","CIVILIAN"],
["Golf IV 1.9 TDI","CUP_C_Golf4_random_Civ","CUP_Vehicles","CIVILIAN"],
["Golf IV 1.9 TDI (Sport)","CUP_C_Golf4_Sport_random_Civ","CUP_Vehicles","CIVILIAN"],
["Golf (Sport/White Blood)","CUP_C_Golf4_whiteblood_Civ","CUP_Vehicles","CIVILIAN"],
["Golf (Sport/Camo)","CUP_C_Golf4_camo_Civ","CUP_Vehicles","CIVILIAN"],
["Golf (Sport/Camo Digital)","CUP_C_Golf4_camodigital_Civ","CUP_Vehicles","CIVILIAN"],
["Golf (Sport/Camo Dark)","CUP_C_Golf4_camodark_Civ","CUP_Vehicles","CIVILIAN"],
["Golf (Sport/Reptile)","CUP_C_Golf4_reptile_Civ","CUP_Vehicles","CIVILIAN"],
["Golf (Sport/Kitty)","CUP_C_Golf4_kitty_Civ","CUP_Vehicles","CIVILIAN"],
["Golf (Sport/Crowe)","CUP_C_Golf4_crowe_Civ","CUP_Vehicles","CIVILIAN"],
["Wolfhound TSV HMG Desert","CUP_B_Wolfhound_HMG_GB_D","CUP_Vehicles","WEST"],
["Wolfhound TSV HMG Woodland","CUP_B_Wolfhound_HMG_GB_W","CUP_Vehicles","WEST"],
["Wolfhound TSV GMG Desert","CUP_B_Wolfhound_GMG_GB_D","CUP_Vehicles","WEST"],
["Wolfhound TSV GMG Woodland","CUP_B_Wolfhound_GMG_GB_W","CUP_Vehicles","WEST"],
["Wolfhound TSV LMG Desert","CUP_B_Wolfhound_LMG_GB_D","CUP_Vehicles","WEST"],
["Wolfhound TSV LMG Woodland","CUP_B_Wolfhound_LMG_GB_W","CUP_Vehicles","WEST"],
["Datsun 620 Pickup (PK)","CUP_O_Datsun_PK","CUP_Vehicles","EAST"],
["Datsun 620 Pickup (PK) Woodland","CUP_O_Datsun_PK_Random","CUP_Vehicles","EAST"],
["Datsun 620 Pickup (PK)","CUP_I_Datsun_PK","CUP_Vehicles","RESISTANCE"],
["Datsun 620 Pickup (PK) Woodland","CUP_I_Datsun_PK_Random","CUP_Vehicles","RESISTANCE"],
["Datsun 620 Pickup (PK)","CUP_I_Datsun_PK_TK","CUP_Vehicles","RESISTANCE"],
["Datsun 620 Pickup (PK) Desert","CUP_I_Datsun_PK_TK_Random","CUP_Vehicles","RESISTANCE"],
["Datsun 620 Pickup","CUP_C_Datsun","CUP_Vehicles","CIVILIAN"],
["Datsun 620 Pickup (5 seats)","CUP_C_Datsun_4seat","CUP_Vehicles","CIVILIAN"],
["Datsun 620 Pickup Woodland","CUP_O_Datsun_4seat","CUP_Vehicles","EAST"],
["Datsun 620 Pickup Woodland","CUP_I_Datsun_4seat","CUP_Vehicles","RESISTANCE"],
["Datsun 620 Pickup Desert","CUP_I_Datsun_4seat_TK","CUP_Vehicles","RESISTANCE"],
["Datsun 620 Pickup (Old)","CUP_C_Datsun_Plain","CUP_Vehicles","CIVILIAN"],
["Datsun 620 Pickup (Covered)","CUP_C_Datsun_Covered","CUP_Vehicles","CIVILIAN"],
["Datsun 620 Pickup (Tubeframe)","CUP_C_Datsun_Tubeframe","CUP_Vehicles","CIVILIAN"],
["HMMWV (Unarmed)","CUP_B_HMMWV_Unarmed_USMC","CUP_Vehicles","WEST"],
["HMMWV M2","CUP_B_HMMWV_M2_USMC","CUP_Vehicles","WEST"],
["HMMWV (MK19)","CUP_B_HMMWV_MK19_USMC","CUP_Vehicles","WEST"],
["HMMWV (TOW)","CUP_B_HMMWV_TOW_USMC","CUP_Vehicles","WEST"],
["HMMWV (M240)","CUP_B_HMMWV_M1114_USMC","CUP_Vehicles","WEST"],
["HMMWV (Ambulance)","CUP_B_HMMWV_Ambulance_USMC","CUP_Vehicles","WEST"],
["HMMWV (Unarmed)","CUP_B_HMMWV_Unarmed_USA","CUP_Vehicles","WEST"],
["HMMWV M2","CUP_B_HMMWV_M2_USA","CUP_Vehicles","WEST"],
["HMMWV (MK19)","CUP_B_HMMWV_MK19_USA","CUP_Vehicles","WEST"],
["HMMWV (TOW)","CUP_B_HMMWV_TOW_USA","CUP_Vehicles","WEST"],
["HMMWV (Ambulance)","CUP_B_HMMWV_Ambulance_USA","CUP_Vehicles","WEST"],
["HMMWV (Transport)","CUP_B_HMMWV_Transport_USA","CUP_Vehicles","WEST"],
["HMMWV M1151 M2","CUP_B_HMMWV_M2_GPK_USA","CUP_Vehicles","WEST"],
["HMMWV UAV Terminal","CUP_B_HMMWV_Terminal_USA","CUP_Vehicles","WEST"],
["HMMWV SOV (Mk19)","CUP_B_HMMWV_SOV_USA","CUP_Vehicles","WEST"],
["HMMWV SOV (M2)","CUP_B_HMMWV_SOV_M2_USA","CUP_Vehicles","WEST"],
["HMMWV CROWS M2","CUP_B_HMMWV_Crows_M2_USA","CUP_Vehicles","WEST"],
["HMMWV CROWS MK19","CUP_B_HMMWV_Crows_MK19_USA","CUP_Vehicles","WEST"],
["HMMWV (Unarmed)","CUP_B_HMMWV_Unarmed_NATO_T","CUP_Vehicles","WEST"],
["HMMWV M2","CUP_B_HMMWV_M2_NATO_T","CUP_Vehicles","WEST"],
["HMMWV (MK19)","CUP_B_HMMWV_MK19_NATO_T","CUP_Vehicles","WEST"],
["HMMWV (TOW)","CUP_B_HMMWV_TOW_NATO_T","CUP_Vehicles","WEST"],
["HMMWV (Ambulance)","CUP_B_HMMWV_Ambulance_NATO_T","CUP_Vehicles","WEST"],
["HMMWV (Transport)","CUP_B_HMMWV_Transport_NATO_T","CUP_Vehicles","WEST"],
["HMMWV M1151 M2","CUP_B_HMMWV_M2_GPK_NATO_T","CUP_Vehicles","WEST"],
["HMMWV UAV Terminal","CUP_B_HMMWV_Terminal_NATO_T","CUP_Vehicles","WEST"],
["HMMWV SOV (Mk19)","CUP_B_HMMWV_SOV_NATO_T","CUP_Vehicles","WEST"],
["HMMWV SOV (M2)","CUP_B_HMMWV_SOV_M2_NATO_T","CUP_Vehicles","WEST"],
["HMMWV CROWS M2","CUP_B_HMMWV_Crows_M2_NATO_T","CUP_Vehicles","WEST"],
["HMMWV CROWS MK19","CUP_B_HMMWV_Crows_MK19_NATO_T","CUP_Vehicles","WEST"],
["HMMWV M1151 M2","CUP_B_HMMWV_M2_GPK_ACR","CUP_Vehicles","WEST"],
["HMMWV M1114 DSHKM","CUP_B_HMMWV_DSHKM_GPK_ACR","CUP_Vehicles","WEST"],
["HMMWV M1114 AGS","CUP_B_HMMWV_AGS_GPK_ACR","CUP_Vehicles","WEST"],
["HMMWV (Ambulance)","CUP_B_HMMWV_Ambulance_ACR","CUP_Vehicles","WEST"],
["Ikarus 260","CUP_C_Ikarus_TKC","CUP_Vehicles","CIVILIAN"],
["Ikarus 260","CUP_C_Ikarus_Chernarus","CUP_Vehicles","CIVILIAN"],
["Land Rover 110 (Transport)","CUP_C_LR_Transport_CTK","CUP_Vehicles","CIVILIAN"],
["Land Rover 110 (Transport) Woodland","CUP_B_LR_Transport_CZ_W","CUP_Vehicles","WEST"],
["Land Rover 110 (Transport) Desert","CUP_B_LR_Transport_CZ_D","CUP_Vehicles","WEST"],
["Land Rover 110 (M2) Woodland","CUP_B_LR_MG_CZ_W","CUP_Vehicles","WEST"],
["Land Rover 110 (Ambulance) Woodland","CUP_B_LR_Ambulance_CZ_W","CUP_Vehicles","WEST"],
["Land Rover 110 (Ambulance) Desert","CUP_B_LR_Ambulance_CZ_D","CUP_Vehicles","WEST"],
["Land Rover 110 (Special) Woodland","CUP_B_LR_Special_CZ_W","CUP_Vehicles","WEST"],
["Land Rover 110 (Special) Desert","CUP_B_LR_Special_Des_CZ_D","CUP_Vehicles","WEST"],
["Land Rover 110 (Transport) Woodland","CUP_B_LR_Transport_GB_W","CUP_Vehicles","WEST"],
["Land Rover 110 (Transport) Desert","CUP_B_LR_Transport_GB_D","CUP_Vehicles","WEST"],
["Land Rover 110 (M2) Woodland","CUP_B_LR_MG_GB_W","CUP_Vehicles","WEST"],
["Land Rover 110 (M2) Desert","CUP_B_LR_MG_GB_D","CUP_Vehicles","WEST"],
["Land Rover 110 (Ambulance) Woodland","CUP_B_LR_Ambulance_GB_W","CUP_Vehicles","WEST"],
["Land Rover 110 (Ambulance) Desert","CUP_B_LR_Ambulance_GB_D","CUP_Vehicles","WEST"],
["Land Rover 110 (M2 Special) Woodland","CUP_B_LR_Special_M2_GB_W","CUP_Vehicles","WEST"],
["Land Rover 110 (M2 Special) Desert","CUP_B_LR_Special_M2_GB_D","CUP_Vehicles","WEST"],
["Land Rover 110 (GMG Special) Woodland","CUP_B_LR_Special_GMG_GB_W","CUP_Vehicles","WEST"],
["Land Rover 110 (GMG Special) Desert","CUP_B_LR_Special_GMG_GB_D","CUP_Vehicles","WEST"],
["Land Rover 110 (Transport)","CUP_I_LR_Transport_AAF","CUP_Vehicles","RESISTANCE"],
["Land Rover 110 (M2)","CUP_I_LR_MG_AAF","CUP_Vehicles","RESISTANCE"],
["Land Rover 110 (SF HMG)","CUP_I_LR_SF_HMG_AAF","CUP_Vehicles","RESISTANCE"],
["Land Rover 110 (SF GMG)","CUP_I_LR_SF_GMG_AAF","CUP_Vehicles","RESISTANCE"],
["Land Rover 110 (Ambulance)","CUP_I_LR_Ambulance_AAF","CUP_Vehicles","RESISTANCE"],
["Land Rover 110 (Transport)","CUP_I_LR_Transport_RACS","CUP_Vehicles","RESISTANCE"],
["Land Rover 110 (M2)","CUP_I_LR_MG_RACS","CUP_Vehicles","RESISTANCE"],
["Land Rover 110 (Ambulance)","CUP_I_LR_Ambulance_RACS","CUP_Vehicles","RESISTANCE"],
["Land Rover 110 (Transport)","CUP_O_LR_Transport_TKA","CUP_Vehicles","EAST"],
["Land Rover 110 (M2)","CUP_O_LR_MG_TKA","CUP_Vehicles","EAST"],
["Land Rover 110 (Ambulance)","CUP_O_LR_Ambulance_TKA","CUP_Vehicles","EAST"],
["Land Rover 110 (SPG-9)","CUP_O_LR_SPG9_TKA","CUP_Vehicles","EAST"],
["Land Rover 110 (Transport)","CUP_O_LR_Transport_TKM","CUP_Vehicles","EAST"],
["Land Rover 110 (M2)","CUP_O_LR_MG_TKM","CUP_Vehicles","EAST"],
["Land Rover 110 (SPG-9)","CUP_O_LR_SPG9_TKM","CUP_Vehicles","EAST"],
["MTVR","CUP_B_MTVR_USA","CUP_Vehicles","WEST"],
["MTVR (Ammo)","CUP_B_MTVR_Ammo_USA","CUP_Vehicles","WEST"],
["MTVR (Refuel)","CUP_B_MTVR_Refuel_USA","CUP_Vehicles","WEST"],
["MTVR (Repair)","CUP_B_MTVR_Repair_USA","CUP_Vehicles","WEST"],
["MTVR","CUP_B_MTVR_USMC","CUP_Vehicles","WEST"],
["MTVR (Ammo)","CUP_B_MTVR_Ammo_USMC","CUP_Vehicles","WEST"],
["MTVR (Refuel)","CUP_B_MTVR_Refuel_USMC","CUP_Vehicles","WEST"],
["MTVR (Repair)","CUP_B_MTVR_Repair_USMC","CUP_Vehicles","WEST"],
["MTVR","CUP_B_MTVR_HIL","CUP_Vehicles","WEST"],
["MTVR (Ammo)","CUP_B_MTVR_Ammo_HIL","CUP_Vehicles","WEST"],
["MTVR (Refuel)","CUP_B_MTVR_Refuel_HIL","CUP_Vehicles","WEST"],
["MTVR (Repair)","CUP_B_MTVR_Repair_HIL","CUP_Vehicles","WEST"],
["MTVR","CUP_I_MTVR_RACS","CUP_Vehicles","RESISTANCE"],
["MTVR (Ammo)","CUP_I_MTVR_Ammo_RACS","CUP_Vehicles","RESISTANCE"],
["MTVR (Refuel)","CUP_I_MTVR_Refuel_RACS","CUP_Vehicles","RESISTANCE"],
["MTVR (Repair)","CUP_I_MTVR_Repair_RACS","CUP_Vehicles","RESISTANCE"],
["MTVR","CUP_B_MTVR_BAF_DES","CUP_Vehicles","WEST"],
["MTVR (Ammo)","CUP_B_MTVR_Ammo_BAF_DES","CUP_Vehicles","WEST"],
["MTVR (Refuel)","CUP_B_MTVR_Refuel_BAF_DES","CUP_Vehicles","WEST"],
["MTVR (Repair)","CUP_B_MTVR_Repair_BAF_DES","CUP_Vehicles","WEST"],
["MTVR","CUP_B_MTVR_BAF_WOOD","CUP_Vehicles","WEST"],
["MTVR (Ammo)","CUP_B_MTVR_Ammo_BAF_WOOD","CUP_Vehicles","WEST"],
["MTVR (Refuel)","CUP_B_MTVR_Refuel_BAF_WOOD","CUP_Vehicles","WEST"],
["MTVR (Repair)","CUP_B_MTVR_Repair_BAF_WOOD","CUP_Vehicles","WEST"],
["Tractor","CUP_C_Tractor_CIV","CUP_Vehicles","CIVILIAN"],
["Tractor (Old)","CUP_C_Tractor_Old_CIV","CUP_Vehicles","CIVILIAN"],
["Towing Tractor","CUP_B_Tractor_CDF","CUP_Vehicles","WEST"],
["Towing Tractor","CUP_O_Tractor_Old_CHDKZ","CUP_Vehicles","EAST"],
["Towing Tractor","CUP_O_Tractor_SLA","CUP_Vehicles","EAST"],
["Towing Tractor","CUP_O_Tractor_Old_TKA","CUP_Vehicles","EAST"],
["Towing Tractor","CUP_I_Tractor_Old_SYND","CUP_Vehicles","RESISTANCE"],
["Towing Tractor","CUP_I_Tractor_UN","CUP_Vehicles","RESISTANCE"],
["UAZ-469","CUP_B_UAZ_Unarmed_CDF","CUP_Vehicles","WEST"],
["UAZ-469 (Open)","CUP_B_UAZ_Open_CDF","CUP_Vehicles","WEST"],
["UAZ-469 (DShKM)","CUP_B_UAZ_MG_CDF","CUP_Vehicles","WEST"],
["UAZ-469 (AGS-30)","CUP_B_UAZ_AGS30_CDF","CUP_Vehicles","WEST"],
["UAZ-469 (SPG-9)","CUP_B_UAZ_SPG9_CDF","CUP_Vehicles","WEST"],
["UAZ-469 (Metis-M)","CUP_B_UAZ_METIS_CDF","CUP_Vehicles","WEST"],
["UAZ-469","CUP_O_UAZ_Unarmed_CHDKZ","CUP_Vehicles","EAST"],
["UAZ-469 (Open)","CUP_O_UAZ_Open_CHDKZ","CUP_Vehicles","EAST"],
["UAZ-469 (DShKM)","CUP_O_UAZ_MG_CHDKZ","CUP_Vehicles","EAST"],
["UAZ-469 (AGS-30)","CUP_O_UAZ_AGS30_CHDKZ","CUP_Vehicles","EAST"],
["UAZ-469 (SPG-9)","CUP_O_UAZ_SPG9_CHDKZ","CUP_Vehicles","EAST"],
["UAZ-469 (Metis-M)","CUP_O_UAZ_METIS_CHDKZ","CUP_Vehicles","EAST"],
["UAZ-469","CUP_O_UAZ_Unarmed_SLA","CUP_Vehicles","EAST"],
["UAZ-469 (Militia)","CUP_O_UAZ_Militia_SLA","CUP_Vehicles","EAST"],
["UAZ-469 (Open)","CUP_O_UAZ_Open_SLA","CUP_Vehicles","EAST"],
["UAZ-469 (DShKM)","CUP_O_UAZ_MG_SLA","CUP_Vehicles","EAST"],
["UAZ-469 (AGS-30)","CUP_O_UAZ_AGS30_SLA","CUP_Vehicles","EAST"],
["UAZ-469 (SPG-9)","CUP_O_UAZ_SPG9_SLA","CUP_Vehicles","EAST"],
["UAZ-469 (Metis-M)","CUP_O_UAZ_METIS_SLA","CUP_Vehicles","EAST"],
["UAZ-469","CUP_O_UAZ_Unarmed_CSAT","CUP_Vehicles","EAST"],
["UAZ-469 (Open)","CUP_O_UAZ_Open_CSAT","CUP_Vehicles","EAST"],
["UAZ-469 (DShKM)","CUP_O_UAZ_MG_CSAT","CUP_Vehicles","EAST"],
["UAZ-469 (AGS-30)","CUP_O_UAZ_AGS30_CSAT","CUP_Vehicles","EAST"],
["UAZ-469 (SPG-9)","CUP_O_UAZ_SPG9_CSAT","CUP_Vehicles","EAST"],
["UAZ-469 (Metis-M)","CUP_O_UAZ_METIS_CSAT","CUP_Vehicles","EAST"],
["UAZ-469","CUP_O_UAZ_Unarmed_RU","CUP_Vehicles","EAST"],
["UAZ-469 (Open)","CUP_O_UAZ_Open_RU","CUP_Vehicles","EAST"],
["UAZ-469 (DShKM)","CUP_O_UAZ_MG_RU","CUP_Vehicles","EAST"],
["UAZ-469 (AGS-30)","CUP_O_UAZ_AGS30_RU","CUP_Vehicles","EAST"],
["UAZ-469 (SPG-9)","CUP_O_UAZ_SPG9_RU","CUP_Vehicles","EAST"],
["UAZ-469 (Metis-M)","CUP_O_UAZ_METIS_RU","CUP_Vehicles","EAST"],
["UAZ-469 (Medevac)","CUP_O_UAZ_AMB_RU","CUP_Vehicles","EAST"],
["UAZ-469","CUP_O_UAZ_Unarmed_TKA","CUP_Vehicles","EAST"],
["UAZ-469 (Open)","CUP_O_UAZ_Open_TKA","CUP_Vehicles","EAST"],
["UAZ-469 (DShKM)","CUP_O_UAZ_MG_TKA","CUP_Vehicles","EAST"],
["UAZ-469 (AGS-30)","CUP_O_UAZ_AGS30_TKA","CUP_Vehicles","EAST"],
["UAZ-469 (SPG-9)","CUP_O_UAZ_SPG9_TKA","CUP_Vehicles","EAST"],
["UAZ-469 (Metis-M)","CUP_O_UAZ_METIS_TKA","CUP_Vehicles","EAST"],
["UAZ-469","CUP_I_UAZ_Unarmed_UN","CUP_Vehicles","RESISTANCE"],
["UAZ-469 (Open)","CUP_I_UAZ_Open_UN","CUP_Vehicles","RESISTANCE"],
["UAZ-469 (DShKM)","CUP_I_UAZ_MG_UN","CUP_Vehicles","RESISTANCE"],
["UAZ-469 (AGS-30)","CUP_I_UAZ_AGS30_UN","CUP_Vehicles","RESISTANCE"],
["UAZ-469 (SPG-9)","CUP_I_UAZ_SPG9_UN","CUP_Vehicles","RESISTANCE"],
["UAZ-469","CUP_C_UAZ_Unarmed_TK_CIV","CUP_Vehicles","CIVILIAN"],
["UAZ-469 (Open)","CUP_C_UAZ_Open_TK_CIV","CUP_Vehicles","CIVILIAN"],
["UAZ-469","CUP_B_UAZ_Unarmed_ACR","CUP_Vehicles","WEST"],
["UAZ-469 (Open)","CUP_B_UAZ_Open_ACR","CUP_Vehicles","WEST"],
["UAZ-469 (DShKM)","CUP_B_UAZ_MG_ACR","CUP_Vehicles","WEST"],
["UAZ-469 (AGS-30)","CUP_B_UAZ_AGS30_ACR","CUP_Vehicles","WEST"],
["UAZ-469 (SPG-9)","CUP_B_UAZ_SPG9_ACR","CUP_Vehicles","WEST"],
["UAZ-469 (Metis-M)","CUP_B_UAZ_METIS_ACR","CUP_Vehicles","WEST"],
["M1165 GMV (M134)","CUP_B_M1165_GMV_USA","CUP_Vehicles","WEST"],
["M1151 (M2)","CUP_B_M1151_M2_USA","CUP_Vehicles","WEST"],
["M1151 (M2) Deployment","CUP_B_M1151_Deploy_USA","CUP_Vehicles","WEST"],
["M1151 (Mk. 19)","CUP_B_M1151_Mk19_USA","CUP_Vehicles","WEST"],
["M1151 (Unarmed)","CUP_B_M1151_USA","CUP_Vehicles","WEST"],
["M1152 ECV","CUP_B_M1152_USA","CUP_Vehicles","WEST"],
["M1167 (TOW-2)","CUP_B_M1167_USA","CUP_Vehicles","WEST"],
["M1165 GMV (M134)","CUP_B_M1165_GMV_USMC","CUP_Vehicles","WEST"],
["M1151 (M2)","CUP_B_M1151_M2_USMC","CUP_Vehicles","WEST"],
["M1151 (M2) Deployment","CUP_B_M1151_Deploy_USMC","CUP_Vehicles","WEST"],
["M1151 (Mk. 19)","CUP_B_M1151_Mk19_USMC","CUP_Vehicles","WEST"],
["M1151 (Unarmed)","CUP_B_M1151_USMC","CUP_Vehicles","WEST"],
["M1152 ECV","CUP_B_M1152_USMC","CUP_Vehicles","WEST"],
["M1167 (TOW-2)","CUP_B_M1167_USMC","CUP_Vehicles","WEST"],
["M1165 GMV (M134)","CUP_B_M1165_GMV_NATO_T","CUP_Vehicles","WEST"],
["M1151 (M2)","CUP_B_M1151_M2_NATO_T","CUP_Vehicles","WEST"],
["M1151 (M2) Deployment","CUP_B_M1151_Deploy_NATO_T","CUP_Vehicles","WEST"],
["M1151 (Mk. 19)","CUP_B_M1151_Mk19_NATO_T","CUP_Vehicles","WEST"],
["M1151 (Unarmed)","CUP_B_M1151_NATO_T","CUP_Vehicles","WEST"],
["M1152 ECV","CUP_B_M1152_NATO_T","CUP_Vehicles","WEST"],
["M1167 (TOW-2)","CUP_B_M1167_NATO_T","CUP_Vehicles","WEST"],
["Ural","CUP_O_Ural_RU","CUP_Vehicles","EAST"],
["Ural (Open)","CUP_O_Ural_Open_RU","CUP_Vehicles","EAST"],
["Ural (Refuel)","CUP_O_Ural_Refuel_RU","CUP_Vehicles","EAST"],
["Ural (Repair)","CUP_O_Ural_Repair_RU","CUP_Vehicles","EAST"],
["Ural (Ammo)","CUP_O_Ural_Reammo_RU","CUP_Vehicles","EAST"],
["Ural (Empty)","CUP_O_Ural_Empty_RU","CUP_Vehicles","EAST"],
["Ural","CUP_B_Ural_CDF","CUP_Vehicles","WEST"],
["Ural (Open)","CUP_B_Ural_Open_CDF","CUP_Vehicles","WEST"],
["Ural (Refuel)","CUP_B_Ural_Refuel_CDF","CUP_Vehicles","WEST"],
["Ural (Repair)","CUP_B_Ural_Repair_CDF","CUP_Vehicles","WEST"],
["Ural (Ammo)","CUP_B_Ural_Reammo_CDF","CUP_Vehicles","WEST"],
["Ural (Empty)","CUP_B_Ural_Empty_CDF","CUP_Vehicles","WEST"],
["Ural","CUP_O_Ural_CHDKZ","CUP_Vehicles","EAST"],
["Ural (Open)","CUP_O_Ural_Open_CHDKZ","CUP_Vehicles","EAST"],
["Ural (Refuel)","CUP_O_Ural_Refuel_CHDKZ","CUP_Vehicles","EAST"],
["Ural (Repair)","CUP_O_Ural_Repair_CHDKZ","CUP_Vehicles","EAST"],
["Ural (Ammo)","CUP_O_Ural_Reammo_CHDKZ","CUP_Vehicles","EAST"],
["Ural (Empty)","CUP_O_Ural_Empty_CHDKZ","CUP_Vehicles","EAST"],
["Ural","CUP_O_Ural_TKA","CUP_Vehicles","EAST"],
["Ural (Open)","CUP_O_Ural_Open_TKA","CUP_Vehicles","EAST"],
["Ural (Refuel)","CUP_O_Ural_Refuel_TKA","CUP_Vehicles","EAST"],
["Ural (Repair)","CUP_O_Ural_Repair_TKA","CUP_Vehicles","EAST"],
["Ural (Ammo)","CUP_O_Ural_Reammo_TKA","CUP_Vehicles","EAST"],
["Ural (Empty)","CUP_O_Ural_Empty_TKA","CUP_Vehicles","EAST"],
["Ural","CUP_O_Ural_SLA","CUP_Vehicles","EAST"],
["Ural (Open)","CUP_O_Ural_Open_SLA","CUP_Vehicles","EAST"],
["Ural (Refuel)","CUP_O_Ural_Refuel_SLA","CUP_Vehicles","EAST"],
["Ural (Repair)","CUP_O_Ural_Repair_SLA","CUP_Vehicles","EAST"],
["Ural (Ammo)","CUP_O_Ural_Reammo_SLA","CUP_Vehicles","EAST"],
["Ural (Empty)","CUP_O_Ural_Empty_SLA","CUP_Vehicles","EAST"],
["Ural","CUP_I_Ural_UN","CUP_Vehicles","RESISTANCE"],
["Ural (Repair)","CUP_I_Ural_Repair_UN","CUP_Vehicles","RESISTANCE"],
["Ural (Ammo)","CUP_I_Ural_Reammo_UN","CUP_Vehicles","RESISTANCE"],
["Ural (Empty)","CUP_I_Ural_Empty_UN","CUP_Vehicles","RESISTANCE"],
["Ural (Blue)","CUP_C_Ural_Civ_01","CUP_Vehicles","CIVILIAN"],
["Ural (Yellow)","CUP_C_Ural_Civ_02","CUP_Vehicles","CIVILIAN"],
["Ural (Worker)","CUP_C_Ural_Civ_03","CUP_Vehicles","CIVILIAN"],
["Ural (Blue) (Open)","CUP_C_Ural_Open_Civ_01","CUP_Vehicles","CIVILIAN"],
["Ural (Yellow) (Open)","CUP_C_Ural_Open_Civ_02","CUP_Vehicles","CIVILIAN"],
["Ural (Worker) (Open)","CUP_C_Ural_Open_Civ_03","CUP_Vehicles","CIVILIAN"],
["Praga V3S","CUP_O_V3S_Open_TKA","CUP_Vehicles","EAST"],
["Praga V3S (Covered)","CUP_O_V3S_Covered_TKA","CUP_Vehicles","EAST"],
["Praga V3S (Refuel)","CUP_O_V3S_Refuel_TKA","CUP_Vehicles","EAST"],
["Praga V3S (Repair)","CUP_O_V3S_Repair_TKA","CUP_Vehicles","EAST"],
["Praga V3S (Rearm)","CUP_O_V3S_Rearm_TKA","CUP_Vehicles","EAST"],
["Praga V3S","CUP_O_V3S_Open_TKM","CUP_Vehicles","EAST"],
["Praga V3S (Covered)","CUP_O_V3S_Covered_TKM","CUP_Vehicles","EAST"],
["Praga V3S (Refuel)","CUP_O_V3S_Refuel_TKM","CUP_Vehicles","EAST"],
["Praga V3S (Repair)","CUP_O_V3S_Repair_TKM","CUP_Vehicles","EAST"],
["Praga V3S (Rearm)","CUP_O_V3S_Rearm_TKM","CUP_Vehicles","EAST"],
["Praga V3S","CUP_I_V3S_Open_TKG","CUP_Vehicles","RESISTANCE"],
["Praga V3S (Covered)","CUP_I_V3S_Covered_TKG","CUP_Vehicles","RESISTANCE"],
["Praga V3S (Refuel)","CUP_I_V3S_Refuel_TKG","CUP_Vehicles","RESISTANCE"],
["Praga V3S (Repair)","CUP_I_V3S_Repair_TKG","CUP_Vehicles","RESISTANCE"],
["Praga V3S (Rearm)","CUP_I_V3S_Rearm_TKG","CUP_Vehicles","RESISTANCE"],
["Praga V3S","CUP_C_V3S_Open_TKC","CUP_Vehicles","CIVILIAN"],
["Praga V3S (Covered)","CUP_C_V3S_Covered_TKC","CUP_Vehicles","CIVILIAN"],
["Praga V3S","CUP_V3S_Open_NAPA","CUP_Vehicles","RESISTANCE"],
["SUV","CUP_C_SUV_TK","CUP_Vehicles","CIVILIAN"],
["SUV (Blue/White)","CUP_C_SUV_CIV","CUP_Vehicles","CIVILIAN"],
["SUV","CUP_O_SUV_TKA","CUP_Vehicles","EAST"],
["SUV","CUP_I_SUV_UNO","CUP_Vehicles","RESISTANCE"],
["SUV","CUP_I_SUV_ION","CUP_Vehicles","RESISTANCE"],
["Armored SUV","CUP_I_SUV_Armored_ION","CUP_Vehicles","RESISTANCE"]]
