[["Wrack (UH-60)","BlackhawkWreck","CUP_Terrains_-_Core","CIVILIAN"],
["Blackfoot-Wrack","Land_Wreck_Heli_Attack_01_F","CBA_A3","CIVILIAN"],
["Mi-8","Mi8Wreck","CUP_Terrains_-_Core","CIVILIAN"],
["MH-47E","CUP_B_MH47E_USA","CUP_Vehicles","WEST"],
["Chinook HC-6","CUP_B_MH47E_GB","CUP_Vehicles","WEST"],
["M-900","I_C_Heli_Light_01_civil_F","expansion","RESISTANCE"],
["UH-80 Ghost Hawk (Sand)","B_CTRG_Heli_Transport_01_sand_F","expansion","WEST"],
["UH-80 Ghost Hawk (Tropen)","B_CTRG_Heli_Transport_01_tropic_F","expansion","WEST"],
["PAH 1","gm_ge_army_bo105p_pah1","GM","WEST"],
["PAH 1A1","gm_ge_army_bo105p_pah1a1","GM","WEST"],
["VBH 1","gm_ge_army_bo105m_vbh","GM","WEST"],
["VBH 1A1","gm_ge_army_bo105p1m_vbh","GM","WEST"],
["VBH 1A1 Swooper","gm_ge_army_bo105p1m_vbh_swooper","GM","WEST"],
["VBH 1","gm_ge_bgs_bo105m_vbh","GM","WEST"],
["VBH 1","gm_ge_pol_bo105m_vbh","GM","CIVILIAN"],
["CH-53G","gm_ge_army_ch53g","GM","WEST"],
["CH-53GS","gm_ge_army_ch53gs","GM","WEST"],
["Mi-2P","gm_gc_airforce_mi2p","GM","EAST"],
["Mi-2T","gm_gc_airforce_mi2t","GM","EAST"],
["Mi-2SR","gm_gc_airforce_mi2sr","GM","EAST"],
["Mi-2US","gm_gc_airforce_mi2us","GM","EAST"],
["Mi-2URN","gm_gc_airforce_mi2urn","GM","EAST"],
["Mi-2P","gm_gc_bgs_mi2p","GM","EAST"],
["Mi-2US","gm_gc_bgs_mi2us","GM","EAST"],
["Mi-2P","gm_gc_civ_mi2p","GM","CIVILIAN"],
["Mi-2R","gm_gc_civ_mi2r","GM","CIVILIAN"],
["Mi-2SR","gm_gc_civ_mi2sr","GM","CIVILIAN"],
["Mi-2P","gm_pl_airforce_mi2p","GM","EAST"],
["Mi-2T","gm_pl_airforce_mi2t","GM","EAST"],
["Mi-2SR","gm_pl_airforce_mi2sr","GM","EAST"],
["Mi-2US","gm_pl_airforce_mi2us","GM","EAST"],
["Mi-2URN","gm_pl_airforce_mi2urn","GM","EAST"],
["Mi-2URP","gm_pl_airforce_mi2urp","GM","EAST"],
["Mi-2URS","gm_pl_airforce_mi2urs","GM","EAST"],
["Mi-2URP-G","gm_pl_airforce_mi2urpg","GM","EAST"],
["Mi-2Ch","gm_pl_airforce_mi2ch","GM","EAST"],
["Mi-2P Platan","gm_pl_airforce_mi2platan","GM","EAST"],
["Merlin HC3","CUP_B_Merlin_HC3_GB","CUP_Vehicles","WEST"],
["Merlin HC3 (VIV)","CUP_B_Merlin_HC3_VIV_GB","CUP_Vehicles","WEST"],
["Merlin HC3A","CUP_B_Merlin_HC3A_GB","CUP_Vehicles","WEST"],
["Merlin HC3 (Armed)","CUP_B_Merlin_HC3_Armed_GB","CUP_Vehicles","WEST"],
["Merlin HC3A (Armed)","CUP_B_Merlin_HC3A_Armed_GB","CUP_Vehicles","WEST"],
["Merlin HM2","CUP_B_Merlin_HC4_GB","CUP_Vehicles","WEST"],
["Ka-52","CUP_O_Ka52_RU","CUP_Vehicles","EAST"],
["MH-60S Seahawk","CUP_B_MH60S_USMC","CUP_Vehicles","WEST"],
["UH-1Y Venom (Transport)","CUP_B_UH1Y_UNA_USMC","CUP_Vehicles","WEST"],
["UH-1Y Venom (MEDVAC)","CUP_B_UH1Y_MEV_USMC","CUP_Vehicles","WEST"],
["UH-1Y Venom (Gunship)","CUP_B_UH1Y_Gunship_Dynamic_USMC","CUP_Vehicles","WEST"],
["AH-1Z","CUP_B_AH1Z_Dynamic_USMC","CUP_Vehicles","WEST"],
["AH-1Z","CUP_I_AH1Z_Dynamic_AAF","CUP_Vehicles","RESISTANCE"],
["AH-64D","CUP_B_AH64D_DL_USA","CUP_Vehicles","WEST"],
["AH-64","CUP_B_AH64_DL_USA","CUP_Vehicles","WEST"],
["AH1","CUP_B_AH1_DL_BAF","CUP_Vehicles","WEST"],
["MH-6M MELB","CUP_B_MH6M_USA","CUP_Vehicles","WEST"],
["MH-6J Little Bird","CUP_B_MH6J_USA","CUP_Vehicles","WEST"],
["MH-6M Recon","CUP_B_MH6M_OBS_USA","CUP_Vehicles","WEST"],
["MH-6J Recon","CUP_B_MH6J_OBS_USA","CUP_Vehicles","WEST"],
["AH-6M","CUP_B_AH6M_USA","CUP_Vehicles","WEST"],
["AH-6J","CUP_B_AH6J_USA","CUP_Vehicles","WEST"],
["MH-6J Little Bird","CUP_I_MH6J_RACS","CUP_Vehicles","RESISTANCE"],
["AH-6J","CUP_I_AH6J_RACS","CUP_Vehicles","RESISTANCE"],
["MH-6M MELB","CUP_I_MH6M_ION","CUP_Vehicles","RESISTANCE"],
["MH-6M Recon","CUP_I_MH6M_ION_OBS","CUP_Vehicles","RESISTANCE"],
["AW159 Wildcat (Green, Unarmed)","CUP_B_AW159_Unarmed_GB","CUP_Vehicles","WEST"],
["AW159 Wildcat (Grey, Unarmed)","CUP_B_AW159_Unarmed_RN_Grey","CUP_Vehicles","WEST"],
["AW159 Wildcat (Black Cat, Unarmed)","CUP_B_AW159_Unarmed_RN_Blackcat","CUP_Vehicles","WEST"],
["AW159 Wildcat (Green)","CUP_B_AW159_GB","CUP_Vehicles","WEST"],
["AW159 Wildcat (Grey)","CUP_B_AW159_RN_Grey","CUP_Vehicles","WEST"],
["AW159 Wildcat (Black Cat)","CUP_B_AW159_RN_Blackcat","CUP_Vehicles","WEST"],
["AW159 Wildcat (Green, Unarmed)","CUP_I_Wildcat_Unarmed_Green_AAF","CUP_Vehicles","RESISTANCE"],
["AW159 Wildcat (Digital, Unarmed)","CUP_I_Wildcat_Unarmed_Digital_AAF","CUP_Vehicles","RESISTANCE"],
["AW159 Wildcat (Green)","CUP_I_Wildcat_Green_AAF","CUP_Vehicles","RESISTANCE"],
["AW159 Wildcat (Digital)","CUP_I_Wildcat_Digital_AAF","CUP_Vehicles","RESISTANCE"],
["AW159 Wildcat (Unarmed)","CUP_B_AW159_Unarmed_HIL","CUP_Vehicles","WEST"],
["AW159 Wildcat","CUP_B_AW159_HIL","CUP_Vehicles","WEST"],
["CH-47F","CUP_B_CH47F_USA","CUP_Vehicles","WEST"],
["CH-47F (VIV)","CUP_B_CH47F_VIV_USA","CUP_Vehicles","WEST"],
["CH-47F","CUP_B_CH47F_HIL","CUP_Vehicles","WEST"],
["CH-47F (VIV)","CUP_B_CH47F_VIV_HIL","CUP_Vehicles","WEST"],
["Chinook HC-4","CUP_B_CH47F_GB","CUP_Vehicles","WEST"],
["Chinook HC-4 (VIV)","CUP_B_CH47F_VIV_GB","CUP_Vehicles","WEST"],
["CH-47F","CUP_I_CH47F_RACS","CUP_Vehicles","RESISTANCE"],
["CH-47F (VIV)","CUP_I_CH47F_VIV_RACS","CUP_Vehicles","RESISTANCE"],
["CH-53E Super Stallion","CUP_B_CH53E_USMC","CUP_Vehicles","WEST"],
["CH-53E Super Stallion (VIV)","CUP_B_CH53E_VIV_USMC","CUP_Vehicles","WEST"],
["CH-53G Super Stallion","CUP_B_CH53E_GER","CUP_Vehicles","WEST"],
["CH-53G Super Stallion (VIV)","CUP_B_CH53E_VIV_GER","CUP_Vehicles","WEST"],
["Ka-50 Black Shark","CUP_O_Ka50_DL_SLA","CUP_Vehicles","EAST"],
["Ka-50 Black Shark","CUP_O_Ka50_DL_RU","CUP_Vehicles","EAST"],
["Mi-24P","CUP_O_Mi24_P_Dynamic_RU","CUP_Vehicles","EAST"],
["Mi-24V","CUP_O_Mi24_V_Dynamic_RU","CUP_Vehicles","EAST"],
["Mi-24D","CUP_B_Mi24_D_Dynamic_CDF","CUP_Vehicles","WEST"],
["Mi-24D MEV","CUP_B_Mi24_D_MEV_Dynamic_CDF","CUP_Vehicles","WEST"],
["Mi-24D","CUP_O_Mi24_D_Dynamic_CSAT_T","CUP_Vehicles","EAST"],
["Mi-24P","CUP_O_Mi24_P_Dynamic_CSAT_T","CUP_Vehicles","EAST"],
["Mi-24V","CUP_O_Mi24_V_Dynamic_CSAT_T","CUP_Vehicles","EAST"],
["Mi-24D","CUP_O_Mi24_D_Dynamic_TK","CUP_Vehicles","EAST"],
["Mi-24D","CUP_O_Mi24_D_Dynamic_SLA","CUP_Vehicles","EAST"],
["Mi-35","CUP_B_Mi35_Dynamic_CZ","CUP_Vehicles","WEST"],
["Mi-35 (Desert)","CUP_B_Mi35_Dynamic_CZ_Des","CUP_Vehicles","WEST"],
["Mi-35 (Ram)","CUP_B_Mi35_Dynamic_CZ_Ram","CUP_Vehicles","WEST"],
["Mi-35 (Tiger)","CUP_B_Mi35_Dynamic_CZ_Tiger","CUP_Vehicles","WEST"],
["Mi-35 (Dark)","CUP_B_Mi35_Dynamic_CZ_Dark","CUP_Vehicles","WEST"],
["Mi-24D","CUP_I_Mi24_D_Dynamic_UN","CUP_Vehicles","RESISTANCE"],
["Mi-24D","CUP_I_Mi24_D_Dynamic_AAF","CUP_Vehicles","RESISTANCE"],
["Mi-24D","CUP_I_Mi24_D_Dynamic_ION","CUP_Vehicles","RESISTANCE"],
["Mi-24 Superhind Mk.III","CUP_I_Mi24_Mk3_AAF","CUP_Vehicles","RESISTANCE"],
["Mi-24 Superhind Mk.IV (S8)","CUP_I_Mi24_Mk4_AAF","CUP_Vehicles","RESISTANCE"],
["Mi-24 Superhind Mk.III","CUP_O_Mi24_Mk3_CSAT_T","CUP_Vehicles","EAST"],
["Mi-24 Superhind Mk.IV (S8)","CUP_O_Mi24_Mk4_CSAT_T","CUP_Vehicles","EAST"],
["Mi-24 Superhind Mk.III","CUP_I_Mi24_Mk3_ION","CUP_Vehicles","RESISTANCE"],
["Mi-24 Superhind Mk.IV (S8)","CUP_I_Mi24_Mk4_ION","CUP_Vehicles","RESISTANCE"],
["Mi-24 Superhind Mk.III","CUP_I_Mi24_Mk3_UN","CUP_Vehicles","RESISTANCE"],
["Mi-24 Superhind Mk.IV (S8)","CUP_I_Mi24_Mk4_UN","CUP_Vehicles","RESISTANCE"],
["Mi-6A Hook (VIV)","CUP_B_MI6A_CDF","CUP_Vehicles","WEST"],
["Mi-6T Hook","CUP_B_MI6T_CDF","CUP_Vehicles","WEST"],
["Mi-6A Hook (VIV)","CUP_O_MI6A_CHDKZ","CUP_Vehicles","EAST"],
["Mi-6T Hook","CUP_O_MI6T_CHDKZ","CUP_Vehicles","EAST"],
["Mi-6A Hook (VIV)","CUP_O_MI6A_TKA","CUP_Vehicles","EAST"],
["Mi-6T Hook","CUP_O_MI6T_TKA","CUP_Vehicles","EAST"],
["Mi-6T Hook","CUP_O_MI6T_SLA","CUP_Vehicles","EAST"],
["Mi-6A Hook (VIV)","CUP_O_MI6A_SLA","CUP_Vehicles","EAST"],
["Mi-6A Hook (VIV)","CUP_I_MI6A_UN","CUP_Vehicles","RESISTANCE"],
["Mi-6T Hook","CUP_I_MI6T_UN","CUP_Vehicles","RESISTANCE"],
["Mi-6A Hook (VIV)","CUP_O_MI6A_RU","CUP_Vehicles","EAST"],
["Mi-6T Hook","CUP_O_MI6T_RU","CUP_Vehicles","EAST"],
["Mi-6A Hook (VIV)","CUP_O_MI6A_CSAT_T","CUP_Vehicles","EAST"],
["Mi-6T Hook","CUP_O_MI6T_CSAT_T","CUP_Vehicles","EAST"],
["Mi-6A Hook (VIV)","CUP_C_MI6A_RU","CUP_Vehicles","CIVILIAN"],
["Mi-6T Hook","CUP_C_MI6T_RU","CUP_Vehicles","CIVILIAN"],
["Mi-8MT","CUP_O_Mi8_CHDKZ","CUP_Vehicles","EAST"],
["Mi-8MT Medevac","CUP_O_Mi8_medevac_CHDKZ","CUP_Vehicles","EAST"],
["Mi-8MT (VIV)","CUP_O_Mi8_VIV_CHDKZ","CUP_Vehicles","EAST"],
["Mi-8MT","CUP_B_Mi17_CDF","CUP_Vehicles","WEST"],
["Mi-8MT Medevac","CUP_B_Mi17_medevac_CDF","CUP_Vehicles","WEST"],
["Mi-8MT (VIV)","CUP_B_Mi17_VIV_CDF","CUP_Vehicles","WEST"],
["Mi-171Sh (Rockets)","CUP_B_Mi171Sh_CDF","CUP_Vehicles","WEST"],
["Mi-8MT","CUP_I_Mi17_UN","CUP_Vehicles","RESISTANCE"],
["Mi-8MT (VIV)","CUP_I_Mi17_VIV_UN","CUP_Vehicles","RESISTANCE"],
["Mi-8MT","CUP_O_Mi17_TK","CUP_Vehicles","EAST"],
["Mi-8MT (VIV)","CUP_O_Mi17_VIV_TK","CUP_Vehicles","EAST"],
["Mi-8AMT Medevac","CUP_O_Mi8_medevac_RU","CUP_Vehicles","EAST"],
["Mi-8AMT (VIV)","CUP_O_Mi8_VIV_RU","CUP_Vehicles","EAST"],
["Mi-8MTV3","CUP_O_Mi8_RU","CUP_Vehicles","EAST"],
["Mi-8AMT","CUP_O_Mi8AMT_RU","CUP_Vehicles","EAST"],
["Mi-8MT","CUP_C_Mi17_Civilian_RU","CUP_Vehicles","CIVILIAN"],
["Mi-8MT (VIV)","CUP_C_Mi17_VIV_RU","CUP_Vehicles","CIVILIAN"],
["Mi-171Sh (Rockets)","CUP_B_Mi171Sh_ACR","CUP_Vehicles","WEST"],
["Mi-171Sh","CUP_B_Mi171Sh_Unarmed_ACR","CUP_Vehicles","WEST"],
["Mi-8MT","CUP_O_Mi8_SLA_1","CUP_Vehicles","EAST"],
["Mi-8MTV3","CUP_O_Mi8_SLA_2","CUP_Vehicles","EAST"],
["Mi-8AMT (VIV)","CUP_O_Mi8_VIV_SLA","CUP_Vehicles","EAST"],
["SA-330 Puma HC1","CUP_B_SA330_Puma_HC1_BAF","CUP_Vehicles","WEST"],
["SA-330 Puma HC2","CUP_B_SA330_Puma_HC2_BAF","CUP_Vehicles","WEST"],
["SA-330 Puma HC1","CUP_I_SA330_Puma_HC1_RACS","CUP_Vehicles","RESISTANCE"],
["IAR-330 (ChernAvia)","CUP_C_SA330_Puma_HC1_ChernAvia","CUP_Vehicles","CIVILIAN"],
["SA-330 Puma HC2","CUP_I_SA330_Puma_HC2_RACS","CUP_Vehicles","RESISTANCE"],
["UH-1H","CUP_O_UH1H_TKA","CUP_Vehicles","EAST"],
["UH-1H (Slick)","CUP_O_UH1H_slick_TKA","CUP_Vehicles","EAST"],
["UH-1H (Armed)","CUP_O_UH1H_armed_TKA","CUP_Vehicles","EAST"],
["UH-1H (Gunship)","CUP_O_UH1H_gunship_TKA","CUP_Vehicles","EAST"],
["UH-1H","CUP_O_UH1H_SLA","CUP_Vehicles","EAST"],
["UH-1H (Slick)","CUP_O_UH1H_slick_SLA","CUP_Vehicles","EAST"],
["UH-1H (Armed)","CUP_O_UH1H_armed_SLA","CUP_Vehicles","EAST"],
["UH-1H (Gunship)","CUP_O_UH1H_gunship_SLA","CUP_Vehicles","EAST"],
["UH-1H","CUP_I_UH1H_TK_GUE","CUP_Vehicles","RESISTANCE"],
["UH-1H (Slick)","CUP_I_UH1H_slick_TK_GUE","CUP_Vehicles","RESISTANCE"],
["UH-1H (Armed)","CUP_I_UH1H_armed_TK_GUE","CUP_Vehicles","RESISTANCE"],
["UH-1H (Gunship)","CUP_I_UH1H_gunship_TK_GUE","CUP_Vehicles","RESISTANCE"],
["UH-1D","CUP_B_UH1D_GER_KSK","CUP_Vehicles","WEST"],
["UH-1D (Slick)","CUP_B_UH1D_slick_GER_KSK","CUP_Vehicles","WEST"],
["UH-1D (Armed)","CUP_B_UH1D_armed_GER_KSK","CUP_Vehicles","WEST"],
["UH-1D (Gunship)","CUP_B_UH1D_gunship_GER_KSK","CUP_Vehicles","WEST"],
["UH-1D (Desert)","CUP_B_UH1D_GER_KSK_Des","CUP_Vehicles","WEST"],
["UH-1D (Slick/Desert)","CUP_B_UH1D_slick_GER_KSK_Des","CUP_Vehicles","WEST"],
["UH-1D (Armed/Desert)","CUP_B_UH1D_armed_GER_KSK_Des","CUP_Vehicles","WEST"],
["UH-1D (Gunship/Desert)","CUP_B_UH1D_gunship_GER_KSK_Des","CUP_Vehicles","WEST"],
["UH-1H","CUP_I_UH1H_RACS","CUP_Vehicles","RESISTANCE"],
["UH-1H (Slick)","CUP_I_UH1H_Slick_RACS","CUP_Vehicles","RESISTANCE"],
["UH-1H (Armed)","CUP_I_UH1H_Armed_RACS","CUP_Vehicles","RESISTANCE"],
["UH-1H (Gunship)","CUP_I_UH1H_gunship_RACS","CUP_Vehicles","RESISTANCE"],
["UH-60M","CUP_B_UH60M_US","CUP_Vehicles","WEST"],
["MH-60L DAP (4 Stores)","CUP_B_MH60L_DAP_4x_US","CUP_Vehicles","WEST"],
["MH-60L DAP (2 Stores)","CUP_B_MH60L_DAP_2x_US","CUP_Vehicles","WEST"],
["UH-60M (FFV)","CUP_B_UH60M_FFV_US","CUP_Vehicles","WEST"],
["UH-60M (Unarmed)","CUP_B_UH60M_Unarmed_US","CUP_Vehicles","WEST"],
["UH-60M (Unarmed/FFV)","CUP_B_UH60M_Unarmed_FFV_US","CUP_Vehicles","WEST"],
["UH-60M MEDVAC (Unarmed/FFV)","CUP_B_UH60M_Unarmed_FFV_MEV_US","CUP_Vehicles","WEST"],
["MH-60S Knighthawk (ESSS x4)","CUP_B_MH60L_DAP_4x_USN","CUP_Vehicles","WEST"],
["MH-60S Knighthawk (ESSS x2)","CUP_B_MH60L_DAP_2x_USN","CUP_Vehicles","WEST"],
["MH-60S Seahawk (M3M)","CUP_B_UH60S_USN","CUP_Vehicles","WEST"],
["MH-60S Seahawk (Unarmed)","CUP_MH60S_Unarmed_USN","CUP_Vehicles","WEST"],
["MH-60S Seahawk (Unarmed/FFV)","CUP_MH60S_Unarmed_FFV_USN","CUP_Vehicles","WEST"],
["UH-60L","CUP_I_UH60L_RACS","CUP_Vehicles","RESISTANCE"],
["UH-60L (FFV)","CUP_I_UH60L_FFV_RACS","CUP_Vehicles","RESISTANCE"],
["UH-60L (Unarmed)","CUP_I_UH60L_Unarmed_RACS","CUP_Vehicles","RESISTANCE"],
["UH-60L (Unarmed/FFV)","CUP_I_UH60L_Unarmed_FFV_Racs","CUP_Vehicles","RESISTANCE"],
["UH-60L MEDVAC (Unarmed/FFV)","CUP_I_UH60L_Unarmed_FFV_MEV_Racs","CUP_Vehicles","RESISTANCE"],
["Ka-60 Kasatka Black (Rockets - M32)","CUP_I_Ka60_GL_Blk_ION","CUP_Vehicles","RESISTANCE"],
["Ka-60 Kasatka Black (Rockets)","CUP_I_Ka60_Blk_ION","CUP_Vehicles","RESISTANCE"],
["Ka-60 Kasatka Digital (Rockets - M32)","CUP_I_Ka60_GL_Digi_AAF","CUP_Vehicles","RESISTANCE"],
["Ka-60 Kasatka Digital (Rockets)","CUP_I_Ka60_Digi_AAF","CUP_Vehicles","RESISTANCE"],
["Ka-60 Kasatka Hex (Rockets - M32)","CUP_O_Ka60_GL_Hex_CSAT","CUP_Vehicles","EAST"],
["Ka-60 Kasatka Hex (Rockets)","CUP_O_Ka60_Hex_CSAT","CUP_Vehicles","EAST"],
["Ka-60 Kasatka Black (Rockets - M32)","CUP_O_Ka60_GL_Blk_CSAT","CUP_Vehicles","EAST"],
["Ka-60 Kasatka Black (Rockets)","CUP_O_Ka60_Blk_CSAT","CUP_Vehicles","EAST"],
["Ka-60 Kasatka Whale (Rockets - M32)","CUP_O_Ka60_GL_Whale_CSAT","CUP_Vehicles","EAST"],
["Ka-60 Kasatka Whale (Rockets)","CUP_O_Ka60_Whale_CSAT","CUP_Vehicles","EAST"],
["Ka-60 Kasatka Grey (Rockets)","CUP_O_Ka60_Grey_RU","CUP_Vehicles","EAST"]]
