[["UBF Saif","O_T_UGV_01_ghex_F","expansion","EAST"],
["UBF Saif RCWS","O_T_UGV_01_rcws_ghex_F","expansion","EAST"],
["UGV Stomper","B_T_UGV_01_olive_F","expansion","WEST"],
["UGV Stomper RCWS","B_T_UGV_01_rcws_olive_F","expansion","WEST"],
["MQ-12 Falcon","B_T_UAV_03_dynamicLoadout_F","expansion","WEST"],
["KH-3A Fenghuang","O_T_UAV_04_CAS_F","expansion","EAST"],
["MQ-9 Reaper","CUP_B_USMC_DYN_MQ9","CUP_Vehicles","WEST"],
["Pchela-1T","CUP_O_Pchela1T_RU","CUP_Vehicles","EAST"],
["Pchela-1T","CUP_B_Pchela1T_CDF","CUP_Vehicles","WEST"],
["Seafox (USV)","CUP_B_Seafox_USV_USMC","CUP_Vehicles","WEST"],
["AH-6X Littlebird ULB","CUP_B_AH6X_USA","CUP_Vehicles","WEST"]]
