[["Wrack (M113)","M113Wreck","CUP_Terrains_-_Core","CIVILIAN"],
["BMP-2","BMP2Wreck","CUP_Terrains_-_Core","CIVILIAN"],
["BRDM-2","BRDMWreck","CUP_Terrains_-_Core","CIVILIAN"],
["CRV-6e Bobcat","B_T_APC_Tracked_01_CRV_F","expansion","WEST"],
["IFV-6c Panther","B_T_APC_Tracked_01_rcws_F","expansion","WEST"],
["BTR-K Kamysh","O_T_APC_Tracked_02_cannon_ghex_F","expansion","EAST"],
["AMV-7 Marshall","B_T_APC_Wheeled_01_cannon_F","expansion","WEST"],
["MSE-3 Marid","O_T_APC_Wheeled_02_rcws_v2_ghex_F","expansion","EAST"],
["BMP-1 SP-2","gm_gc_army_bmp1sp2","GM","EAST"],
["BWP-1","gm_pl_army_bmp1sp2","GM","EAST"],
["M113A1DK MTW","gm_dk_army_m113a1dk_apc","GM","WEST"],
["M113A1DK PzPiGrp","gm_dk_army_m113a1dk_engineer","GM","WEST"],
["M113A1DK FÃ¼FuPz","gm_dk_army_m113a1dk_command","GM","WEST"],
["M113A1DK KrKw","gm_dk_army_m113a1dk_medic","GM","WEST"],
["M113A1G MTW","gm_ge_army_m113a1g_apc","GM","WEST"],
["M113A1G MTW LPALR","gm_ge_army_m113a1g_apc_milan","GM","WEST"],
["M113A1G FÃ¼FuPz","gm_ge_army_m113a1g_command","GM","WEST"],
["M113A1G KrKw","gm_ge_army_m113a1g_medic","GM","WEST"],
["M113A2DK PNMK","gm_dk_army_m113a2dk","GM","WEST"],
["SPW-40P2","gm_gc_army_brdm2","GM","EAST"],
["SPW-40P2UM","gm_gc_army_brdm2um","GM","EAST"],
["BRDM2","gm_pl_army_brdm2","GM","EAST"],
["SPW-60PA","gm_gc_army_btr60pa","GM","EAST"],
["SPW-60PB","gm_gc_army_btr60pb","GM","EAST"],
["SPW-60PU-12","gm_gc_army_btr60pu12","GM","EAST"],
["TPz 1A0 PzAufklGrp","gm_ge_army_fuchsa0_reconnaissance","GM","WEST"],
["TPz 1A0 PzPiGrp","gm_ge_army_fuchsa0_engineer","GM","WEST"],
["TPz 1A0 FÃ¼Fu","gm_ge_army_fuchsa0_command","GM","WEST"],
["SpPz 2A1","gm_ge_army_luchsa1","GM","WEST"],
["SpPz 2A2","gm_ge_army_luchsa2","GM","WEST"],
["SKOT-2A","gm_pl_army_ot64a","GM","EAST"],
["MT-LB LV","CUP_O_MTLB_pk_TKA","CUP_Vehicles","EAST"],
["MT-LB LV","CUP_O_MTLB_pk_TK_MILITIA","CUP_Vehicles","EAST"],
["MT-LB LV","CUP_O_MTLB_pk_ChDKZ","CUP_Vehicles","EAST"],
["MT-LB LV","CUP_O_MTLB_pk_SLA","CUP_Vehicles","EAST"],
["MT-LB LV (Green)","CUP_O_MTLB_pk_Green_RU","CUP_Vehicles","EAST"],
["MT-LB LV (Camo)","CUP_O_MTLB_pk_WDL_RU","CUP_Vehicles","EAST"],
["MT-LB LV (Winter)","CUP_O_MTLB_pk_Winter_RU","CUP_Vehicles","EAST"],
["MT-LB LV","CUP_B_MTLB_pk_CDF","CUP_Vehicles","WEST"],
["MT-LB LV (Winter)","CUP_B_MTLB_pk_Winter_CDF","CUP_Vehicles","WEST"],
["MT-LB LV","CUP_B_MTLB_pk_FIA","CUP_Vehicles","WEST"],
["MT-LB LV","CUP_I_MTLB_pk_SYNDIKAT","CUP_Vehicles","RESISTANCE"],
["MT-LB LV","CUP_I_MTLB_pk_UN","CUP_Vehicles","RESISTANCE"],
["MT-LB LV","CUP_I_MTLB_pk_NAPA","CUP_Vehicles","RESISTANCE"],
["FV510 Warrior (SLAT - Desert)","CUP_B_FV510_GB_D_SLAT","CUP_Vehicles","WEST"],
["FV510 Warrior (SLAT - Woodland)","CUP_B_FV510_GB_W_SLAT","CUP_Vehicles","WEST"],
["FV510 Warrior (Desert)","CUP_B_FV510_GB_D","CUP_Vehicles","WEST"],
["FV510 Warrior (Woodland)","CUP_B_FV510_GB_W","CUP_Vehicles","WEST"],
["MCV-80 Warrior (SLAT - Desert)","CUP_B_MCV80_GB_D_SLAT","CUP_Vehicles","WEST"],
["MCV-80 Warrior (SLAT - Woodland)","CUP_B_MCV80_GB_W_SLAT","CUP_Vehicles","WEST"],
["MCV-80 Warrior (Desert)","CUP_B_MCV80_GB_D","CUP_Vehicles","WEST"],
["MCV-80 Warrior (Woodland)","CUP_B_MCV80_GB_W","CUP_Vehicles","WEST"],
["GTK Boxer (Woodland, Empty)","CUP_B_Boxer_Empty_GER_WDL","CUP_Vehicles","WEST"],
["GTK Boxer (Desert, Empty)","CUP_B_Boxer_Empty_GER_DES","CUP_Vehicles","WEST"],
["GTK Boxer (Woodland, HMG)","CUP_B_Boxer_HMG_GER_WDL","CUP_Vehicles","WEST"],
["GTK Boxer (Desert, HMG)","CUP_B_Boxer_HMG_GER_DES","CUP_Vehicles","WEST"],
["GTK Boxer (Woodland, GMG)","CUP_B_Boxer_GMG_GER_WDL","CUP_Vehicles","WEST"],
["GTK Boxer (Desert, GMG)","CUP_B_Boxer_GMG_GER_DES","CUP_Vehicles","WEST"],
["GTK Boxer (Empty)","CUP_B_Boxer_Empty_HIL","CUP_Vehicles","WEST"],
["GTK Boxer (HMG)","CUP_B_Boxer_HMG_HIL","CUP_Vehicles","WEST"],
["GTK Boxer (GMG)","CUP_B_Boxer_GMG_HIL","CUP_Vehicles","WEST"],
["LAV-25A1","CUP_B_LAV25_USMC","CUP_Vehicles","WEST"],
["LAV-25A1 (Desert)","CUP_B_LAV25_desert_USMC","CUP_Vehicles","WEST"],
["LAV-25A1 (Olive)","CUP_B_LAV25_green","CUP_Vehicles","WEST"],
["LAV-25A1 (M240)","CUP_B_LAV25M240_USMC","CUP_Vehicles","WEST"],
["LAV-25A1 (M240) (Desert)","CUP_B_LAV25M240_desert_USMC","CUP_Vehicles","WEST"],
["LAV-25A1 (M240) (Olive)","CUP_B_LAV25M240_green","CUP_Vehicles","WEST"],
["LAV-C2","CUP_B_LAV25_HQ_USMC","CUP_Vehicles","WEST"],
["LAV-C2 (Desert)","CUP_B_LAV25_HQ_desert_USMC","CUP_Vehicles","WEST"],
["LAV-C2 (Olive)","CUP_B_LAV25_HQ_green","CUP_Vehicles","WEST"],
["LAV-25A1","CUP_I_LAV25_RACS","CUP_Vehicles","RESISTANCE"],
["LAV-25A1 (M240)","CUP_I_LAV25M240_RACS","CUP_Vehicles","RESISTANCE"],
["LAV-C2","CUP_I_LAV25_HQ_RACS","CUP_Vehicles","RESISTANCE"],
["GAZ-3937 Vodnik (2x PKM)","CUP_O_GAZ_Vodnik_PK_RU","CUP_Vehicles","EAST"],
["GAZ-3937 Vodnik (BPPU)","CUP_O_GAZ_Vodnik_BPPU_RU","CUP_Vehicles","EAST"],
["GAZ-3937 Vodnik (Medical)","CUP_O_GAZ_Vodnik_MedEvac_RU","CUP_Vehicles","EAST"],
["GAZ-3937 Vodnik (AGS-30/PKM)","CUP_O_GAZ_Vodnik_AGS_RU","CUP_Vehicles","EAST"],
["GAZ-3937 Vodnik (KPVT)","CUP_O_GAZ_Vodnik_KPVT_RU","CUP_Vehicles","EAST"],
["GAZ-3937 Vodnik","CUP_O_GAZ_Vodnik_Unarmed_RU","CUP_Vehicles","EAST"],
["AAVP7/A1","CUP_B_AAV_USMC","CUP_Vehicles","WEST"],
["AAVC7/A1 (Command)","CUP_B_AAV_Unarmed_USMC","CUP_Vehicles","WEST"],
["AAVP7/A1","CUP_I_AAV_RACS","CUP_Vehicles","RESISTANCE"],
["AAVC7/A1 (Command)","CUP_I_AAV_Unarmed_RACS","CUP_Vehicles","RESISTANCE"],
["BMP-3","CUP_O_BMP3_RU","CUP_Vehicles","EAST"],
["BMP-3","CUP_O_BMP3_CSAT_T","CUP_Vehicles","EAST"],
["BMP-1","CUP_O_BMP1_TKA","CUP_Vehicles","EAST"],
["BMP-1P","CUP_O_BMP1P_TKA","CUP_Vehicles","EAST"],
["BMP-2","CUP_O_BMP2_TKA","CUP_Vehicles","EAST"],
["BMP-2K","CUP_O_BMP_HQ_TKA","CUP_Vehicles","EAST"],
["BMP-2 Ambulance","CUP_O_BMP2_AMB_TKA","CUP_Vehicles","EAST"],
["BMP-2 ZU-23","CUP_O_BMP2_ZU_TKA","CUP_Vehicles","EAST"],
["BMP-1","CUP_I_BMP1_TK_GUE","CUP_Vehicles","RESISTANCE"],
["BMP-2","CUP_B_BMP2_CDF","CUP_Vehicles","WEST"],
["BMP-2K","CUP_B_BMP_HQ_CDF","CUP_Vehicles","WEST"],
["BMP-2 Ambulance","CUP_B_BMP2_AMB_CDF","CUP_Vehicles","WEST"],
["BMP-2","CUP_O_BMP2_RU","CUP_Vehicles","EAST"],
["BMP-2K","CUP_O_BMP_HQ_RU","CUP_Vehicles","EAST"],
["BMP-2 Ambulance","CUP_O_BMP2_AMB_RU","CUP_Vehicles","EAST"],
["BMP-2","CUP_O_BMP2_CHDKZ","CUP_Vehicles","EAST"],
["BMP-2K","CUP_O_BMP_HQ_CHDKZ","CUP_Vehicles","EAST"],
["BMP-2 Ambulance","CUP_O_BMP2_AMB_CHDKZ","CUP_Vehicles","EAST"],
["BMP-2","CUP_I_BMP2_UN","CUP_Vehicles","RESISTANCE"],
["BMP-2K","CUP_I_BMP_HQ_UN","CUP_Vehicles","RESISTANCE"],
["BMP-2 Ambulance","CUP_I_BMP2_AMB_UN","CUP_Vehicles","RESISTANCE"],
["BMP-2","CUP_O_BMP2_SLA","CUP_Vehicles","EAST"],
["BMP-2K","CUP_O_BMP_HQ_sla","CUP_Vehicles","EAST"],
["BMP-2 Ambulance","CUP_O_BMP2_AMB_sla","CUP_Vehicles","EAST"],
["BMP-1","CUP_O_BMP1_CSAT","CUP_Vehicles","EAST"],
["BMP-1P","CUP_O_BMP1P_CSAT","CUP_Vehicles","EAST"],
["BMP-2","CUP_O_BMP2_CSAT","CUP_Vehicles","EAST"],
["BMP-2K","CUP_O_BMP_HQ_CSAT","CUP_Vehicles","EAST"],
["BMP-2 Ambulance","CUP_O_BMP2_AMB_CSAT","CUP_Vehicles","EAST"],
["BMP-2 ZU-23","CUP_O_BMP2_ZU_CSAT","CUP_Vehicles","EAST"],
["BMP-1","CUP_O_BMP1_CSAT_T","CUP_Vehicles","EAST"],
["BMP-1P","CUP_O_BMP1P_CSAT_T","CUP_Vehicles","EAST"],
["BMP-2","CUP_O_BMP2_CSAT_T","CUP_Vehicles","EAST"],
["BMP-2K","CUP_O_BMP_HQ_CSAT_T","CUP_Vehicles","EAST"],
["BMP-2 Ambulance","CUP_O_BMP2_AMB_CSAT_T","CUP_Vehicles","EAST"],
["BMP-2 ZU-23","CUP_O_BMP2_ZU_CSAT_T","CUP_Vehicles","EAST"],
["BMP-2","CUP_I_BMP2_NAPA","CUP_Vehicles","RESISTANCE"],
["BMP-2K","CUP_I_BMP_HQ_NAPA","CUP_Vehicles","RESISTANCE"],
["BMP-2 Ambulance","CUP_I_BMP2_AMB_NAPA","CUP_Vehicles","RESISTANCE"],
["BVP-2","CUP_B_BMP2_CZ","CUP_Vehicles","WEST"],
["BVP-2","CUP_B_BMP2_CZ_Des","CUP_Vehicles","WEST"],
["BVP-2 (HQ)","CUP_B_BMP_HQ_CZ","CUP_Vehicles","WEST"],
["BVP-2 (HQ)","CUP_B_BMP_HQ_CZ_Des","CUP_Vehicles","WEST"],
["BVP-2 Ambulance","CUP_B_BMP2_AMB_CZ","CUP_Vehicles","WEST"],
["BVP-2 Ambulance","CUP_B_BMP2_AMB_CZ_Des","CUP_Vehicles","WEST"],
["M2A2 Bradley IFV (Desert)","CUP_B_M2Bradley_USA_D","CUP_Vehicles","WEST"],
["M2A2 Bradley IFV (Woodland)","CUP_B_M2Bradley_USA_W","CUP_Vehicles","WEST"],
["M2A3 ERA Bradley IFV (Desert)","CUP_B_M2A3Bradley_USA_D","CUP_Vehicles","WEST"],
["M2A3 ERA Bradley IFV (Woodland)","CUP_B_M2A3Bradley_USA_W","CUP_Vehicles","WEST"],
["M7 Bradley (Desert)","CUP_B_M7Bradley_USA_D","CUP_Vehicles","WEST"],
["M7 Bradley (Woodland)","CUP_B_M7Bradley_USA_W","CUP_Vehicles","WEST"],
["M2A2 Bradley IFV","CUP_B_M2Bradley_NATO_T","CUP_Vehicles","WEST"],
["M2A3 ERA Bradley IFV","CUP_B_M2A3Bradley_NATO_T","CUP_Vehicles","WEST"],
["M113","CUP_B_M113_USA","CUP_Vehicles","WEST"],
["M113A3 (Desert)","CUP_B_M113_desert_USA","CUP_Vehicles","WEST"],
["M113A3 Ambulance","CUP_B_M113_Med_USA","CUP_Vehicles","WEST"],
["M113","CUP_I_M113_AAF","CUP_Vehicles","RESISTANCE"],
["M113A3 Ambulance","CUP_I_M113_Med_AAF","CUP_Vehicles","RESISTANCE"],
["M113A3 Super-Gavin","CUP_I_M113_RACS","CUP_Vehicles","RESISTANCE"],
["M113A3 Super-Gavin (Urban)","CUP_I_M113_RACS_URB","CUP_Vehicles","RESISTANCE"],
["M113A3 Medi-Gavin","CUP_I_M113_Med_RACS","CUP_Vehicles","RESISTANCE"],
["M113","CUP_I_M113_UN","CUP_Vehicles","RESISTANCE"],
["M113A3 Ambulance","CUP_I_M113_Med_UN","CUP_Vehicles","RESISTANCE"],
["M113","CUP_O_M113_TKA","CUP_Vehicles","EAST"],
["M113A3 Ambulance","CUP_O_M113_Med_TKA","CUP_Vehicles","EAST"],
["BRDM-2","CUP_B_BRDM2_CDF","CUP_Vehicles","WEST"],
["BRDM-2 (ATGM)","CUP_B_BRDM2_ATGM_CDF","CUP_Vehicles","WEST"],
["BRDM-2 (HQ)","CUP_B_BRDM2_HQ_CDF","CUP_Vehicles","WEST"],
["BRDM-2","CUP_O_BRDM2_CHDKZ","CUP_Vehicles","EAST"],
["BRDM-2 (ATGM)","CUP_O_BRDM2_ATGM_CHDKZ","CUP_Vehicles","EAST"],
["BRDM-2 (HQ)","CUP_O_BRDM2_HQ_CHDKZ","CUP_Vehicles","EAST"],
["BRDM-2","CUP_I_BRDM2_NAPA","CUP_Vehicles","RESISTANCE"],
["BRDM-2 (ATGM)","CUP_I_BRDM2_ATGM_NAPA","CUP_Vehicles","RESISTANCE"],
["BRDM-2 (HQ)","CUP_I_BRDM2_HQ_NAPA","CUP_Vehicles","RESISTANCE"],
["BRDM-2","CUP_O_BRDM2_SLA","CUP_Vehicles","EAST"],
["BRDM-2 (ATGM)","CUP_O_BRDM2_ATGM_SLA","CUP_Vehicles","EAST"],
["BRDM-2 (HQ)","CUP_O_BRDM2_HQ_SLA","CUP_Vehicles","EAST"],
["BRDM-2","CUP_O_BRDM2_CSAT","CUP_Vehicles","EAST"],
["BRDM-2 (ATGM)","CUP_O_BRDM2_ATGM_CSAT","CUP_Vehicles","EAST"],
["BRDM-2 (HQ)","CUP_O_BRDM2_HQ_CSAT","CUP_Vehicles","EAST"],
["BRDM-2","CUP_O_BRDM2_CSAT_T","CUP_Vehicles","EAST"],
["BRDM-2 (ATGM)","CUP_O_BRDM2_ATGM_CSAT_T","CUP_Vehicles","EAST"],
["BRDM-2 (HQ)","CUP_O_BRDM2_HQ_CSAT_T","CUP_Vehicles","EAST"],
["BRDM-2","CUP_O_BRDM2_RUS","CUP_Vehicles","EAST"],
["BRDM-2 (ATGM)","CUP_O_BRDM2_ATGM_RUS","CUP_Vehicles","EAST"],
["BRDM-2 (HQ)","CUP_O_BRDM2_HQ_RUS","CUP_Vehicles","EAST"],
["BRDM-2","CUP_O_BRDM2_TKA","CUP_Vehicles","EAST"],
["BRDM-2 (ATGM)","CUP_O_BRDM2_ATGM_TKA","CUP_Vehicles","EAST"],
["BRDM-2 (HQ)","CUP_O_BRDM2_HQ_TKA","CUP_Vehicles","EAST"],
["BRDM-2","CUP_I_BRDM2_TK_Gue","CUP_Vehicles","RESISTANCE"],
["BRDM-2 (ATGM)","CUP_I_BRDM2_ATGM_TK_Gue","CUP_Vehicles","RESISTANCE"],
["BRDM-2 (HQ)","CUP_I_BRDM2_HQ_TK_Gue","CUP_Vehicles","RESISTANCE"],
["BRDM-2","CUP_I_BRDM2_UN","CUP_Vehicles","RESISTANCE"],
["BRDM-2 (HQ)","CUP_I_BRDM2_HQ_UN","CUP_Vehicles","RESISTANCE"],
["BRDM-2","CUP_B_BRDM2_CZ","CUP_Vehicles","WEST"],
["BRDM-2 (desert)","CUP_B_BRDM2_CZ_Des","CUP_Vehicles","WEST"],
["BRDM-2 (HQ)","CUP_B_BRDM2_HQ_CZ","CUP_Vehicles","WEST"],
["BRDM-2 (HQ)(desert)","CUP_B_BRDM2_HQ_CZ_Des","CUP_Vehicles","WEST"],
["BTR-40 (DSHKM)","CUP_I_BTR40_MG_TKG","CUP_Vehicles","RESISTANCE"],
["BTR-40 (Unarmed)","CUP_I_BTR40_TKG","CUP_Vehicles","RESISTANCE"],
["BTR-40 (DSHKM)","CUP_O_BTR40_MG_TKM","CUP_Vehicles","EAST"],
["BTR-40 (Unarmed)","CUP_O_BTR40_TKM","CUP_Vehicles","EAST"],
["BTR-40 (DSHKM)","CUP_O_BTR40_MG_TKA","CUP_Vehicles","EAST"],
["BTR-40 (Unarmed)","CUP_O_BTR40_TKA","CUP_Vehicles","EAST"],
["BTR-60PB","CUP_B_BTR60_CDF","CUP_Vehicles","WEST"],
["BTR-60PB","CUP_I_BTR60_UN","CUP_Vehicles","RESISTANCE"],
["BTR-60PB","CUP_O_BTR60_TK","CUP_Vehicles","EAST"],
["BTR-60PB","CUP_O_BTR60_SLA","CUP_Vehicles","EAST"],
["BTR-60PB","CUP_O_BTR60_CSAT","CUP_Vehicles","EAST"],
["BTR-60PB (Woodland)","CUP_O_BTR60_RU","CUP_Vehicles","EAST"],
["BTR-60PB (Green)","CUP_O_BTR60_Green_RU","CUP_Vehicles","EAST"],
["BTR-60PB (Winter)","CUP_O_BTR60_Winter_RU","CUP_Vehicles","EAST"],
["BTR-60PB","CUP_O_BTR60_CHDKZ","CUP_Vehicles","EAST"],
["BTR-60PB","CUP_B_BTR60_FIA","CUP_Vehicles","WEST"],
["BTR-80A","CUP_B_BTR80A_CDF","CUP_Vehicles","WEST"],
["BTR-80A","CUP_B_BTR80A_FIA","CUP_Vehicles","WEST"],
["BTR-80A (Green)","CUP_O_BTR80A_GREEN_RU","CUP_Vehicles","EAST"],
["BTR-80A (Camo)","CUP_O_BTR80A_CAMO_RU","CUP_Vehicles","EAST"],
["BTR-80A (Winter)","CUP_O_BTR80A_WINTER_RU","CUP_Vehicles","EAST"],
["BTR-80A (Desert)","CUP_O_BTR80A_DESERT_RU","CUP_Vehicles","EAST"],
["BTR-80A","CUP_O_BTR80A_CHDKZ","CUP_Vehicles","EAST"],
["BTR-80A","CUP_O_BTR80A_CSAT","CUP_Vehicles","EAST"],
["BTR-80A","CUP_O_BTR80A_CSAT_T","CUP_Vehicles","EAST"],
["BTR-80A","CUP_O_BTR80A_SLA","CUP_Vehicles","EAST"],
["BTR-80A","CUP_O_BTR80A_TK","CUP_Vehicles","EAST"],
["BTR-80A","CUP_I_BTR80A_ION","CUP_Vehicles","RESISTANCE"],
["BTR-80A","CUP_I_BTR80A_UN","CUP_Vehicles","RESISTANCE"],
["BTR-80","CUP_B_BTR80_CDF","CUP_Vehicles","WEST"],
["BTR-80","CUP_B_BTR80_FIA","CUP_Vehicles","WEST"],
["BTR-80 (Green)","CUP_O_BTR80_GREEN_RU","CUP_Vehicles","EAST"],
["BTR-80 (Camo)","CUP_O_BTR80_CAMO_RU","CUP_Vehicles","EAST"],
["BTR-80 (Winter)","CUP_O_BTR80_WINTER_RU","CUP_Vehicles","EAST"],
["BTR-80 (Desert)","CUP_O_BTR80_DESERT_RU","CUP_Vehicles","EAST"],
["BTR-80","CUP_O_BTR80_CHDKZ","CUP_Vehicles","EAST"],
["BTR-80","CUP_O_BTR80_CSAT","CUP_Vehicles","EAST"],
["BTR-80","CUP_O_BTR80_CSAT_T","CUP_Vehicles","EAST"],
["BTR-80","CUP_O_BTR80_SLA","CUP_Vehicles","EAST"],
["BTR-80","CUP_O_BTR80_TK","CUP_Vehicles","EAST"],
["BTR-80","CUP_I_BTR80_ION","CUP_Vehicles","RESISTANCE"],
["BTR-80","CUP_I_BTR80_UN","CUP_Vehicles","RESISTANCE"],
["BTR-90","CUP_O_BTR90_RU","CUP_Vehicles","EAST"],
["BTR-90 (HQ)","CUP_O_BTR90_HQ_RU","CUP_Vehicles","EAST"],
["M1126 ICV M2 CROWS (Desert)","CUP_B_M1126_ICV_M2_Desert","CUP_Vehicles","WEST"],
["M1126 ICV M2 CROWS (Woodland)","CUP_B_M1126_ICV_M2_Woodland","CUP_Vehicles","WEST"],
["M1126 ICV MK19 CROWS (Desert)","CUP_B_M1126_ICV_MK19_Desert","CUP_Vehicles","WEST"],
["M1126 ICV MK19 CROWS (Woodland)","CUP_B_M1126_ICV_MK19_Woodland","CUP_Vehicles","WEST"],
["M1130 CV M2 CROWS (Desert)","CUP_B_M1130_CV_M2_Desert","CUP_Vehicles","WEST"],
["M1130 CV M2 CROWS (Woodland)","CUP_B_M1130_CV_M2_Woodland","CUP_Vehicles","WEST"],
["M1135 ATGMV (Desert)","CUP_B_M1135_ATGMV_Desert","CUP_Vehicles","WEST"],
["M1135 ATGMV (Woodland)","CUP_B_M1135_ATGMV_Woodland","CUP_Vehicles","WEST"],
["M1128 MGS (Desert)","CUP_B_M1128_MGS_Desert","CUP_Vehicles","WEST"],
["M1128 MGS (Woodland)","CUP_B_M1128_MGS_Woodland","CUP_Vehicles","WEST"],
["M1133 MEV (Desert)","CUP_B_M1133_MEV_Desert","CUP_Vehicles","WEST"],
["M1133 MEV (Woodland)","CUP_B_M1133_MEV_Woodland","CUP_Vehicles","WEST"],
["FV432 Bulldog L7A2 [Desert]","CUP_B_FV432_Bulldog_GB_D","CUP_Vehicles","WEST"],
["FV432 Bulldog L7A2 [Woodland]","CUP_B_FV432_Bulldog_GB_W","CUP_Vehicles","WEST"],
["FV432 Bulldog L111A1 RWS [Desert]","CUP_B_FV432_Bulldog_GB_D_RWS","CUP_Vehicles","WEST"],
["FV432 Bulldog L111A1 RWS [Woodland]","CUP_B_FV432_Bulldog_GB_W_RWS","CUP_Vehicles","WEST"],
["FV432 GPMG","CUP_B_FV432_GB_GPMG","CUP_Vehicles","WEST"],
["FV432 Ambulance","CUP_B_FV432_GB_Ambulance","CUP_Vehicles","WEST"],
["FV432 Mortar","CUP_B_FV432_Mortar","CUP_Vehicles","WEST"]]
