[["RPG-7","Weapon_launch_RPG7_F","expansion","CIVILIAN"],
["Titan MPRL (Tropen)","Weapon_launch_B_Titan_tna_F","expansion","CIVILIAN"],
["Titan MPRL Compact (Tropen)","Weapon_launch_B_Titan_short_tna_F","expansion","CIVILIAN"],
["Titan MPRL (GrÃ¼ne Sechsecke)","Weapon_launch_O_Titan_ghex_F","expansion","CIVILIAN"],
["Titan MPRL Compact (GrÃ¼ne Sechsecke)","Weapon_launch_O_Titan_short_ghex_F","expansion","CIVILIAN"],
["RPG-42 Alamut (GrÃ¼ne Sechsecke)","Weapon_launch_RPG32_ghex_F","expansion","CIVILIAN"],
["PzF84","gm_placeableweapon_pzf84_oli","GM","CIVILIAN"],
["PzF84 (WÃ¼ste)","gm_placeableweapon_pzf84_des","GM","CIVILIAN"],
["PzF84 (Winter)","gm_placeableweapon_pzf84_win","GM","CIVILIAN"],
["FIM-43","gm_placeableweapon_fim43_oli","GM","CIVILIAN"],
["PzF44-2","gm_placeableweapon_pzf44_2_oli","GM","CIVILIAN"],
["PzF44-2 (WÃ¼ste)","gm_placeableweapon_pzf44_2_des","GM","CIVILIAN"],
["PzF44-2 (Winter)","gm_placeableweapon_pzf44_2_win","GM","CIVILIAN"],
["RPG-7 (Dunkellila)","gm_placeableweapon_rpg7_prp","GM","CIVILIAN"],
["RPG-7","gm_placeableweapon_rpg7_wud","GM","CIVILIAN"],
["Strela-2M","gm_placeableweapon_9k32m_oli","GM","CIVILIAN"],
["Boden","CUP_Weapons_Launchers_Base","CUP_Weapons","CIVILIAN"],
["M32","CUP_Weapon_glaunch_M32","CUP_Weapons","CIVILIAN"],
["M79","CUP_Weapon_glaunch_M79","CUP_Weapons","CIVILIAN"],
["Mk13 EGLM","CUP_Weapon_glaunch_Mk13","CUP_Weapons","CIVILIAN"],
["6G30","CUP_Weapon_glaunch_6G30","CUP_Weapons","CIVILIAN"],
["Igla 9K38","CUP_Weapon_launch_Igla","CUP_Weapons","CIVILIAN"],
["FGM-148 Javelin","CUP_Weapon_launch_Javelin","CUP_Weapons","CIVILIAN"],
["M47 Dragon","CUP_Weapon_launch_M47","CUP_Weapons","CIVILIAN"],
["M136 AT-4 launcher","CUP_Weapon_launch_M136","CUP_Weapons","CIVILIAN"],
["M72A6","CUP_Weapon_launch_M72A6","CUP_Weapons","CIVILIAN"],
["M72A6 (Special)","CUP_Weapon_launch_M72A6_Special","CUP_Weapons","CIVILIAN"],
["M3 MAAWS","CUP_Weapon_launch_MAAWS","CUP_Weapons","CIVILIAN"],
["M3 MAAWS with Scope","CUP_Weapon_launch_MAAWS_Scope","CUP_Weapons","CIVILIAN"],
["Metis Launcher","CUP_Weapon_launch_Metis","CUP_Weapons","CIVILIAN"],
["NLAW","CUP_Weapon_launch_NLAW","CUP_Weapons","CIVILIAN"],
["RPG-7V","CUP_Weapon_launch_RPG7V","CUP_Weapons","CIVILIAN"],
["RPG-7V PGO7V","CUP_Weapon_launch_RPG7V_PGO7V","CUP_Weapons","CIVILIAN"],
["RPG-7V PGO7V2","CUP_Weapon_launch_RPG7V_PGO7V2","CUP_Weapons","CIVILIAN"],
["RPG-7V PGO7V3","CUP_Weapon_launch_RPG7V_PGO7V3","CUP_Weapons","CIVILIAN"],
["RPG-7V NSPU","CUP_Weapon_launch_RPG7V_NSPU","CUP_Weapons","CIVILIAN"],
["RPG 18","CUP_Weapon_launch_RPG18","CUP_Weapons","CIVILIAN"],
["Mk153 Mod 0 SMAW","CUP_Weapon_launch_Mk153Mod0","CUP_Weapons","CIVILIAN"],
["Mk153 Mod 0 SMAW with Optics","CUP_Weapon_launch_Mk153Mod0_SMAWOptics","CUP_Weapons","CIVILIAN"],
["FIM-92 Stinger","CUP_Weapon_launch_FIM92Stinger","CUP_Weapons","CIVILIAN"],
["Strela-2 9K32","CUP_Weapon_launch_9K32Strela","CUP_Weapons","CIVILIAN"]]
