[["Protector 9 mm","Weapon_SMG_05_F","expansion","CIVILIAN"],
["MP2A1 9x19 mm","gm_placeableweapon_mp2a1_blk","GM","CIVILIAN"],
["SG5A2 9x19 mm","gm_placeableweapon_mp5a2_blk","GM","CIVILIAN"],
["SG5A3 9x19 mm","gm_placeableweapon_mp5a3_blk","GM","CIVILIAN"],
["SG5SD2 9x19 mm","gm_placeableweapon_mp5sd2_blk","GM","CIVILIAN"],
["SG5SD3 9x19 mm","gm_placeableweapon_mp5sd3_blk","GM","CIVILIAN"],
["PM-63 9x18 mm","gm_placeableweapon_pm63_blk","GM","CIVILIAN"],
["Boden","CUP_Weapons_SubMachineGuns_Base","CUP_Weapons","CIVILIAN"],
["PP-19 Bizon","CUP_Weapon_smg_bizon","CUP_Weapons","CIVILIAN"],
["PP-19 Bizon with Silencer","CUP_Weapon_smg_bizon_snds","CUP_Weapons","CIVILIAN"],
["Scorpion EVO","CUP_Weapon_smg_EVO","CUP_Weapons","CIVILIAN"],
["Scorpion EVO with MRAD, Flashlight","CUP_Weapon_smg_EVO_MRad_Flashlight","CUP_Weapons","CIVILIAN"],
["Scorpion EVO with MRAD, Flashlight, Silencer","CUP_Weapon_smg_EVO_MRad_Flashlight_Snds","CUP_Weapons","CIVILIAN"],
["MP5 SD6","CUP_Weapon_smg_MP5SD6","CUP_Weapons","CIVILIAN"],
["MP5A5","CUP_Weapon_smg_MP5A5","CUP_Weapons","CIVILIAN"],
["SA61","CUP_Weapon_smg_SA61","CUP_Weapons","CIVILIAN"]]
