[["M4 Scorcher","B_T_MBT_01_arty_F","expansion","WEST"],
["M5 Sandstorm MLRS","B_T_MBT_01_mlrs_F","expansion","WEST"],
["2S9 Sochor","O_T_MBT_02_arty_ghex_F","expansion","EAST"],
["M1129 MC MK19 CROWS (Desert)","CUP_B_M1129_MC_MK19_Desert","CUP_Vehicles","WEST"],
["M1129 MC MK19 CROWS (Woodland)","CUP_B_M1129_MC_MK19_Woodland","CUP_Vehicles","WEST"],
["BM-21","CUP_O_BM21_RU","CUP_Vehicles","EAST"],
["BM-21","CUP_B_BM21_CDF","CUP_Vehicles","WEST"],
["BM-21","CUP_O_BM21_CHDKZ","CUP_Vehicles","EAST"],
["BM-21","CUP_O_BM21_TKA","CUP_Vehicles","EAST"],
["BM-21","CUP_O_BM21_SLA","CUP_Vehicles","EAST"],
["M270 MLRS (HE)","CUP_B_M270_HE_USMC","CUP_Vehicles","WEST"],
["M270 MLRS (DPICM)","CUP_B_M270_DPICM_USMC","CUP_Vehicles","WEST"],
["M270 MLRS (HE)","CUP_B_M270_HE_USA","CUP_Vehicles","WEST"],
["M270 MLRS (DPICM)","CUP_B_M270_DPICM_USA","CUP_Vehicles","WEST"],
["M270 MLRS (HE)","CUP_I_M270_HE_AAF","CUP_Vehicles","RESISTANCE"],
["M270 MLRS (DPICM)","CUP_I_M270_DPICM_AAF","CUP_Vehicles","RESISTANCE"],
["M270 MLRS (HE)","CUP_B_M270_HE_HIL","CUP_Vehicles","WEST"],
["M270 MLRS (DPICM)","CUP_B_M270_DPICM_HIL","CUP_Vehicles","WEST"],
["M270 MLRS (HE)","CUP_B_M270_HE_BAF_WOOD","CUP_Vehicles","WEST"],
["M270 MLRS (DPICM)","CUP_B_M270_DPICM_BAF_WOOD","CUP_Vehicles","WEST"],
["M270 MLRS (HE)","CUP_B_M270_HE_BAF_DES","CUP_Vehicles","WEST"],
["M270 MLRS (DPICM)","CUP_B_M270_DPICM_BAF_DES","CUP_Vehicles","WEST"],
["M270 MLRS (HE)","CUP_I_M270_HE_RACS","CUP_Vehicles","RESISTANCE"],
["M270 MLRS (DPICM)","CUP_I_M270_DPICM_RACS","CUP_Vehicles","RESISTANCE"],
["RM-70","CUP_B_RM70_CZ","CUP_Vehicles","WEST"]]
