[["P07 9 mm (Khaki)","Weapon_hgun_P07_khk_F","expansion","CIVILIAN"],
["P07 9Â mm (schwarz)","Weapon_hgun_P07_blk_F","expansion","CIVILIAN"],
["PM 9 mm","Weapon_hgun_Pistol_01_F","expansion","CIVILIAN"],
["LP1 26,5 mm","gm_placeableweapon_lp1_blk","GM","CIVILIAN"],
["P1 9x19 mm","gm_placeableweapon_p1_blk","GM","CIVILIAN"],
["P2A1 26,5 mm","gm_placeableweapon_p2a1_blk","GM","CIVILIAN"],
["wz. 78 26,5 mm","gm_placeableweapon_wz78_blk","GM","CIVILIAN"],
["P2A1 Experiment","gm_placeableweapon_p2a1_launcher_blk","GM","CIVILIAN"],
["PM 9x18 mm","gm_placeableweapon_pm_blk","GM","CIVILIAN"],
["Boden","CUP_Weapons_Pistols_Base","CUP_Weapons","CIVILIAN"],
["M1911","CUP_Weapon_hgun_Colt1911","CUP_Weapons","CIVILIAN"],
["M1911 with Silencer","CUP_Weapon_hgun_Colt1911_snds","CUP_Weapons","CIVILIAN"],
["CZ 75 P-07 Compact","CUP_Weapon_hgun_Compact","CUP_Weapons","CIVILIAN"],
["CZ 75 P-07 Duty","CUP_Weapon_hgun_Duty","CUP_Weapons","CIVILIAN"],
["CZ 75 P-07 Duty with M3X","CUP_Weapon_hgun_Duty_M3X","CUP_Weapons","CIVILIAN"],
["Glock 17","CUP_Weapon_hgun_Glock17","CUP_Weapons","CIVILIAN"],
["Glock 17 with Flashlight","CUP_Weapon_hgun_Glock17_flashlight","CUP_Weapons","CIVILIAN"],
["Glock 17 with Flashlight, Silencer","CUP_Weapon_hgun_Glock17_flashlight_snds","CUP_Weapons","CIVILIAN"],
["Glock 17 with Silencer","CUP_Weapon_hgun_Glock17_snds","CUP_Weapons","CIVILIAN"],
["M9","CUP_Weapon_hgun_M9","CUP_Weapons","CIVILIAN"],
["M9 with Silencer","CUP_Weapon_hgun_M9_snds","CUP_Weapons","CIVILIAN"],
["Makarov","CUP_Weapon_hgun_Makarov","CUP_Weapons","CIVILIAN"],
["Micro UZI PDW","CUP_Weapon_hgun_MicroUzi","CUP_Weapons","CIVILIAN"],
["Micro UZI PDW with Silencer","CUP_Weapon_hgun_MicroUzi_snds","CUP_Weapons","CIVILIAN"],
["PB 6P9","CUP_Weapon_hgun_PB6P9","CUP_Weapons","CIVILIAN"],
["PB 6P9 with Silencer","CUP_Weapon_hgun_PB6P9_snds","CUP_Weapons","CIVILIAN"],
["CZ 75 SP-01 Phantom","CUP_Weapon_hgun_Phantom","CUP_Weapons","CIVILIAN"],
["CZ 75 SP-01 Phantom with Flashlight","CUP_Weapon_hgun_Phantom_Flashlight","CUP_Weapons","CIVILIAN"],
["CZ 75 SP-01 Phantom with Flashlight, Silencer","CUP_Weapon_hgun_Phantom_Flashlight_snds","CUP_Weapons","CIVILIAN"],
["Taurus Tracker Model 455","CUP_Weapon_hgun_TaurusTracker455","CUP_Weapons","CIVILIAN"],
["Taurus Tracker Model 455 Gold","CUP_Weapon_hgun_TaurusTracker455_gold","CUP_Weapons","CIVILIAN"],
["SA-61","CUP_Weapon_hgun_SA61","CUP_Weapons","CIVILIAN"],
["Ballistic Shield with M9","CUP_Weapon_hgun_hgun_BallisticShield_Armed","CUP_Weapons","CIVILIAN"]]
