[["T-72","T72Wreck","CUP_Terrains_-_Core","CIVILIAN"],
["T-72 (GeschÃ¼tzturm)","T72WreckTurret","CUP_Terrains_-_Core","CIVILIAN"],
["M2A1 Slammer","B_T_MBT_01_cannon_F","expansion","WEST"],
["M2A4 Slammer UP","B_T_MBT_01_TUSK_F","expansion","WEST"],
["T-100 Varsuk","O_T_MBT_02_cannon_ghex_F","expansion","EAST"],
["KPz 1A3","gm_dk_army_Leopard1a3","GM","WEST"],
["KPz 1A1","gm_ge_army_Leopard1a1","GM","WEST"],
["KPz 1A1A1","gm_ge_army_Leopard1a1a1","GM","WEST"],
["KPz 1A1A2","gm_ge_army_Leopard1a1a2","GM","WEST"],
["KPz 1A3","gm_ge_army_Leopard1a3","GM","WEST"],
["KPz 1A3A1","gm_ge_army_Leopard1a3a1","GM","WEST"],
["KPz 1A5","gm_ge_army_Leopard1a5","GM","WEST"],
["PT-76B","gm_gc_army_pt76b","GM","EAST"],
["PT-76B","gm_pl_army_pt76b","GM","EAST"],
["T-55","gm_gc_army_t55","GM","EAST"],
["T-55A","gm_gc_army_t55a","GM","EAST"],
["T-55AK","gm_gc_army_t55ak","GM","EAST"],
["T-55AM2","gm_gc_army_t55am2","GM","EAST"],
["T-55AM2B","gm_gc_army_t55am2b","GM","EAST"],
["T-55","gm_pl_army_t55","GM","EAST"],
["T-55A","gm_pl_army_t55a","GM","EAST"],
["T-55AD1","gm_pl_army_t55ak","GM","EAST"],
["BPz 2A0","gm_dk_army_bpz2a0","GM","WEST"],
["BPz 2A0","gm_ge_army_bpz2a0","GM","WEST"],
["Leopard 2A6 (Woodland)","CUP_B_Leopard2A6_GER","CUP_Vehicles","WEST"],
["Leopard 2A6 (Desert)","CUP_B_Leopard2A6DST_GER","CUP_Vehicles","WEST"],
["Leopard 2A6","CUP_B_Leopard2A6_HIL","CUP_Vehicles","WEST"],
["T-90A","CUP_O_T90_RU","CUP_Vehicles","EAST"],
["FV4034 Challenger 2 (Woodland)","CUP_B_Challenger2_Woodland_BAF","CUP_Vehicles","WEST"],
["FV4034 Challenger 2 (Two Color Woodland)","CUP_B_Challenger2_2CW_BAF","CUP_Vehicles","WEST"],
["FV4034 Challenger 2 (Desert)","CUP_B_Challenger2_Desert_BAF","CUP_Vehicles","WEST"],
["FV4034 Challenger 2 (Two-Color Desert)","CUP_B_Challenger2_2CD_BAF","CUP_Vehicles","WEST"],
["FV4034 Challenger 2 (Snow)","CUP_B_Challenger2_Snow_BAF","CUP_Vehicles","WEST"],
["FV4034 Challenger 2 (Two Color Snow)","CUP_B_Challenger2_2CS_BAF","CUP_Vehicles","WEST"],
["FV4034 Challenger 2 (Green)","CUP_B_Challenger2_Green_CTRG","CUP_Vehicles","WEST"],
["FV4034 Challenger 2 (Green)","CUP_B_Challenger2_Sand_CTRG","CUP_Vehicles","WEST"],
["FV4034 Challenger 2","CUP_B_Challenger2_NATO","CUP_Vehicles","WEST"],
["M1A1 Abrams (Woodland)","CUP_B_M1A1_Woodland_US_Army","CUP_Vehicles","WEST"],
["M1A1 Abrams (Desert)","CUP_B_M1A1_DES_US_Army","CUP_Vehicles","WEST"],
["M1A2 Abrams TUSK (Woodland)","CUP_B_M1A2_TUSK_MG_US_Army","CUP_Vehicles","WEST"],
["M1A2 Abrams TUSK (Desert)","CUP_B_M1A2_TUSK_MG_DES_US_Army","CUP_Vehicles","WEST"],
["M1A1 Abrams (Woodland)","CUP_B_M1A1_Woodland_USMC","CUP_Vehicles","WEST"],
["M1A1 Abrams (Desert)","CUP_B_M1A1_DES_USMC","CUP_Vehicles","WEST"],
["M1A2 Abrams TUSK (Woodland)","CUP_B_M1A2_TUSK_MG_USMC","CUP_Vehicles","WEST"],
["M1A2 Abrams TUSK (Desert)","CUP_B_M1A2_TUSK_MG_DES_USMC","CUP_Vehicles","WEST"],
["M1A1 Abrams","CUP_B_M1A1_NATO_T","CUP_Vehicles","WEST"],
["M1A2 Abrams TUSK","CUP_B_M1A_TUSK_NATO_T","CUP_Vehicles","WEST"],
["M60A3","CUP_B_M60A3_USMC","CUP_Vehicles","WEST"],
["M60A3 TTS","CUP_B_M60A3_TTS_USMC","CUP_Vehicles","WEST"],
["M60A3","CUP_I_M60A3_RACS","CUP_Vehicles","RESISTANCE"],
["M60A3 TTS","CUP_I_M60A3_TTS_RACS","CUP_Vehicles","RESISTANCE"],
["T-72","CUP_B_T72_CDF","CUP_Vehicles","WEST"],
["T-72M4CZ","CUP_B_T72_CZ","CUP_Vehicles","WEST"],
["T-72","CUP_I_T72_RACS","CUP_Vehicles","RESISTANCE"],
["T-72","CUP_I_T72_NAPA","CUP_Vehicles","RESISTANCE"],
["T-72","CUP_O_T72_SLA","CUP_Vehicles","EAST"],
["T-72","CUP_O_T72_CSAT","CUP_Vehicles","EAST"],
["T-72","CUP_O_T72_CSAT_T","CUP_Vehicles","EAST"],
["T-72","CUP_O_T72_TKA","CUP_Vehicles","EAST"],
["T-72","CUP_O_T72_RU","CUP_Vehicles","EAST"],
["T-72","CUP_O_T72_CHDKZ","CUP_Vehicles","EAST"],
["T-34-85M","CUP_I_T34_NAPA","CUP_Vehicles","RESISTANCE"],
["T-34-85M","CUP_O_T34_TKA","CUP_Vehicles","EAST"],
["T-34-85M","CUP_I_T34_TK_GUE","CUP_Vehicles","RESISTANCE"],
["T-55","CUP_O_T55_TK","CUP_Vehicles","EAST"],
["T-55","CUP_I_T55_TK_GUE","CUP_Vehicles","RESISTANCE"],
["T-55","CUP_I_T55_NAPA","CUP_Vehicles","RESISTANCE"],
["T-55","CUP_O_T55_CHDKZ","CUP_Vehicles","EAST"],
["T-55","CUP_O_T55_SLA","CUP_Vehicles","EAST"],
["T-55","CUP_O_T55_CSAT","CUP_Vehicles","EAST"],
["T-55","CUP_O_T55_CSAT_T","CUP_Vehicles","EAST"]]
