[["C-130J-Wrack","C130J_wreck_EP1","CUP_Terrains_-_Core","CIVILIAN"],
["C130J Wreck (Ruins)","Land_Wreck_C130J_EP1_ruins","CUP_Terrains_-_Core","CIVILIAN"],
["C-130J statisch","C130J_static_EP1","CUP_Terrains_-_Core","CIVILIAN"],
["C-130 Wreck","cwa_C130Wreck","CUP_Terrains_-_CWA","CIVILIAN"],
["Flugzeugwrack TrÃ¼mmer 1","Land_HistoricalPlaneDebris_01_F","expansion","CIVILIAN"],
["Flugzeugwrack TrÃ¼mmer 2","Land_HistoricalPlaneDebris_02_F","expansion","CIVILIAN"],
["Flugzeugwrack TrÃ¼mmer 3","Land_HistoricalPlaneDebris_03_F","expansion","CIVILIAN"],
["Flugzeugwrack TrÃ¼mmer 4","Land_HistoricalPlaneDebris_04_F","expansion","CIVILIAN"],
["Flugzeugwrack (A6M)","Land_HistoricalPlaneWreck_01_F","expansion","CIVILIAN"],
["Flugzeugwrack (G4M, Bug)","Land_HistoricalPlaneWreck_02_front_F","expansion","CIVILIAN"],
["Flugzeugwrack (G4M, Heck)","Land_HistoricalPlaneWreck_02_rear_F","expansion","CIVILIAN"],
["Flugzeugwrack (G4M, linke TragflÃ¤che)","Land_HistoricalPlaneWreck_02_wing_left_F","expansion","CIVILIAN"],
["Flugzeugwrack (G4M, rechte TragflÃ¤che)","Land_HistoricalPlaneWreck_02_wing_right_F","expansion","CIVILIAN"],
["Flugzeugwrack (B-25)","Land_HistoricalPlaneWreck_03_F","expansion","CIVILIAN"],
["Caesar BTT","C_Plane_Civil_01_F","expansion","CIVILIAN"],
["Caesar BTT (Rennen)","C_Plane_Civil_01_racing_F","expansion","CIVILIAN"],
["Caesar BTT","I_C_Plane_Civil_01_F","expansion","RESISTANCE"],
["V-44 X Blackfish (Infanterie-UnterstÃ¼tzung)","B_T_VTOL_01_infantry_F","expansion","WEST"],
["V-44 X Blackfish (Fahrzeug-Transporter)","B_T_VTOL_01_vehicle_F","expansion","WEST"],
["V-44 X Blackfish (Bewaffnet)","B_T_VTOL_01_armed_F","expansion","WEST"],
["Y-32 Xi'an (Infanterie-Transporter)","O_T_VTOL_02_infantry_dynamicLoadout_F","expansion","EAST"],
["Y-32 Xi'an (Fahrzeug-Transporter)","O_T_VTOL_02_vehicle_dynamicLoadout_F","expansion","EAST"],
["Do 28 D2","gm_ge_airforce_do28d2","GM","WEST"],
["Do 28 D2 (Medevac)","gm_ge_airforce_do28d2_medevac","GM","WEST"],
["L-410T","gm_gc_airforce_l410t","GM","EAST"],
["L-410S","gm_gc_airforce_l410s_salon","GM","EAST"],
["L-410S","gm_gc_civ_l410s_passenger","GM","CIVILIAN"],
["L-410S Salon","gm_gc_civ_l410s_salon","GM","CIVILIAN"],
["F-35B Lightning II","CUP_B_F35B_USMC","CUP_Vehicles","WEST"],
["F-35B Lightning II (Stealth)","CUP_B_F35B_Stealth_USMC","CUP_Vehicles","WEST"],
["F-35B Lightning II","CUP_B_F35B_BAF","CUP_Vehicles","WEST"],
["F-35B Lightning II (Stealth)","CUP_B_F35B_Stealth_BAF","CUP_Vehicles","WEST"],
["Motor Plane","CUP_I_Plane_ION","CUP_Vehicles","RESISTANCE"],
["Caesar BTT (Orbit Airlines)","CUP_C_Plane_Orbit","CUP_Vehicles","CIVILIAN"],
["A-10A Thunderbolt II","CUP_B_A10_DYN_USA","CUP_Vehicles","WEST"],
["Antonov An-2 (AeroSchrot)","CUP_C_AN2_AEROSCHROT_TK_CIV","CUP_Vehicles","CIVILIAN"],
["Antonov An-2 (AeroSchrot)","CUP_C_AN2_CIV","CUP_Vehicles","CIVILIAN"],
["Antonov An-2 (AirTak)","CUP_C_AN2_AIRTAK_TK_CIV","CUP_Vehicles","CIVILIAN"],
["Antonov An-2","CUP_O_AN2_TK","CUP_Vehicles","EAST"],
["AV-8B Harrier II","CUP_B_AV8B_DYN_USMC","CUP_Vehicles","WEST"],
["AV-8B Harrier II","CUP_I_AV8B_DYN_AAF","CUP_Vehicles","RESISTANCE"],
["Harrier GR.9","CUP_B_GR9_DYN_GB","CUP_Vehicles","WEST"],
["C-130J","CUP_B_C130J_USMC","CUP_Vehicles","WEST"],
["C-130J (VIV)","CUP_B_C130J_Cargo_USMC","CUP_Vehicles","WEST"],
["C-130J","CUP_B_C130J_GB","CUP_Vehicles","WEST"],
["C-130J (VIV)","CUP_B_C130J_Cargo_GB","CUP_Vehicles","WEST"],
["C-130J","CUP_I_C130J_AAF","CUP_Vehicles","RESISTANCE"],
["C-130J (VIV)","CUP_I_C130J_Cargo_AAF","CUP_Vehicles","RESISTANCE"],
["C-130J","CUP_I_C130J_RACS","CUP_Vehicles","RESISTANCE"],
["C-130J (VIV)","CUP_I_C130J_Cargo_RACS","CUP_Vehicles","RESISTANCE"],
["C-130J","CUP_O_C130J_TKA","CUP_Vehicles","EAST"],
["C-130J (VIV)","CUP_O_C130J_Cargo_TKA","CUP_Vehicles","EAST"],
["DC-3","CUP_C_DC3_CIV","CUP_Vehicles","CIVILIAN"],
["DC-3 (TanoAir)","CUP_C_DC3_TanoAir_CIV","CUP_Vehicles","CIVILIAN"],
["Li-2 (Chernavia)","CUP_C_DC3_ChernAvia_CIV","CUP_Vehicles","CIVILIAN"],
["C-47 Skytrain","CUP_C_C47_CIV","CUP_Vehicles","CIVILIAN"],
["Li-2","CUP_O_C47_SLA","CUP_Vehicles","EAST"],
["C-47 Skytrain","CUP_B_C47_USA","CUP_Vehicles","WEST"],
["AC-47D Spooky","CUP_B_AC47_Spooky_USA","CUP_Vehicles","WEST"],
["L-39ZA","CUP_I_L39_AAF","CUP_Vehicles","RESISTANCE"],
["L-39ZA","CUP_O_L39_TK","CUP_Vehicles","EAST"],
["L-39ZA (Green)","CUP_B_L39_CZ","CUP_Vehicles","WEST"],
["L-39ZA (Grey)","CUP_B_L39_CZ_GREY","CUP_Vehicles","WEST"],
["MV-22B Osprey","CUP_B_MV22_USMC","CUP_Vehicles","WEST"],
["MV-22B Osprey (VIV)","CUP_B_MV22_VIV_USMC","CUP_Vehicles","WEST"],
["MV-22B Osprey (Ramp Gun)","CUP_B_MV22_USMC_RAMPGUN","CUP_Vehicles","WEST"],
["Su-25 Frogfoot","CUP_B_Su25_Dyn_CDF","CUP_Vehicles","WEST"],
["Su-25 Frogfoot","CUP_O_Su25_Dyn_TKA","CUP_Vehicles","EAST"],
["Su-25 Frogfoot","CUP_O_Su25_Dyn_SLA","CUP_Vehicles","EAST"],
["Su-25 Frogfoot","CUP_O_Su25_Dyn_CSAT_T","CUP_Vehicles","EAST"],
["Su-25T Frogfoot","CUP_O_Su25_Dyn_RU","CUP_Vehicles","EAST"],
["Su-34","CUP_O_SU34_CSAT","CUP_Vehicles","EAST"],
["Su-34","CUP_O_SU34_RU","CUP_Vehicles","EAST"],
["Su-34","CUP_O_SU34_SLA","CUP_Vehicles","EAST"],
["Su-34","CUP_I_SU34_AAF","CUP_Vehicles","RESISTANCE"],
["Su-34","CUP_B_SU34_CDF","CUP_Vehicles","WEST"],
["A-149 Gryphon","CUP_B_JAS39_HIL","CUP_Vehicles","WEST"],
["A-149 Gryphon","CUP_I_JAS39_RACS","CUP_Vehicles","RESISTANCE"]]
