[["MX SW 6,5 mm (Khaki)","Weapon_arifle_MX_SW_khk_F","expansion","CIVILIAN"],
["LIM-85 5,56 mm","Weapon_LMG_03_F","expansion","CIVILIAN"],
["MG3 7,62x51 mm","gm_placeableweapon_mg3_blk","GM","CIVILIAN"],
["MG3 7,62x51 mm (WÃ¼ste)","gm_placeableweapon_mg3_des","GM","CIVILIAN"],
["LMG M/62 7.62x51 mm","gm_placeableweapon_lmgm62_blk","GM","CIVILIAN"],
["sMG PKM 7,62x54 mmR","gm_placeableweapon_hmgpkm_prp","GM","CIVILIAN"],
["Boden","CUP_Weapons_MachineGuns_Base","CUP_Weapons","CIVILIAN"],
["L110A1","CUP_Weapon_lmg_L110A1","CUP_Weapons","CIVILIAN"],
["L110A1 with AIM, Laser","CUP_Weapon_lmg_L110A1_Aim_Laser","CUP_Weapons","CIVILIAN"],
["M60E4","CUP_Weapon_lmg_M60E4","CUP_Weapons","CIVILIAN"],
["M240","CUP_Weapon_lmg_M240","CUP_Weapons","CIVILIAN"],
["M240 with M143","CUP_Weapon_lmg_M240_ElcanM143","CUP_Weapons","CIVILIAN"],
["L7A2","CUP_Weapon_lmg_L7A2","CUP_Weapons","CIVILIAN"],
["FN Minimi Para","CUP_Weapon_lmg_minimipara","CUP_Weapons","CIVILIAN"],
["FN Minimi (18.3 in.)","CUP_Weapon_lmg_minimi","CUP_Weapons","CIVILIAN"],
["FN Minimi (18.3 in.) Railed","CUP_Weapon_lmg_minimi_railed","CUP_Weapons","CIVILIAN"],
["M249E2 Para(13.7in.)","CUP_Weapon_lmg_m249_para","CUP_Weapons","CIVILIAN"],
["M249E2","CUP_Weapon_lmg_m249_E2","CUP_Weapons","CIVILIAN"],
["M249 PIP (RIS/18.3 in.)","CUP_Weapon_lmg_m249_pip1","CUP_Weapons","CIVILIAN"],
["M249E2 (RIS/13.7 in.)","CUP_Weapon_lmg_m249_pip2","CUP_Weapons","CIVILIAN"],
["M249 PIP (RIS/PIP Stock)","CUP_Weapon_lmg_m249_pip3","CUP_Weapons","CIVILIAN"],
["M249 PIP (VFG/PIP Stock)","CUP_Weapon_lmg_m249_pip4","CUP_Weapons","CIVILIAN"],
["M249 PIP (VFG/PIP Stock) with M145, Laser","CUP_Weapon_lmg_m249_ElcanM145_Laser","CUP_Weapons","CIVILIAN"],
["M249 PIP (VFG/PIP Stock) with Laser","CUP_Weapon_lmg_m249_Laser","CUP_Weapons","CIVILIAN"],
["M249 PIP (VFG/PIP Stock) with ANPAS13c2, Laser","CUP_Weapon_lmg_m249_ANPAS13c2_Laser","CUP_Weapons","CIVILIAN"],
["Mk48 Mod 0 (desert)","CUP_Weapon_lmg_Mk48_des","CUP_Weapons","CIVILIAN"],
["Mk48 Mod 0 (desert) with AIM, Laser","CUP_Weapon_lmg_Mk48_des_Aim_Laser","CUP_Weapons","CIVILIAN"],
["Mk48 Mod 0 (woodland)","CUP_Weapon_lmg_Mk48_wdl","CUP_Weapons","CIVILIAN"],
["Mk48 Mod 0 (woodland) with AIM, Laser","CUP_Weapon_lmg_Mk48_wdl_Aim_Laser","CUP_Weapons","CIVILIAN"],
["PKM","CUP_Weapon_lmg_PKM","CUP_Weapons","CIVILIAN"],
["PKP Pecheneg","CUP_Weapon_lmg_Pecheneg","CUP_Weapons","CIVILIAN"],
["PKP Pecheneg Scope","CUP_Weapon_lmg_Pecheneg_PScope","CUP_Weapons","CIVILIAN"],
["UK59","CUP_Weapon_lmg_UK59","CUP_Weapons","CIVILIAN"]]
