[
["IFV-6a Cheetah","B_T_APC_Tracked_01_AA_F","expansion","WEST"],
["ZSU-39 Tigris","O_T_APC_Tracked_02_AA_ghex_F","expansion","EAST"],
["ZSU-23-4V1","gm_gc_army_zsu234v1","GM","EAST"],
["ZSU-23-4V1","gm_pl_army_zsu234v1","GM","EAST"],
["FlakPz 1A1","gm_ge_army_gepard1a1","GM","WEST"],
["2S6 Tunguska","CUP_O_2S6_RU","CUP_Vehicles","EAST"],
["2S6M Tunguska-M","CUP_O_2S6M_RU","CUP_Vehicles","EAST"],
["M6 Linebacker (Desert)","CUP_B_M6LineBacker_USA_D","CUP_Vehicles","WEST"],
["M6 Linebacker (Woodland)","CUP_B_M6LineBacker_USA_W","CUP_Vehicles","WEST"],
["M6 Linebacker","CUP_B_M6LineBacker_NATO_T","CUP_Vehicles","WEST"],
["M163A1 VADS","CUP_B_M163_USA","CUP_Vehicles","WEST"],
["M163A1 VADS","CUP_I_M163_AAF","CUP_Vehicles","RESISTANCE"],
["M163A1 Vulcan-Gavin","CUP_I_M163_RACS","CUP_Vehicles","RESISTANCE"],
["ZSU-23-4","CUP_B_ZSU23_CDF","CUP_Vehicles","WEST"],
["ZSU-23-4","CUP_I_ZSU23_AAF","CUP_Vehicles","RESISTANCE"],
["ZSU-23-4","CUP_O_ZSU23_ChDKZ","CUP_Vehicles","EAST"],
["ZSU-23-4","CUP_O_ZSU23_TK","CUP_Vehicles","EAST"],
["ZSU-23-4","CUP_O_ZSU23_SLA","CUP_Vehicles","EAST"],
["ZSU-23-4","CUP_O_ZSU23_CSAT","CUP_Vehicles","EAST"],
["ZSU-23-4 Afghanski","CUP_B_ZSU23_Afghan_CDF","CUP_Vehicles","WEST"],
["ZSU-23-4 Afghanski","CUP_I_ZSU23_Afghan_AAF","CUP_Vehicles","RESISTANCE"],
["ZSU-23-4 Afghanski","CUP_O_ZSU23_Afghan_ChDKZ","CUP_Vehicles","EAST"],
["ZSU-23-4 Afghanski","CUP_O_ZSU23_Afghan_TK","CUP_Vehicles","EAST"],
["ZSU-23-4 Afghanski","CUP_O_ZSU23_Afghan_SLA","CUP_Vehicles","EAST"],
["ZSU-23-4 Afghanski","CUP_O_ZSU23_Afghan_CSAT","CUP_Vehicles","EAST"],
["Datsun 620 Pickup (AA)","CUP_O_Datsun_AA","CUP_Vehicles","EAST"],
["Datsun 620 Pickup (AA)","CUP_I_Datsun_AA","CUP_Vehicles","RESISTANCE"],
["Datsun 620 Pickup (AA)","CUP_I_Datsun_AA_TK","CUP_Vehicles","RESISTANCE"],
["Datsun 620 Pickup (AA) Woodland","CUP_O_Datsun_AA_Random","CUP_Vehicles","EAST"],
["Datsun 620 Pickup (AA) Woodland","CUP_I_Datsun_AA_Random","CUP_Vehicles","RESISTANCE"],
["Datsun 620 Pickup (AA) Desert","CUP_I_Datsun_AA_TK_Random","CUP_Vehicles","RESISTANCE"],
["HMMWV Avenger","CUP_B_HMMWV_Avenger_USMC","CUP_Vehicles","WEST"],
["HMMWV Avenger","CUP_B_HMMWV_Avenger_USA","CUP_Vehicles","WEST"],
["HMMWV Avenger","CUP_B_HMMWV_Avenger_NATO_T","CUP_Vehicles","WEST"],
["Land Rover 110 (AA)","CUP_I_LR_AA_AAF","CUP_Vehicles","RESISTANCE"],
["Land Rover 110 (AA)","CUP_I_LR_AA_RACS","CUP_Vehicles","RESISTANCE"],
["Land Rover 110 (AA)","CUP_O_LR_AA_TKA","CUP_Vehicles","EAST"],
["Land Rover 110 (AA)","CUP_O_LR_AA_TKM","CUP_Vehicles","EAST"],
["UAZ-469 (AA)","CUP_B_UAZ_AA_CDF","CUP_Vehicles","WEST"],
["UAZ-469 (AA)","CUP_O_UAZ_AA_CHDKZ","CUP_Vehicles","EAST"],
["UAZ-469 (AA)","CUP_O_UAZ_AA_SLA","CUP_Vehicles","EAST"],
["UAZ-469 (AA)","CUP_O_UAZ_AA_CSAT","CUP_Vehicles","EAST"],
["UAZ-469 (AA)","CUP_O_UAZ_AA_RU","CUP_Vehicles","EAST"],
["UAZ-469 (AA)","CUP_O_UAZ_AA_TKA","CUP_Vehicles","EAST"],
["UAZ-469 (AA)","CUP_I_UAZ_AA_UN","CUP_Vehicles","RESISTANCE"],
["Ural (ZU-23)","CUP_O_Ural_ZU23_RU","CUP_Vehicles","EAST"],
["Ural (ZU-23)","CUP_B_Ural_ZU23_CDF","CUP_Vehicles","WEST"],
["Ural (ZU-23)","CUP_O_Ural_ZU23_CHDKZ","CUP_Vehicles","EAST"],
["Ural (ZU-23)","CUP_O_Ural_ZU23_TKA","CUP_Vehicles","EAST"],
["Ural (ZU-23)","CUP_I_Ural_ZU23_TK_Gue","CUP_Vehicles","RESISTANCE"],
["Ural (ZU-23)","CUP_O_Ural_ZU23_TKM","CUP_Vehicles","EAST"],
["Ural (ZU-23)","CUP_O_Ural_ZU23_SLA","CUP_Vehicles","EAST"],
["Ural (ZU-23)","CUP_I_Ural_ZU23_NAPA","CUP_Vehicles","RESISTANCE"]
]
