[["CMR-76 6,5 mm (Schwarz)","Weapon_srifle_DMR_07_blk_F","expansion","CIVILIAN"],
["CMR-76 6,5 mm (Sechsecke)","Weapon_srifle_DMR_07_hex_F","expansion","CIVILIAN"],
["CMR-76 6,5 mm (GrÃ¼ne Sechsecke)","Weapon_srifle_DMR_07_ghex_F","expansion","CIVILIAN"],
["M320 LRR .408 (Tropen)","Weapon_srifle_LRR_tna_F","expansion","CIVILIAN"],
["GM6 Lynx 12,7 mm (GrÃ¼ne Sechsecke)","Weapon_srifle_GM6_ghex_F","expansion","CIVILIAN"],
["SVD 7.62x54 mmR","gm_placeableweapon_svd_wud","GM","CIVILIAN"],
["Boden","CUP_Weapons_SniperRifles_Base","CUP_Weapons","CIVILIAN"],
["AS50","CUP_Weapon_srifle_AS50","CUP_Weapons","CIVILIAN"],
["AS50 with SBPMII","CUP_Weapon_srifle_AS50_SBPMII","CUP_Weapons","CIVILIAN"],
["AS50 with AMPAS13c2","CUP_Weapon_srifle_AS50_AMPAS13c2","CUP_Weapons","CIVILIAN"],
["L115A1 (Desert)","CUP_Weapon_srifle_AWM_des","CUP_Weapons","CIVILIAN"],
["L115A1 (Desert) With SBPMII","CUP_Weapon_srifle_AWM_des_SBPMII","CUP_Weapons","CIVILIAN"],
["L115A1 (Woodland)","CUP_Weapon_srifle_AWM_wdl","CUP_Weapons","CIVILIAN"],
["L115A1 (Woodland) with SBPMII","CUP_Weapon_srifle_AWM_wdl_SBPMII","CUP_Weapons","CIVILIAN"],
["G22 (Desert)","CUP_Weapon_srifle_G22_des","CUP_Weapons","CIVILIAN"],
["G22 (Desert) with SBPMII","CUP_Weapon_srifle_G22_des_SBPMII","CUP_Weapons","CIVILIAN"],
["CZ 750 S1 M1","CUP_Weapon_srifle_CZ750","CUP_Weapons","CIVILIAN"],
["CZ 750 S1 M1 with SOS, Bipod","CUP_Weapon_srifle_CZ750_SOS_bipod","CUP_Weapons","CIVILIAN"],
["CZ 550","CUP_Weapon_srifle_CZ550","CUP_Weapons","CIVILIAN"],
["CZ 550 with Rail","CUP_Weapon_srifle_CZ550_rail","CUP_Weapons","CIVILIAN"],
["KSVK","CUP_Weapon_srifle_ksvk","CUP_Weapons","CIVILIAN"],
["KSVK with PSO3","CUP_Weapon_srifle_ksvk_PSO3","CUP_Weapons","CIVILIAN"],
["L129A1","CUP_Weapon_srifle_L129A1","CUP_Weapons","CIVILIAN"],
["L129A1 with Grip","CUP_Weapon_srifle_L129A1_HG","CUP_Weapons","CIVILIAN"],
["Lee Enfield","CUP_Weapon_srifle_LeeEnfield","CUP_Weapons","CIVILIAN"],
["Lee Enfield with Rail","CUP_Weapon_srifle_LeeEnfield_rail","CUP_Weapons","CIVILIAN"],
["M14","CUP_Weapon_srifle_M14","CUP_Weapons","CIVILIAN"],
["M14 DMR","CUP_Weapon_srifle_M14_DMR","CUP_Weapons","CIVILIAN"],
["M14 DMR with Leupold Mk4","CUP_Weapon_srifle_M14_DMR_LeupoldMk4","CUP_Weapons","CIVILIAN"],
["M14 DMR with Leupold Mk4, Silencer","CUP_Weapon_srifle_M14_DMR_LeupoldMk4_snds","CUP_Weapons","CIVILIAN"],
["Mk12SPR","CUP_Weapon_srifle_Mk12SPR","CUP_Weapons","CIVILIAN"],
["Mk12SPR with Leupold M3LR","CUP_Weapon_srifle_Mk12SPR_LeupoldM3LR","CUP_Weapons","CIVILIAN"],
["Mk12SPR with Leupold M3LR, Silencer","CUP_Weapon_srifle_Mk12SPR_LeupoldM3LR_bipod","CUP_Weapons","CIVILIAN"],
["M24 (desert)","CUP_Weapon_srifle_M24_des","CUP_Weapons","CIVILIAN"],
["M24 (desert) with Leupold Mk4 LRT","CUP_Weapon_srifle_M24_des_LeupoldMk4LRT","CUP_Weapons","CIVILIAN"],
["M24 (woodland)","CUP_Weapon_srifle_M24_wdl","CUP_Weapons","CIVILIAN"],
["M24 (woodland) with Leupold Mk4 LRT","CUP_Weapon_srifle_M24_wdl_LeupoldMk4LRT","CUP_Weapons","CIVILIAN"],
["M24 Ghillie","CUP_Weapon_srifle_M24_ghillie","CUP_Weapons","CIVILIAN"],
["M24 Ghillie with Bipod","CUP_Weapon_srifle_M24_ghillie_bipod","CUP_Weapons","CIVILIAN"],
["M40A3","CUP_Weapon_srifle_M40A3","CUP_Weapons","CIVILIAN"],
["M40A3 with Bipod","CUP_Weapon_srifle_M40A3_bipod","CUP_Weapons","CIVILIAN"],
["M107","CUP_Weapon_srifle_M107_Base","CUP_Weapons","CIVILIAN"],
["M107 with Leupold VX3","CUP_Weapon_srifle_M107_LeupoldVX3","CUP_Weapons","CIVILIAN"],
["M107 with ANPAS13c2","CUP_Weapon_srifle_M107_ANPAS13c2","CUP_Weapons","CIVILIAN"],
["M110","CUP_Weapon_srifle_M110","CUP_Weapons","CIVILIAN"],
["M110 with ANPAS13c2","CUP_Weapon_srifle_M110_ANPAS13c2","CUP_Weapons","CIVILIAN"],
["M110 with ANPVS10","CUP_Weapon_srifle_M110_ANPVS10","CUP_Weapons","CIVILIAN"],
["Dragunov SVD","CUP_Weapon_srifle_SVD","CUP_Weapons","CIVILIAN"],
["Dragunov SVD with PSO","CUP_Weapon_srifle_SVD_pso","CUP_Weapons","CIVILIAN"],
["Dragunov SVD with NSPU","CUP_Weapon_srifle_SVD_NSPU","CUP_Weapons","CIVILIAN"],
["Dragunov SVD Desert","CUP_Weapon_srifle_SVD_des","CUP_Weapons","CIVILIAN"],
["Dragunov SVD Desert with PSO","CUP_Weapon_srifle_SVD_des_pso","CUP_Weapons","CIVILIAN"],
["Dragunov SVD Desert Ghillie with PSO","CUP_Weapon_srifle_SVD_des_ghillie_pso","CUP_Weapons","CIVILIAN"],
["Dragunov SVD Woodland Ghillie","CUP_Weapon_srifle_SVD_wdl_ghillie","CUP_Weapons","CIVILIAN"],
["VSS Vintorez","CUP_Weapon_srifle_VSSVintorez","CUP_Weapons","CIVILIAN"],
["VSS Vintorez with PSO","CUP_Weapon_srifle_VSSVintorez_pso","CUP_Weapons","CIVILIAN"]]
