[["Skater-Helm","Headgear_H_Helmet_Skate","expansion","CIVILIAN"],
["MilitÃ¤rmÃ¼tze (Tropen)","Headgear_H_MilCap_tna_F","expansion","CIVILIAN"],
["MilitÃ¤rmÃ¼tze (GrÃ¼ne Sechsecke)","Headgear_H_MilCap_ghex_F","expansion","CIVILIAN"],
["Tarnhut (Tropen)","Headgear_H_Booniehat_tna_F","expansion","CIVILIAN"],
["Barett (Gendarmerie)","Headgear_H_Beret_gen_F","expansion","CIVILIAN"],
["MilitÃ¤rmÃ¼tze (Gendarmerie)","Headgear_H_MilCap_gen_F","expansion","CIVILIAN"],
["Barett (rot) [CSAT]","Headgear_H_Beret_CSAT_01_F","expansion","CIVILIAN"],
["Panzerhaube, Schwarz","gm_placeableItem_gc_army_headgear_crewhat_80_blk","GM","CIVILIAN"],
["PolizeischirmmÃ¼tze","gm_placeableItem_gc_pol_headgear_cap_80_blu","GM","CIVILIAN"],
["OffizierschirmmÃ¼tze","gm_placeableItem_gc_army_headgear_cap_80_gry","GM","CIVILIAN"],
["Schiffchen, GrÃ¼n","gm_placeableItem_gc_army_headgear_hat_80_grn","GM","CIVILIAN"],
["Schiffchen, Grau","gm_placeableItem_gc_bgs_headgear_hat_80_gry","GM","CIVILIAN"],
["FJH Modell 4","gm_placeableItem_gc_headgear_fjh_model4_oli","GM","CIVILIAN"],
["FJH Modell 4 (WeiÃŸ)","gm_placeableItem_gc_headgear_fjh_model4_wht","GM","CIVILIAN"],
["Beret (Dungelgrau)","gm_placeableItem_gc_headgear_beret_blk","GM","CIVILIAN"],
["Beret (Orange)","gm_placeableItem_gc_headgear_beret_orn","GM","CIVILIAN"],
["Beret (Strichtarn)","gm_placeableItem_gc_headgear_beret_str","GM","CIVILIAN"],
["Beret (Offizier, Dungelgrau)","gm_placeableItem_gc_headgear_beret_officer_blk","GM","CIVILIAN"],
["Beret (Offizier, Orange)","gm_placeableItem_gc_headgear_beret_officer_orn","GM","CIVILIAN"],
["Beret (Offizier, Strichtarn)","gm_placeableItem_gc_headgear_beret_officer_str","GM","CIVILIAN"],
["SchM-41M","gm_placeableItem_gc_army_facewear_schm41m","GM","CIVILIAN"],
["Schutzbrille","gm_placeableItem_gc_army_facewear_dustglasses","GM","CIVILIAN"],
["BrieftrÃ¤germÃ¼tze","gm_placeableItem_ge_dbp_headgear_cap_80_blu","GM","CIVILIAN"],
["PolizeimÃ¼tze, WeiÃŸ","gm_placeableItem_ge_pol_headgear_cap_80_wht","GM","CIVILIAN"],
["PolizeimÃ¼tze, GrÃ¼n","gm_placeableItem_ge_pol_headgear_cap_80_grn","GM","CIVILIAN"],
["Panzerhaube","gm_placeableItem_ge_headgear_crewhat_80_blk","GM","CIVILIAN"],
["Sprechsatz","gm_placeableItem_ge_headgear_headset_crew_oli","GM","CIVILIAN"],
["Barett, grÃ¼n","gm_placeableItem_ge_headgear_beret_grn","GM","CIVILIAN"],
["Barett, bordeauxrot","gm_placeableItem_ge_headgear_beret_bdx","GM","CIVILIAN"],
["Barett, schwarz","gm_placeableItem_ge_headgear_beret_blk","GM","CIVILIAN"],
["Barett, Korallenrot","gm_placeableItem_ge_headgear_beret_red","GM","CIVILIAN"],
["Barett, Kobaltblau","gm_placeableItem_ge_headgear_beret_blu","GM","CIVILIAN"],
["Barett, Marineblau","gm_placeableItem_ge_headgear_beret_mrb","GM","CIVILIAN"],
["Barett, Cyan","gm_placeableItem_ge_headgear_beret_un","GM","CIVILIAN"],
["FeldmÃ¼tze, Oliv","gm_placeableItem_ge_headgear_hat_80_oli","GM","CIVILIAN"],
["FeldmÃ¼tze, Grau","gm_placeableItem_ge_headgear_hat_80_gry","GM","CIVILIAN"],
["WintermÃ¼tze","gm_placeableItem_ge_headgear_winterhat_80_oli","GM","CIVILIAN"],
["Dschungelhut, Woodland","gm_placeableItem_ge_headgear_hat_boonie_wdl","GM","CIVILIAN"],
["Dschungelhut, Oliv","gm_placeableItem_ge_headgear_hat_boonie_oli","GM","CIVILIAN"],
["WollmÃ¼tze, Schwarz","gm_placeableItem_ge_headgear_hat_beanie_blk","GM","CIVILIAN"],
["FeldmÃ¼tze wz.0443","gm_placeableItem_pl_army_headgear_cap_80_moro","GM","CIVILIAN"],
["Barett (Polen, Schwarz)","gm_placeableItem_pl_headgear_beret_blk","GM","CIVILIAN"],
["Barett (Polen, Blau)","gm_placeableItem_pl_headgear_beret_blu","GM","CIVILIAN"],
["Barett (Polen, Rot)","gm_placeableItem_pl_headgear_beret_bdx","GM","CIVILIAN"],
["Dschungelhut, M/84","gm_placeableItem_dk_headgear_hat_boonie_m84","GM","CIVILIAN"]]
