[["MX 6,5 mm (Khaki)","Weapon_arifle_MX_khk_F","expansion","CIVILIAN"],
["MX 3GL 6,5 mm (Khaki)","Weapon_arifle_MX_GL_khk_F","expansion","CIVILIAN"],
["MXC 6,5 mm (Khaki)","Weapon_arifle_MXC_khk_F","expansion","CIVILIAN"],
["MXM 6,5 mm (Khaki)","Weapon_arifle_MXM_khk_F","expansion","CIVILIAN"],
["AK-12 7,62 mm","Weapon_arifle_AK12_F","expansion","CIVILIAN"],
["AK-12 GL 7,62 mm","Weapon_arifle_AK12_GL_F","expansion","CIVILIAN"],
["Typ 115 6,5 mm (Schwarz)","Weapon_arifle_ARX_blk_F","expansion","CIVILIAN"],
["Typ 115 6,5 mm (GrÃ¼ne Sechsecke)","Weapon_arifle_ARX_ghex_F","expansion","CIVILIAN"],
["Typ 115 6,5 mm (Sechsecke)","Weapon_arifle_ARX_hex_F","expansion","CIVILIAN"],
["CAR-95 5,8 mm (Schwarz)","Weapon_arifle_CTAR_blk_F","expansion","CIVILIAN"],
["CAR-95 5,8mm (Sechsecke)","Weapon_arifle_CTAR_hex_F","expansion","CIVILIAN"],
["CAR-95 5,8 mm (GrÃ¼ne Sechsecke)","Weapon_arifle_CTAR_ghex_F","expansion","CIVILIAN"],
["CAR-95 GL 5,8 mm (Schwarz)","Weapon_arifle_CTAR_GL_blk_F","expansion","CIVILIAN"],
["CAR-95 GL 5,8mm (Sechsecke)","Weapon_arifle_CTAR_GL_hex_F","expansion","CIVILIAN"],
["CAR-95 GL 5,8 mm (GrÃ¼ne Sechsecke)","Weapon_arifle_CTAR_GL_ghex_F","expansion","CIVILIAN"],
["CAR-95-1 5,8 mm (Schwarz)","Weapon_arifle_CTARS_blk_F","expansion","CIVILIAN"],
["CAR-95-1 5,8mm (Sechsecke)","Weapon_arifle_CTARS_hex_F","expansion","CIVILIAN"],
["CAR-95-1 5,8 mm (GrÃ¼ne Sechsecke)","Weapon_arifle_CTARS_ghex_F","expansion","CIVILIAN"],
["SPAR-16 5,56 mm (Schwarz)","Weapon_arifle_SPAR_01_blk_F","expansion","CIVILIAN"],
["SPAR-16 5,56 mm (Khaki)","Weapon_arifle_SPAR_01_khk_F","expansion","CIVILIAN"],
["SPAR-16 5,56 mm (Sand)","Weapon_arifle_SPAR_01_snd_F","expansion","CIVILIAN"],
["SPAR-16 GL 5,56 mm (Schwarz)","Weapon_arifle_SPAR_01_GL_blk_F","expansion","CIVILIAN"],
["SPAR-16 GL 5,56 mm (Khaki)","Weapon_arifle_SPAR_01_GL_khk_F","expansion","CIVILIAN"],
["SPAR-16 GL 5,56 mm (Sand)","Weapon_arifle_SPAR_01_GL_snd_F","expansion","CIVILIAN"],
["SPAR-16S 5,56 mm (Schwarz)","Weapon_arifle_SPAR_02_blk_F","expansion","CIVILIAN"],
["SPAR-16S 5,56 mm (Khaki)","Weapon_arifle_SPAR_02_khk_F","expansion","CIVILIAN"],
["SPAR-16S 5,56 mm (Sand)","Weapon_arifle_SPAR_02_snd_F","expansion","CIVILIAN"],
["SPAR-17 7,62 mm (Schwarz)","Weapon_arifle_SPAR_03_blk_F","expansion","CIVILIAN"],
["SPAR-17 7,62 mm (Khaki)","Weapon_arifle_SPAR_03_khk_F","expansion","CIVILIAN"],
["SPAR-17 7,62 mm (Sand)","Weapon_arifle_SPAR_03_snd_F","expansion","CIVILIAN"],
["AKM 7,62 mm","Weapon_arifle_AKM_F","expansion","CIVILIAN"],
["AKS-74U 5,45 mm","Weapon_arifle_AKS_F","expansion","CIVILIAN"],
["AKM 7,62x39 mm","gm_placeableweapon_akm_wud","GM","CIVILIAN"],
["AKMN 7,62x39 mm","gm_placeableweapon_akmn_wud","GM","CIVILIAN"],
["RPK 7,62x39 mm","gm_placeableweapon_rpk_wud","GM","CIVILIAN"],
["MPi KM-72 7,62x39 mm (Dunkellila)","gm_placeableweapon_mpikm72_prp","GM","CIVILIAN"],
["MPi KMS-72 7,62x39 mm (Dunkellila)","gm_placeableweapon_mpikms72_prp","GM","CIVILIAN"],
["lMG RPK 7,62x39 mm (Dunkellila)","gm_placeableweapon_lmgrpk_prp","GM","CIVILIAN"],
["MPi KM-72 7,62x39 mm","gm_placeableweapon_mpikm72_brn","GM","CIVILIAN"],
["MPi KMS-72 7,62x39 mm","gm_placeableweapon_mpikms72_brn","GM","CIVILIAN"],
["lMG RPK 7,62x39 mm","gm_placeableweapon_lmgrpk_brn","GM","CIVILIAN"],
["MPi AK-74 5,45x39 mm (Dunkellila)","gm_placeableweapon_mpiak74n_prp","GM","CIVILIAN"],
["MPi AKS-74 5,45x39 mm (Dunkellila)","gm_placeableweapon_mpiaks74n_prp","GM","CIVILIAN"],
["MPi AKS-74K 5,45x39 mm (Dunkellila)","gm_placeableweapon_mpiaks74nk_prp","GM","CIVILIAN"],
["lMG RPK-74 5,45x39 mm (Dunkellila)","gm_placeableweapon_lmgrpk74n_prp","GM","CIVILIAN"],
["MPi AK-74 5,45x39 mm","gm_placeableweapon_mpiak74n_brn","GM","CIVILIAN"],
["MPi AKS-74 5,45x39 mm","gm_placeableweapon_mpiaks74n_brn","GM","CIVILIAN"],
["MPi AKS-74K 5,45x39 mm","gm_placeableweapon_mpiaks74nk_brn","GM","CIVILIAN"],
["lMG RPK-74 5,45x39 mm","gm_placeableweapon_lmgrpk74n_brn","GM","CIVILIAN"],
["G3A3 7,62x51 mm","gm_placeableweapon_g3a3_oli","GM","CIVILIAN"],
["G3A3 7,62x51 mm (Schwarz)","gm_placeableweapon_g3a3_blk","GM","CIVILIAN"],
["G3A3 7,62x51 mm (GrÃ¼n)","gm_placeableweapon_g3a3_grn","GM","CIVILIAN"],
["G3A3 7,62x51 mm (WÃ¼ste)","gm_placeableweapon_g3a3_des","GM","CIVILIAN"],
["G3A4 7,62x51 mm","gm_placeableweapon_g3a4_oli","GM","CIVILIAN"],
["G3A4 7,62x51 mm (Schwarz)","gm_placeableweapon_g3a4_blk","GM","CIVILIAN"],
["G3A4 7,62x51 mm (GrÃ¼n)","gm_placeableweapon_g3a4_grn","GM","CIVILIAN"],
["G3A4 7,62x51 mm (WÃ¼ste)","gm_placeableweapon_g3a4_des","GM","CIVILIAN"],
["GV M/75 7.62x51 mm","gm_placeableweapon_gvm75_oli","GM","CIVILIAN"],
["GV M/75 7.62x51 mm (Schwarz)","gm_placeableweapon_gvm75_blk","GM","CIVILIAN"],
["GV M/75 7.62x51 mm (GrÃ¼n)","gm_placeableweapon_gvm75_grn","GM","CIVILIAN"],
["GV M/75 Karabiner 7.62x51 mm","gm_placeableweapon_gvm75carb_oli","GM","CIVILIAN"],
["GV M/75 Karabiner 7.62x51 mm (Schwarz)","gm_placeableweapon_gvm75carb_blk","GM","CIVILIAN"],
["GV M/75 Karabiner 7.62x51 mm (GrÃ¼n)","gm_placeableweapon_gvm75carb_grn","GM","CIVILIAN"],
["M16A1 5,56x45 mm","gm_placeableweapon_m16a1_blk","GM","CIVILIAN"],
["M16A2 5,56x45 mm","gm_placeableweapon_m16a2_blk","GM","CIVILIAN"],
["C7A1 5.56x45 mm (Schwarz)","gm_placeableweapon_c7a1_blk","GM","CIVILIAN"],
["C7A1 5.56x45 mm","gm_placeableweapon_c7a1_oli","GM","CIVILIAN"],
["GV M/95 5.56x45 mm","gm_placeableweapon_gvm95_blk","GM","CIVILIAN"],
["Boden","CUP_Weapons_AssaultRifles_Base","CUP_Weapons","CIVILIAN"],
["AK47","CUP_Weapon_arifle_AK47","CUP_Weapons","CIVILIAN"],
["AK74","CUP_Weapon_arifle_AK74","CUP_Weapons","CIVILIAN"],
["AK74 Underbarrel","CUP_Weapon_arifle_AK74_GL","CUP_Weapons","CIVILIAN"],
["AK74 Underbarrel with Kobra","CUP_Weapon_arifle_AK74_GL_kobra","CUP_Weapons","CIVILIAN"],
["AK74M","CUP_Weapon_arifle_AK74M","CUP_Weapons","CIVILIAN"],
["AK74M with PSO","CUP_Weapon_arifle_AK74M_pso","CUP_Weapons","CIVILIAN"],
["AK74M with Kobra","CUP_Weapon_arifle_AK74M_kobra","CUP_Weapons","CIVILIAN"],
["AK74M Underbarrel","CUP_Weapon_arifle_AK74M_GL","CUP_Weapons","CIVILIAN"],
["AK74M Underbarrel with Kobra","CUP_Weapon_arifle_AK74M_GL_kobra","CUP_Weapons","CIVILIAN"],
["AK74M Underbarrel with PSO","CUP_Weapon_arifle_AK74M_GL_pso","CUP_Weapons","CIVILIAN"],
["AK107","CUP_Weapon_arifle_AK107","CUP_Weapons","CIVILIAN"],
["AK107 with Kobra","CUP_Weapon_arifle_AK107_kobra","CUP_Weapons","CIVILIAN"],
["AK107 with PSO","CUP_Weapon_arifle_AK107_pso","CUP_Weapons","CIVILIAN"],
["AK107 Underbarrel","CUP_Weapon_arifle_AK107_GL","CUP_Weapons","CIVILIAN"],
["AK107 Underbarrel with Kobra","CUP_Weapon_arifle_AK107_GL_kobra","CUP_Weapons","CIVILIAN"],
["AK107 Underbarrel with PSO","CUP_Weapon_arifle_AK107_GL_pso","CUP_Weapons","CIVILIAN"],
["AKS74","CUP_Weapon_arifle_AKS74","CUP_Weapons","CIVILIAN"],
["AKS74 with NSPU","CUP_Weapon_arifle_AKS74_NSPU","CUP_Weapons","CIVILIAN"],
["AKS74 with Goshawk","CUP_Weapon_arifle_AKS74_Goshawk","CUP_Weapons","CIVILIAN"],
["AKS74 with Kobra","CUP_Weapon_arifle_AKS74_kobra","CUP_Weapons","CIVILIAN"],
["AKS74 with PSO","CUP_Weapon_arifle_AKS74_pso","CUP_Weapons","CIVILIAN"],
["AKS74U","CUP_Weapon_arifle_AKS74U","CUP_Weapons","CIVILIAN"],
["AKS74U with Kobra, Silencer","CUP_Weapon_arifle_AKS74UN_kobra_snds","CUP_Weapons","CIVILIAN"],
["AKM","CUP_Weapon_arifle_AKM","CUP_Weapons","CIVILIAN"],
["AKS","CUP_Weapon_arifle_AKS","CUP_Weapons","CIVILIAN"],
["AKS Gold","CUP_Weapon_arifle_AKS_Gold","CUP_Weapons","CIVILIAN"],
["RPK74","CUP_Weapon_arifle_RPK74","CUP_Weapons","CIVILIAN"],
["RPK74 45","CUP_Weapon_arifle_RPK74_45","CUP_Weapons","CIVILIAN"],
["RPK74M","CUP_Weapon_arifle_RPK74M","CUP_Weapons","CIVILIAN"],
["CZ805 A1","CUP_Weapon_arifle_CZ805_A1","CUP_Weapons","CIVILIAN"],
["CZ805 A1 with Holo, Laser","CUP_Weapon_arifle_CZ805_A1_Holo_Laser","CUP_Weapons","CIVILIAN"],
["CZ805 A1 with ACO, Laser","CUP_Weapon_arifle_CZ805_A1_Aco_Laser","CUP_Weapons","CIVILIAN"],
["CZ805 A1 with MRCO, Laser","CUP_Weapon_arifle_CZ805_A1_MRCO_Laser","CUP_Weapons","CIVILIAN"],
["CZ805 A1 with ZDot, Laser","CUP_Weapon_arifle_CZ805_A1_ZDDot_Laser","CUP_Weapons","CIVILIAN"],
["CZ805 A2","CUP_Weapon_arifle_CZ805_A2","CUP_Weapons","CIVILIAN"],
["CZ805 A2 with Holo, Laser","CUP_Weapon_arifle_CZ805_A2_Holo_Laser","CUP_Weapons","CIVILIAN"],
["CZ805 A2 with ACO, Laser","CUP_Weapon_arifle_CZ805_A2_Aco_Laser","CUP_Weapons","CIVILIAN"],
["CZ805 A2 with ACO, Laser","CUP_Weapon_arifle_CZ805_A2_MRCO_Laser","CUP_Weapons","CIVILIAN"],
["CZ805 A2 with ZDot, Flashlight, Silencer","CUP_Weapon_arifle_CZ805_A2_ZDDot_Flashlight_Snds","CUP_Weapons","CIVILIAN"],
["CZ805 Underbarrel","CUP_Weapon_arifle_CZ805_GL","CUP_Weapons","CIVILIAN"],
["CZ805 Underbarrel with HAMR, Laser","CUP_Weapon_arifle_CZ805_GL_Hamr_Laser","CUP_Weapons","CIVILIAN"],
["CZ805 Underbarrel with ZDot, Laser","CUP_Weapon_arifle_CZ805_GL_ZDDot_Laser","CUP_Weapons","CIVILIAN"],
["CZ805 B","CUP_Weapon_arifle_CZ805_B","CUP_Weapons","CIVILIAN"],
["CZ805 B Underbarrel","CUP_Weapon_arifle_CZ805_B_GL","CUP_Weapons","CIVILIAN"],
["CZ805 B Underbarrel with ACOG, Laser","CUP_Weapon_arifle_CZ805B_GL_ACOG_Laser","CUP_Weapons","CIVILIAN"],
["FN FAL","CUP_Weapon_arifle_FNFAL","CUP_Weapons","CIVILIAN"],
["FAL 50.61","CUP_Weapon_arifle_FNFAL5061","CUP_Weapons","CIVILIAN"],
["FAL 50.62","CUP_Weapon_arifle_FNFAL5062","CUP_Weapons","CIVILIAN"],
["FAL OSW","CUP_Weapon_arifle_FNFAL_OSW","CUP_Weapons","CIVILIAN"],
["FAL 50.63 (RIS)","CUP_Weapon_arifle_FNFAL_railed","CUP_Weapons","CIVILIAN"],
["FN FAL with ANPVS4","CUP_Weapon_arifle_FNFAL_ANPVS4","CUP_Weapons","CIVILIAN"],
["G36A","CUP_Weapon_arifle_G36A","CUP_Weapons","CIVILIAN"],
["G36A Camo","CUP_Weapon_arifle_G36A_camo","CUP_Weapons","CIVILIAN"],
["G36K","CUP_Weapon_arifle_G36K","CUP_Weapons","CIVILIAN"],
["G36K Camo","CUP_Weapon_arifle_G36K_camo","CUP_Weapons","CIVILIAN"],
["G36C","CUP_Weapon_arifle_G36C","CUP_Weapons","CIVILIAN"],
["G36C Camo","CUP_Weapon_arifle_G36C_camo","CUP_Weapons","CIVILIAN"],
["MG36","CUP_Weapon_arifle_MG36","CUP_Weapons","CIVILIAN"],
["MG36 Camo","CUP_Weapon_arifle_MG36_camo","CUP_Weapons","CIVILIAN"],
["G36C with Holo, Silencer","CUP_Weapon_arifle_G36C_holo_snds","CUP_Weapons","CIVILIAN"],
["G36C Camo with Holo, Silencer","CUP_Weapon_arifle_G36C_camo_holo_snds","CUP_Weapons","CIVILIAN"],
["MG36 with Holo","CUP_Weapon_arifle_MG36_holo","CUP_Weapons","CIVILIAN"],
["MG36 Camo with Holo","CUP_Weapon_arifle_MG36_camo_holo","CUP_Weapons","CIVILIAN"],
["L85A2","CUP_Weapon_arifle_L85A2","CUP_Weapons","CIVILIAN"],
["L85A2 Grip","CUP_Weapon_arifle_L85A2_G","CUP_Weapons","CIVILIAN"],
["L85A2 Grip with Holo, Laser","CUP_Weapon_arifle_L85A2_Holo_laser","CUP_Weapons","CIVILIAN"],
["L85A2 Grip with SUSAT, Laser","CUP_Weapon_arifle_L85A2_SUSAT_Laser","CUP_Weapons","CIVILIAN"],
["L85A2 Grip with CWS, Laser","CUP_Weapon_arifle_L85A2_CWS_Laser","CUP_Weapons","CIVILIAN"],
["L85A2 Grip with ACPG, Laser","CUP_Weapon_arifle_L85A2_ACOG_Laser","CUP_Weapons","CIVILIAN"],
["L85A2 No Grip","CUP_Weapon_arifle_L85A2_NG","CUP_Weapons","CIVILIAN"],
["L85A2 Underbarrel","CUP_Weapon_arifle_L85A2_GL","CUP_Weapons","CIVILIAN"],
["L85A2 Underbarrel with Holo, Laser","CUP_Weapon_arifle_L85A2_GL_Holo_Laser","CUP_Weapons","CIVILIAN"],
["L85A2 Underbarrel with SUSAT, Laser","CUP_Weapon_arifle_L85A2_GL_SUSAT_Laser","CUP_Weapons","CIVILIAN"],
["L85A2 Underbarrel with ACOG, Laser","CUP_Weapon_arifle_L85A2_GL_ACOG_Laser","CUP_Weapons","CIVILIAN"],
["L86A2","CUP_Weapon_arifle_L86A2","CUP_Weapons","CIVILIAN"],
["L86A2 with ACOG","CUP_Weapon_arifle_L86A2_ACOG","CUP_Weapons","CIVILIAN"],
["M16A2","CUP_Weapon_arifle_M16A2","CUP_Weapons","CIVILIAN"],
["M16A2 Underbarrel","CUP_Weapon_arifle_M16A2_GL","CUP_Weapons","CIVILIAN"],
["M16A4","CUP_Weapon_arifle_M16A4_Base","CUP_Weapons","CIVILIAN"],
["M16A4 with AIM, Laser","CUP_Weapon_arifle_M16A4_Aim_Laser","CUP_Weapons","CIVILIAN"],
["M16A4 with ACOG, Laser","CUP_Weapon_arifle_M16A4_ACOG_Laser","CUP_Weapons","CIVILIAN"],
["M16A4 Underbarrel","CUP_Weapon_arifle_M16A4_GL","CUP_Weapons","CIVILIAN"],
["M16A4 Underbarrel with Laser","CUP_Weapon_arifle_M16A4_GL_Laser","CUP_Weapons","CIVILIAN"],
["M16A4 Underbarrel with ACOG, Laser","CUP_Weapon_arifle_M16A4_GL_ACOG_Laser","CUP_Weapons","CIVILIAN"],
["M4A1","CUP_Weapon_arifle_M4A1","CUP_Weapons","CIVILIAN"],
["M4A1 with AIM","CUP_Weapon_arifle_M4A1_Aim","CUP_Weapons","CIVILIAN"],
["M4A1 with Leupold Mk4 MRT","CUP_Weapon_arifle_M4A1_LeupoldMk4MRT","CUP_Weapons","CIVILIAN"],
["M4A1 with Leupold Mk4 CQT","CUP_Weapon_arifle_M4A1_LeupoldMk4CQT_Laser","CUP_Weapons","CIVILIAN"],
["M4A1 with AIM, Laser, Silencer","CUP_Weapon_arifle_M4A1_Aim_Laser_snds","CUP_Weapons","CIVILIAN"],
["M4A1 with Holo","CUP_Weapon_arifle_M4A1_Holo","CUP_Weapons","CIVILIAN"],
["M4A1 with Holo, Laser","CUP_Weapon_arifle_M4A1_Holo_Laser","CUP_Weapons","CIVILIAN"],
["M4A1 Woodland","CUP_Weapon_arifle_M4A1_camo","CUP_Weapons","CIVILIAN"],
["M4A1 Woodland with AIM","CUP_Weapon_arifle_M4A1_camo_Aim","CUP_Weapons","CIVILIAN"],
["M4A1 Woodland with AIM, Laser","CUP_Weapon_arifle_M4A1_camo_Aim_snds","CUP_Weapons","CIVILIAN"],
["M4A1 Black","CUP_Weapon_arifle_M4A1_black","CUP_Weapons","CIVILIAN"],
["M4A1 Desert","CUP_Weapon_arifle_M4A1_desert","CUP_Weapons","CIVILIAN"],
["M4A1 BUIS Underbarrel","CUP_Weapon_arifle_M4A1_BUIS_GL","CUP_Weapons","CIVILIAN"],
["M4A1 Woodland BUIS Underbarrel","CUP_Weapon_arifle_M4A1_BUIS_camo_GL","CUP_Weapons","CIVILIAN"],
["M4A1 Desert BUIS Underbarrel","CUP_Weapon_arifle_M4A1_BUIS_desert_GL","CUP_Weapons","CIVILIAN"],
["M4A1 Underbarrel with Holo, Flashlight","CUP_Weapon_arifle_M4A1_GL_Holo_Flashlight","CUP_Weapons","CIVILIAN"],
["M4A1 Underbarrel with ACOG, Flashlight","CUP_Weapon_arifle_M4A1_GL_ACOG_Flashlight","CUP_Weapons","CIVILIAN"],
["M4A1 Woodland Underbarrel with Holo, Flashlight","CUP_Weapon_arifle_M4A1_camo_GL_Holo_Flashlight","CUP_Weapons","CIVILIAN"],
["M4A1 Woodland Underbarrel with Holo, Flashlight, Silencer","CUP_Weapon_arifle_M4A1_camo_GL_Holo_Flashlight_Snds","CUP_Weapons","CIVILIAN"],
["M4A1 M203 (Woodland)","CUP_Weapon_arifle_M4A1_M203_ACOG_Laser","CUP_Weapons","CIVILIAN"],
["M4A1 Underbarrel with Holo, Laser","CUP_Weapon_arifle_M4A1_M203_Holo_Laser","CUP_Weapons","CIVILIAN"],
["M4A1 Underbarrel with ANPAS13C1, Laser","CUP_Weapon_arifle_M4A1_M203_ANPAS13c1_Laser","CUP_Weapons","CIVILIAN"],
["M4A3 Desert","CUP_Weapon_arifle_M4A3_desert","CUP_Weapons","CIVILIAN"],
["M4A3 Desert with AIM, Flashlight","CUP_Weapon_arifle_M4A3_desert_Aim_Flashlight","CUP_Weapons","CIVILIAN"],
["M4A3 Desert Underbarrel with ACOG, Laser","CUP_Weapon_arifle_M4A3_desert_GL_ACOG_Laser","CUP_Weapons","CIVILIAN"],
["SA58P","CUP_Weapon_arifle_Sa58P","CUP_Weapons","CIVILIAN"],
["SA58P Desert","CUP_Weapon_arifle_Sa58P_des","CUP_Weapons","CIVILIAN"],
["SA58V","CUP_Weapon_arifle_Sa58V","CUP_Weapons","CIVILIAN"],
["SA58V with ACOG, Laser","CUP_Weapon_arifle_Sa58V_ACOG_Laser","CUP_Weapons","CIVILIAN"],
["SA58V with AIM, Laser","CUP_Weapon_arifle_Sa58V_Aim_Laser","CUP_Weapons","CIVILIAN"],
["SA58V Desert","CUP_Weapon_arifle_Sa58V_camo","CUP_Weapons","CIVILIAN"],
["SA58 RIS1","CUP_Weapon_arifle_Sa58RIS1","CUP_Weapons","CIVILIAN"],
["SA58 RIS1 with ACOG, Laser","CUP_Weapon_arifle_Sa58RIS1_Aco_Laser","CUP_Weapons","CIVILIAN"],
["SA58 RIS1 Desert","CUP_Weapon_arifle_Sa58RIS1_des","CUP_Weapons","CIVILIAN"],
["SA58 RIS1 Desert with ACO, Laser","CUP_Weapon_arifle_Sa58RIS1_camo_Aco_Laser","CUP_Weapons","CIVILIAN"],
["SA58 RIS2","CUP_Weapon_arifle_Sa58RIS2","CUP_Weapons","CIVILIAN"],
["SA58 RIS2 with ARCO, Laser","CUP_Weapon_arifle_Sa58RIS2_Arco_Laser","CUP_Weapons","CIVILIAN"],
["SA58 RIS2 Desert","CUP_Weapon_arifle_Sa58RIS2_camo","CUP_Weapons","CIVILIAN"],
["SA58 RIS2 Desert with ARCO, Laser","CUP_Weapon_arifle_Sa58RIS2_camo_Arco_Laser","CUP_Weapons","CIVILIAN"],
["SA58 RIS2 Underbarrel","CUP_Weapon_arifle_Sa58RIS2_gl","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 CQC","CUP_Weapon_arifle_Mk16_CQC","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 CQC Foregrip","CUP_Weapon_arifle_Mk16_CQC_FG","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 CQC Foregrip with AIM, Laser, Silencer","CUP_Weapon_arifle_Mk16_CQC_FG_Aim_Laser_snds","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 CQC Surefire","CUP_Weapon_arifle_Mk16_CQC_SFG","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 CQC Surefire with Holo","CUP_Weapon_arifle_Mk16_CQC_SFG_Holo","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 CQC EGLM","CUP_Weapon_arifle_Mk16_CQC_EGLM","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 CQC EGLM with Holo, Laser, Flash Suppressor","CUP_Weapon_arifle_Mk16_CQC_EGLM_Holo_Laser_mfsup","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 CQC EGLM with ACOG, Laser","CUP_Weapon_arifle_Mk16_CQC_EGLM_ACOG_Laser","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 Standard","CUP_Weapon_arifle_Mk16_STD","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 Standard Fore Grip","CUP_Weapon_arifle_Mk16_STD_FG","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 Standard Fore Grip with Holo, Laser","CUP_Weapon_arifle_Mk16_STD_FG_Holo_Laser","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 Standard Fore Grip with Leupold Mk4 CQT, Laser","CUP_Weapon_arifle_Mk16_STD_FG_LeupoldMk4CQT_Laser","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 Standard SureFire","CUP_Weapon_arifle_Mk16_STD_SFG","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 Standard EGLM","CUP_Weapon_arifle_Mk16_STD_EGLM","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 Standard EGLM with ANPAS13C1, Laser, Flash Suppressor","CUP_Weapon_arifle_Mk16_STD_EGLM_ANPAS13c1_Laser_mfsup","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 SV","CUP_Weapon_arifle_Mk16_SV","CUP_Weapons","CIVILIAN"],
["Mk16 Mod 0 with Leupold Mk4 MRT","CUP_Weapon_arifle_Mk16_LeupoldMk4MRT","CUP_Weapons","CIVILIAN"],
["Mk17 Mod 0 CQC","CUP_Weapon_arifle_Mk17_CQC","CUP_Weapons","CIVILIAN"],
["Mk17 Mod 0 CQC Fore grip","CUP_Weapon_arifle_Mk17_CQC_FG","CUP_Weapons","CIVILIAN"],
["Mk17 Mod 0 CQC SureFire","CUP_Weapon_arifle_Mk17_CQC_SFG","CUP_Weapons","CIVILIAN"],
["Mk17 Mod 0 CQC SureFire with AIM, Flash Suppressor","CUP_Weapon_arifle_Mk17_CQC_SFG_Aim_mfsup","CUP_Weapons","CIVILIAN"],
["Mk17 Mod 0 CQC EGLM","CUP_Weapon_arifle_Mk17_CQC_EGLM","CUP_Weapons","CIVILIAN"],
["Mk17 Mod 0 Std","CUP_Weapon_arifle_Mk17_STD","CUP_Weapons","CIVILIAN"],
["Mk17 Mod 0 Std Fore grip","CUP_Weapon_arifle_Mk17_STD_FG","CUP_Weapons","CIVILIAN"],
["Mk17 Mod 0 Std Fore grip with AIM, Laser, Silencer","CUP_Weapon_arifle_Mk17_STD_FG_Aim_Laser_snds","CUP_Weapons","CIVILIAN"],
["Mk17 Mod 0 Std Fore grip with ANPAS13c1, Laser, Silencer","CUP_Weapon_arifle_Mk17_STD_FG_ANPAS13c1_Laser_Snds","CUP_Weapons","CIVILIAN"],
["Mk17 Mod 0 Std SureFire","CUP_Weapon_arifle_Mk17_STD_SFG","CUP_Weapons","CIVILIAN"],
["Mk17 Mod 0 Std EGLM","CUP_Weapon_arifle_Mk17_STD_EGLM","CUP_Weapons","CIVILIAN"],
["Mk17 Mod 0 Std EGLM with ELCAN, Laser","CUP_Weapon_arifle_Mk17_STD_EGLM_ElcanSpecter_Laser","CUP_Weapons","CIVILIAN"],
["Mk20 Mod 0","CUP_Weapon_arifle_Mk20","CUP_Weapons","CIVILIAN"],
["Mk20 Mod 0 with Leupold Mk4 MRT","CUP_Weapon_arifle_Mk20_LeupoldMk4MRT","CUP_Weapons","CIVILIAN"],
["Mk20 Mod 0 with SB11420, Silencer","CUP_Weapon_arifle_Mk20_SB11420_snds","CUP_Weapons","CIVILIAN"],
["XM8 (railed)","CUP_Weapon_arifle_XM8_Railed","CUP_Weapons","CIVILIAN"],
["XM8 (railed) with ANPAS13c1, Laser","CUP_Weapon_arifle_XM8_Railed_ANPAS13c1_Laser","CUP_Weapons","CIVILIAN"],
["XM8 (railed) with ANPAS13c1, Laser, Silencer","CUP_Weapon_arifle_XM8_Railed_ANPAS13c1_Laser_snds","CUP_Weapons","CIVILIAN"],
["XM8 (railed) with Holo, Laser","CUP_Weapon_arifle_XM8_Railed_Holo_Laser_snds","CUP_Weapons","CIVILIAN"],
["XM8 Carbine","CUP_Weapon_arifle_XM8_Carbine","CUP_Weapons","CIVILIAN"],
["XM8 M320","CUP_Weapon_arifle_XM8_Carbine_GL","CUP_Weapons","CIVILIAN"],
["XM8 CQC","CUP_Weapon_arifle_XM8_Carbine_FG","CUP_Weapons","CIVILIAN"],
["XM8 Sharpshooter","CUP_Weapon_arifle_xm8_sharpshooter","CUP_Weapons","CIVILIAN"],
["XM8 SAW","CUP_Weapon_arifle_xm8_SAW","CUP_Weapons","CIVILIAN"],
["XM8 Compact","CUP_Weapon_arifle_XM8_Compact","CUP_Weapons","CIVILIAN"],
["XM8 Compact (railed)","CUP_Weapon_arifle_XM8_Compact_Rail","CUP_Weapons","CIVILIAN"],
["XM8 Compact (railed) with Holo, Flashlight","CUP_Weapon_arifle_XM8_Compact_Holo_Flashlight","CUP_Weapons","CIVILIAN"]]
