[["Motorboot (Rettung)","C_Boat_Civil_01_rescue_F","TFAR","CIVILIAN"],
["Motorboot (Polizei)","C_Boat_Civil_01_police_F","TFAR","CIVILIAN"],
["Kleines Boot","Land_BoatSmall_1","CUP_Terrains_-_Core","CIVILIAN"],
["Kleines Boot II","Land_BoatSmall_2a","CUP_Terrains_-_Core","CIVILIAN"],
["Kleines Boot III","Land_BoatSmall_2b","CUP_Terrains_-_Core","CIVILIAN"],
["LCU-1610","CUP_B_LCU1600_USMC","CUP_Vehicles","WEST"],
["LCU-1610","CUP_B_LCU1600_HIL","CUP_Vehicles","WEST"],
["LCU-1610","CUP_I_LCU1600_RACS","CUP_Vehicles","RESISTANCE"],
["LCVP","CUP_I_LCVP_RACS","CUP_Vehicles","RESISTANCE"],
["LCVP (VIV)","CUP_I_LCVP_VIV_RACS","CUP_Vehicles","RESISTANCE"],
["LCVP","CUP_O_LCVP_SLA","CUP_Vehicles","EAST"],
["LCVP (VIV)","CUP_O_LCVP_VIV_SLA","CUP_Vehicles","EAST"],
["LCU Mk.10","CUP_B_MK10_GB","CUP_Vehicles","WEST"],
["Zubr-Class LCAC","CUP_B_ZUBR_CDF","CUP_Vehicles","WEST"],
["Zubr-Class LCAC","CUP_O_ZUBR_RU","CUP_Vehicles","EAST"],
["Zubr-Class LCAC","CUP_O_ZUBR_CSAT_T","CUP_Vehicles","EAST"],
["Zubr-Class LCAC","CUP_O_ZUBR_SLA","CUP_Vehicles","EAST"],
["Zubr-Class LCAC","CUP_I_ZUBR_AAF","CUP_Vehicles","RESISTANCE"],
["Zubr-Class LCAC","CUP_I_ZUBR_UN","CUP_Vehicles","RESISTANCE"],
["ZurÃ¼ckgelassenes Boot (Blau)","Land_Boat_01_abandoned_blue_F","expansion","CIVILIAN"],
["ZurÃ¼ckgelassenes Boot (Rot)","Land_Boat_01_abandoned_red_F","expansion","CIVILIAN"],
["ZurÃ¼ckgelassenes Boot (Motor)","Land_Boat_02_abandoned_F","expansion","CIVILIAN"],
["ZurÃ¼ckgelassenes Boot (Trockendock)","Land_Boat_03_abandoned_F","expansion","CIVILIAN"],
["Altes Bootswrack","Land_Boat_04_wreck_F","expansion","CIVILIAN"],
["Bootswrack Holz","Land_Boat_05_wreck_F","expansion","CIVILIAN"],
["Bootswrack Metall","Land_Boat_06_wreck_F","expansion","CIVILIAN"],
["Schnellboot-Minigun","B_T_Boat_Armed_01_minigun_F","expansion","WEST"],
["Schnellboot-HMG","O_T_Boat_Armed_01_hmg_F","expansion","EAST"],
["Kampfboot","O_T_Boat_Transport_01_F","expansion","EAST"],
["Kampfboot","I_C_Boat_Transport_01_F","expansion","RESISTANCE"],
["Kampfboot","B_T_Boat_Transport_01_F","expansion","WEST"],
["Rettungsboot","B_T_Lifeboat","expansion","WEST"],
["Rettungsboot","O_T_Lifeboat","expansion","EAST"],
["RHIB","I_C_Boat_Transport_02_F","expansion","RESISTANCE"],
["RHIB","C_Boat_Transport_02_F","expansion","CIVILIAN"],
["Wasser-Scooter","C_Scooter_Transport_01_F","expansion","CIVILIAN"],
["Seafox (Target)","CUP_B_Seafox_USMC","CUP_Vehicles","WEST"],
["Zodiac","CUP_B_Zodiac_USMC","CUP_Vehicles","WEST"],
["Zodiac","CUP_C_Zodiac_CIV","CUP_Vehicles","CIVILIAN"],
["Kampfboot","CUP_B_HIL_Boat_Transport_01_F","CUP_Vehicles","WEST"],
["Fishing Boat","CUP_C_Fishing_Boat_Chernarus","CUP_Vehicles","CIVILIAN"],
["PBX","CUP_O_PBX_RU","CUP_Vehicles","EAST"],
["PBX","CUP_O_PBX_SLA","CUP_Vehicles","EAST"],
["PBX","CUP_C_PBX_CIV","CUP_Vehicles","CIVILIAN"],
["RHIB","CUP_B_RHIB_USMC","CUP_Vehicles","WEST"],
["RHIB (Mk19)","CUP_B_RHIB2Turret_USMC","CUP_Vehicles","WEST"],
["RHIB","CUP_B_RHIB_HIL","CUP_Vehicles","WEST"],
["RHIB (Mk19)","CUP_B_RHIB2Turret_HIL","CUP_Vehicles","WEST"],
["RHIB","CUP_I_RHIB_RACS","CUP_Vehicles","RESISTANCE"],
["RHIB (Mk19)","CUP_I_RHIB2Turret_RACS","CUP_Vehicles","RESISTANCE"],
["ANZAC Class Frigate","CUP_B_Frigate_ANZAC","CUP_Vehicles","WEST"],
["MEKO 200 Frigate","CUP_I_Frigate_AAF","CUP_Vehicles","RESISTANCE"],
["MEKO 200 Frigate","CUP_I_Frigate_RACS","CUP_Vehicles","RESISTANCE"]]
