[["ARCO (Schwarz)","Item_optic_Arco_blk_F","expansion","CIVILIAN"],
["ARCO (GrÃ¼ne Sechsecke)","Item_optic_Arco_ghex_F","expansion","CIVILIAN"],
["DMS (GrÃ¼ne Sechsecke)","Item_optic_DMS_ghex_F","expansion","CIVILIAN"],
["ERCO (Schwarz)","Item_optic_ERCO_blk_F","expansion","CIVILIAN"],
["ERCO (Khaki)","Item_optic_ERCO_khk_F","expansion","CIVILIAN"],
["ERCO (Sand)","Item_optic_ERCO_snd_F","expansion","CIVILIAN"],
["RCO (Khaki)","Item_optic_Hamr_khk_F","expansion","CIVILIAN"],
["MOS (Khaki)","Item_optic_SOS_khk_F","expansion","CIVILIAN"],
["LRPS (Tropen)","Item_optic_LRPS_tna_F","expansion","CIVILIAN"],
["LRPS (GrÃ¼ne Sechsecke)","Item_optic_LRPS_ghex_F","expansion","CIVILIAN"],
["C79A1","gm_placeableItem_c79a1_blk","GM","CIVILIAN"],
["C79A1 (Oliv)","gm_placeableItem_c79a1_oli","GM","CIVILIAN"],
["Fero Z-24","gm_placeableItem_feroz24_blk","GM","CIVILIAN"],
["Fero Z-24 (WÃ¼ste)","gm_placeableItem_feroz24_des","GM","CIVILIAN"],
["Fero Z 2x17","gm_placeableItem_feroz2x17_pzf44_2_blk","GM","CIVILIAN"],
["Fero Z 2x17 (WÃ¼ste)","gm_placeableItem_feroz2x17_pzf44_2_des","GM","CIVILIAN"],
["Fero Z 2x17 (Winter)","gm_placeableItem_feroz2x17_pzf44_2_win","GM","CIVILIAN"],
["Fero Z 2x17","gm_placeableItem_feroz2x17_pzf84_blk","GM","CIVILIAN"],
["Fero Z 2x17 (WÃ¼ste)","gm_placeableItem_feroz2x17_pzf84_des","GM","CIVILIAN"],
["Fero Z 2x17 (Winter)","gm_placeableItem_feroz2x17_pzf84_win","GM","CIVILIAN"],
["PGO-7V","gm_placeableItem_pgo7v_blk","GM","CIVILIAN"],
["PSO-1","gm_placeableItem_pso1_gry","GM","CIVILIAN"],
["ZFK 4x25","gm_placeableItem_zfk4x25_blk","GM","CIVILIAN"],
["Boden","CUP_Weapons_Optics_Base","CUP_Weapons","CIVILIAN"],
["PSO-1 Scope","CUP_Item_optic_PSO_1","CUP_Weapons","CIVILIAN"],
["PSO-3 Scope","CUP_Item_optic_PSO_3","CUP_Weapons","CIVILIAN"],
["Kobra Reflex Sight","CUP_Item_optic_Kobra","CUP_Weapons","CIVILIAN"],
["GOSHAWK TWS","CUP_Item_optic_GOSHAWK","CUP_Weapons","CIVILIAN"],
["NSPU Scope","CUP_Item_optic_NSPU","CUP_Weapons","CIVILIAN"],
["Pecheneg Scope","CUP_Item_optic_PechenegScope","CUP_Weapons","CIVILIAN"],
["MAAWS Aiming Scope","CUP_Item_optic_MAAWS_Scope","CUP_Weapons","CIVILIAN"],
["SMAW Optical Scope","CUP_Item_optic_SMAW_Scope","CUP_Weapons","CIVILIAN"],
["Schmidt & Bender 3-12x60 PM II","CUP_Item_optic_SB_3_12x50_PMII","CUP_Weapons","CIVILIAN"],
["AN/PAS 13C2 Heavy Thermal Weapon Sight","CUP_Item_optic_AN_PAS_13c2","CUP_Weapons","CIVILIAN"],
["Leupold Mk4","CUP_Item_optic_LeupoldMk4","CUP_Weapons","CIVILIAN"],
["EoTech Holo (black)","CUP_Item_optic_HoloBlack","CUP_Weapons","CIVILIAN"],
["EoTech Holo (Woodland)","CUP_Item_optic_HoloWdl","CUP_Weapons","CIVILIAN"],
["EoTech Holo (Desert)","CUP_Item_optic_HoloDesert","CUP_Weapons","CIVILIAN"],
["EoTech 533 HWS (tan)","CUP_Item_optic_Eotech533","CUP_Weapons","CIVILIAN"],
["EoTech 533 HWS (grey)","CUP_Item_optic_Eotech533Grey","CUP_Weapons","CIVILIAN"],
["Aimpoint CompM4 (black)","CUP_Item_optic_CompM4","CUP_Weapons","CIVILIAN"],
["SUSAT L9A1","CUP_Item_optic_SUSAT","CUP_Weapons","CIVILIAN"],
["Trijicon ACOG TA31F","CUP_Item_optic_ACOG","CUP_Weapons","CIVILIAN"],
["Advanced Weapon Sight CWS","CUP_Item_optic_CWS","CUP_Weapons","CIVILIAN"],
["Leupold VX-3 4.5-14x50mm","CUP_Item_optic_Leupold_VX3","CUP_Weapons","CIVILIAN"],
["AN/PVS-10 Night Vision Scope","CUP_Item_optic_AN_PVS_10","CUP_Weapons","CIVILIAN"],
["M68 CCO (Black)","CUP_Item_optic_CompM2_Black","CUP_Weapons","CIVILIAN"],
["M68 CCO (Woodland)","CUP_Item_optic_CompM2_Woodland","CUP_Weapons","CIVILIAN"],
["M68 CCO (Woodland 2)","CUP_Item_optic_CompM2_Woodland2","CUP_Weapons","CIVILIAN"],
["M68 CCO (Desert)","CUP_Item_optic_CompM2_Desert","CUP_Weapons","CIVILIAN"],
["Trijicon ACOG","CUP_Item_optic_RCO","CUP_Weapons","CIVILIAN"],
["Trijicon ACOG (desert)","CUP_Item_optic_RCO_desert","CUP_Weapons","CIVILIAN"],
["Leupold Mark 4 3-9x36mm MR/T","CUP_Item_optic_LeupoldM3LR","CUP_Weapons","CIVILIAN"],
["Leupold Mark 4 10x40mm LR/T (Desert)","CUP_Item_optic_LeupoldMk4_10x40_LRT_Desert","CUP_Weapons","CIVILIAN"],
["Leupold Mark 4 10x40mm LR/T (Woodland)","CUP_Item_optic_LeupoldMk4_10x40_LRT_Woodland","CUP_Weapons","CIVILIAN"],
["Elcan M145","CUP_Item_optic_ElcanM145","CUP_Weapons","CIVILIAN"],
["AN/PAS 13C1 Light Thermal Weapon Sight","CUP_Item_optic_AN_PAS_13c1","CUP_Weapons","CIVILIAN"],
["Leupold Mk4 CQ/T 1-3x14mm","CUP_Item_optic_LeupoldMk4_CQ_T","CUP_Weapons","CIVILIAN"],
["Elcan SpecterDR","CUP_Item_optic_ELCAN_SpecterDR","CUP_Weapons","CIVILIAN"],
["Leupold Mk4 MR/T (tan)","CUP_Item_optic_LeupoldMk4_MRT_tan","CUP_Weapons","CIVILIAN"],
["Schmidt & Bender 1.1-4x20 PM ShortDot","CUP_Item_optic_SB_11_4x20_PM","CUP_Weapons","CIVILIAN"],
["Meopta ZD-Dot","CUP_Item_optic_ZDDot","CUP_Weapons","CIVILIAN"],
["Meopta Rapid Acquisition Dot","CUP_Item_optic_MRad","CUP_Weapons","CIVILIAN"],
["Trijicon Rx01 Red Dot sight (desert)","CUP_Item_optic_TrijiconRx01_desert","CUP_Weapons","CIVILIAN"],
["Trijicon Rx01 Red Dot sight (black)","CUP_Item_optic_TrijiconRx01_black","CUP_Weapons","CIVILIAN"],
["AN/PVS-4 Night Vision Scope","CUP_Item_optic_AN_PVS_4","CUP_Weapons","CIVILIAN"]]
