[["SchalldÃ¤mpfer (6,5 mm, Khaki)","Item_muzzle_snds_H_khk_F","expansion","CIVILIAN"],
["SchalldÃ¤mpfer (5,56 mm, Khaki)","Item_muzzle_snds_m_khk_F","expansion","CIVILIAN"],
["SchalldÃ¤mpfer (5,56 mm, Sand)","Item_muzzle_snds_m_snd_F","expansion","CIVILIAN"],
["SchalldÃ¤mpfer (7,62 mm, Khaki)","Item_muzzle_snds_B_khk_F","expansion","CIVILIAN"],
["SchalldÃ¤mpfer (7,62 mm, Sand)","Item_muzzle_snds_B_snd_F","expansion","CIVILIAN"],
["SchalldÃ¤mpfer LMG (6,5 mm, Schwarz)","Item_muzzle_snds_H_MG_blk_F","expansion","CIVILIAN"],
["SchalldÃ¤mpfer LMG (6,5 mm, Khaki)","Item_muzzle_snds_H_MG_khk_F","expansion","CIVILIAN"],
["Tarn-SchalldÃ¤mpfer (6,5 mm, Schwarz)","Item_muzzle_snds_65_TI_blk_F","expansion","CIVILIAN"],
["Tarn-SchalldÃ¤mpfer (6,5 mm, Sechseck)","Item_muzzle_snds_65_TI_hex_F","expansion","CIVILIAN"],
["Tarn-SchalldÃ¤mpfer (6,5 mm, GrÃ¼ne Sechsecke)","Item_muzzle_snds_65_TI_ghex_F","expansion","CIVILIAN"],
["Tarn-SchalldÃ¤mpfer (5,8 mm, Schwarz)","Item_muzzle_snds_58_blk_F","expansion","CIVILIAN"],
["Tarn-SchalldÃ¤mpfer (5,8 mm, GrÃ¼ne Sechsecke)","Item_muzzle_snds_58_wdm_F","expansion","CIVILIAN"],
["Boden","CUP_Weapons_FrontSlot_Base","CUP_Weapons","CIVILIAN"],
["PBS4 silencer","CUP_Item_muzzle_PBS4","CUP_Weapons","CIVILIAN"],
["PB 6P9 silencer","CUP_Item_muzzle_PB6P9","CUP_Weapons","CIVILIAN"],
["PP-19 Bizon silencer","CUP_Item_muzzle_Bizon","CUP_Weapons","CIVILIAN"],
["Silencer M110","CUP_Item_muzzle_snds_M110","CUP_Weapons","CIVILIAN"],
["Silencer M14","CUP_Item_muzzle_snds_M14","CUP_Weapons","CIVILIAN"],
["Silencer (M9)","CUP_Item_muzzle_snds_M9","CUP_Weapons","CIVILIAN"],
["Silencer (MicroUzi)","CUP_Item_muzzle_snds_MicroUzi","CUP_Weapons","CIVILIAN"],
["Silencer L115A1/AWM","CUP_Item_muzzle_snds_AWM","CUP_Weapons","CIVILIAN"],
["G36 Silencer (black)","CUP_Item_muzzle_snds_G36_black","CUP_Weapons","CIVILIAN"],
["G36 Silencer (desert)","CUP_Item_muzzle_snds_G36_desert","CUP_Weapons","CIVILIAN"],
["L85 Silencer","CUP_Item_muzzle_snds_L85","CUP_Weapons","CIVILIAN"],
["M16 / M4 Silencer (camo)","CUP_Item_muzzle_snds_M16_camo","CUP_Weapons","CIVILIAN"],
["M16 / M4 Silencer (black)","CUP_Item_muzzle_snds_M16","CUP_Weapons","CIVILIAN"],
["Mk16 Silencer","CUP_Item_muzzle_snds_SCAR_L","CUP_Weapons","CIVILIAN"],
["Mk16 Flash Hider","CUP_Item_muzzle_mfsup_SCAR_L","CUP_Weapons","CIVILIAN"],
["Mk17 Silencer","CUP_Item_muzzle_snds_SCAR_H","CUP_Weapons","CIVILIAN"],
["Mk17 Flash Hider","CUP_Item_muzzle_mfsup_SCAR_H","CUP_Weapons","CIVILIAN"],
["XM8 Silencer","CUP_Item_muzzle_snds_XM8","CUP_Weapons","CIVILIAN"],
["Mk12 SPR Silencer","CUP_Item_muzzle_snds_Mk12","CUP_Weapons","CIVILIAN"],
["Surefire FlashHider","CUP_Item_acc_sffh","CUP_Weapons","CIVILIAN"],
["BFA","CUP_Item_acc_BFA","CUP_Weapons","CIVILIAN"]]
